// Code generated by capnpc-go. DO NOT EDIT.

package custom

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
)

type CustomReserved0 capnp.Struct

// CustomReserved0_TypeID is the unique identifier for the type CustomReserved0.
const CustomReserved0_TypeID = 0x81c2f05a394cf4af

func NewCustomReserved0(s *capnp.Segment) (CustomReserved0, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved0(st), err
}

func NewRootCustomReserved0(s *capnp.Segment) (CustomReserved0, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved0(st), err
}

func ReadRootCustomReserved0(msg *capnp.Message) (CustomReserved0, error) {
	root, err := msg.Root()
	return CustomReserved0(root.Struct()), err
}

func (s CustomReserved0) String() string {
	str, _ := text.Marshal(0x81c2f05a394cf4af, capnp.Struct(s))
	return str
}

func (s CustomReserved0) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved0) DecodeFromPtr(p capnp.Ptr) CustomReserved0 {
	return CustomReserved0(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved0) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved0) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved0) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved0) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved0_List is a list of CustomReserved0.
type CustomReserved0_List = capnp.StructList[CustomReserved0]

// NewCustomReserved0 creates a new list of CustomReserved0.
func NewCustomReserved0_List(s *capnp.Segment, sz int32) (CustomReserved0_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved0](l), err
}

// CustomReserved0_Future is a wrapper for a CustomReserved0 promised by a client call.
type CustomReserved0_Future struct{ *capnp.Future }

func (f CustomReserved0_Future) Struct() (CustomReserved0, error) {
	p, err := f.Future.Ptr()
	return CustomReserved0(p.Struct()), err
}

type CustomReserved1 capnp.Struct

// CustomReserved1_TypeID is the unique identifier for the type CustomReserved1.
const CustomReserved1_TypeID = 0xaedffd8f31e7b55d

func NewCustomReserved1(s *capnp.Segment) (CustomReserved1, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved1(st), err
}

func NewRootCustomReserved1(s *capnp.Segment) (CustomReserved1, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved1(st), err
}

func ReadRootCustomReserved1(msg *capnp.Message) (CustomReserved1, error) {
	root, err := msg.Root()
	return CustomReserved1(root.Struct()), err
}

func (s CustomReserved1) String() string {
	str, _ := text.Marshal(0xaedffd8f31e7b55d, capnp.Struct(s))
	return str
}

func (s CustomReserved1) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved1) DecodeFromPtr(p capnp.Ptr) CustomReserved1 {
	return CustomReserved1(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved1) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved1) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved1) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved1) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved1_List is a list of CustomReserved1.
type CustomReserved1_List = capnp.StructList[CustomReserved1]

// NewCustomReserved1 creates a new list of CustomReserved1.
func NewCustomReserved1_List(s *capnp.Segment, sz int32) (CustomReserved1_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved1](l), err
}

// CustomReserved1_Future is a wrapper for a CustomReserved1 promised by a client call.
type CustomReserved1_Future struct{ *capnp.Future }

func (f CustomReserved1_Future) Struct() (CustomReserved1, error) {
	p, err := f.Future.Ptr()
	return CustomReserved1(p.Struct()), err
}

type CustomReserved2 capnp.Struct

// CustomReserved2_TypeID is the unique identifier for the type CustomReserved2.
const CustomReserved2_TypeID = 0xf35cc4560bbf6ec2

func NewCustomReserved2(s *capnp.Segment) (CustomReserved2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved2(st), err
}

func NewRootCustomReserved2(s *capnp.Segment) (CustomReserved2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved2(st), err
}

func ReadRootCustomReserved2(msg *capnp.Message) (CustomReserved2, error) {
	root, err := msg.Root()
	return CustomReserved2(root.Struct()), err
}

func (s CustomReserved2) String() string {
	str, _ := text.Marshal(0xf35cc4560bbf6ec2, capnp.Struct(s))
	return str
}

func (s CustomReserved2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved2) DecodeFromPtr(p capnp.Ptr) CustomReserved2 {
	return CustomReserved2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved2_List is a list of CustomReserved2.
type CustomReserved2_List = capnp.StructList[CustomReserved2]

// NewCustomReserved2 creates a new list of CustomReserved2.
func NewCustomReserved2_List(s *capnp.Segment, sz int32) (CustomReserved2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved2](l), err
}

// CustomReserved2_Future is a wrapper for a CustomReserved2 promised by a client call.
type CustomReserved2_Future struct{ *capnp.Future }

func (f CustomReserved2_Future) Struct() (CustomReserved2, error) {
	p, err := f.Future.Ptr()
	return CustomReserved2(p.Struct()), err
}

type CustomReserved3 capnp.Struct

// CustomReserved3_TypeID is the unique identifier for the type CustomReserved3.
const CustomReserved3_TypeID = 0xda96579883444c35

func NewCustomReserved3(s *capnp.Segment) (CustomReserved3, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved3(st), err
}

func NewRootCustomReserved3(s *capnp.Segment) (CustomReserved3, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved3(st), err
}

func ReadRootCustomReserved3(msg *capnp.Message) (CustomReserved3, error) {
	root, err := msg.Root()
	return CustomReserved3(root.Struct()), err
}

func (s CustomReserved3) String() string {
	str, _ := text.Marshal(0xda96579883444c35, capnp.Struct(s))
	return str
}

func (s CustomReserved3) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved3) DecodeFromPtr(p capnp.Ptr) CustomReserved3 {
	return CustomReserved3(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved3) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved3) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved3) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved3) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved3_List is a list of CustomReserved3.
type CustomReserved3_List = capnp.StructList[CustomReserved3]

// NewCustomReserved3 creates a new list of CustomReserved3.
func NewCustomReserved3_List(s *capnp.Segment, sz int32) (CustomReserved3_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved3](l), err
}

// CustomReserved3_Future is a wrapper for a CustomReserved3 promised by a client call.
type CustomReserved3_Future struct{ *capnp.Future }

func (f CustomReserved3_Future) Struct() (CustomReserved3, error) {
	p, err := f.Future.Ptr()
	return CustomReserved3(p.Struct()), err
}

type CustomReserved4 capnp.Struct

// CustomReserved4_TypeID is the unique identifier for the type CustomReserved4.
const CustomReserved4_TypeID = 0x80ae746ee2596b11

func NewCustomReserved4(s *capnp.Segment) (CustomReserved4, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved4(st), err
}

func NewRootCustomReserved4(s *capnp.Segment) (CustomReserved4, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved4(st), err
}

func ReadRootCustomReserved4(msg *capnp.Message) (CustomReserved4, error) {
	root, err := msg.Root()
	return CustomReserved4(root.Struct()), err
}

func (s CustomReserved4) String() string {
	str, _ := text.Marshal(0x80ae746ee2596b11, capnp.Struct(s))
	return str
}

func (s CustomReserved4) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved4) DecodeFromPtr(p capnp.Ptr) CustomReserved4 {
	return CustomReserved4(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved4) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved4) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved4) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved4) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved4_List is a list of CustomReserved4.
type CustomReserved4_List = capnp.StructList[CustomReserved4]

// NewCustomReserved4 creates a new list of CustomReserved4.
func NewCustomReserved4_List(s *capnp.Segment, sz int32) (CustomReserved4_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved4](l), err
}

// CustomReserved4_Future is a wrapper for a CustomReserved4 promised by a client call.
type CustomReserved4_Future struct{ *capnp.Future }

func (f CustomReserved4_Future) Struct() (CustomReserved4, error) {
	p, err := f.Future.Ptr()
	return CustomReserved4(p.Struct()), err
}

type CustomReserved5 capnp.Struct

// CustomReserved5_TypeID is the unique identifier for the type CustomReserved5.
const CustomReserved5_TypeID = 0xa5cd762cd951a455

func NewCustomReserved5(s *capnp.Segment) (CustomReserved5, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved5(st), err
}

func NewRootCustomReserved5(s *capnp.Segment) (CustomReserved5, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved5(st), err
}

func ReadRootCustomReserved5(msg *capnp.Message) (CustomReserved5, error) {
	root, err := msg.Root()
	return CustomReserved5(root.Struct()), err
}

func (s CustomReserved5) String() string {
	str, _ := text.Marshal(0xa5cd762cd951a455, capnp.Struct(s))
	return str
}

func (s CustomReserved5) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved5) DecodeFromPtr(p capnp.Ptr) CustomReserved5 {
	return CustomReserved5(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved5) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved5) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved5) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved5) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved5_List is a list of CustomReserved5.
type CustomReserved5_List = capnp.StructList[CustomReserved5]

// NewCustomReserved5 creates a new list of CustomReserved5.
func NewCustomReserved5_List(s *capnp.Segment, sz int32) (CustomReserved5_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved5](l), err
}

// CustomReserved5_Future is a wrapper for a CustomReserved5 promised by a client call.
type CustomReserved5_Future struct{ *capnp.Future }

func (f CustomReserved5_Future) Struct() (CustomReserved5, error) {
	p, err := f.Future.Ptr()
	return CustomReserved5(p.Struct()), err
}

type CustomReserved6 capnp.Struct

// CustomReserved6_TypeID is the unique identifier for the type CustomReserved6.
const CustomReserved6_TypeID = 0xf98d843bfd7004a3

func NewCustomReserved6(s *capnp.Segment) (CustomReserved6, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved6(st), err
}

func NewRootCustomReserved6(s *capnp.Segment) (CustomReserved6, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved6(st), err
}

func ReadRootCustomReserved6(msg *capnp.Message) (CustomReserved6, error) {
	root, err := msg.Root()
	return CustomReserved6(root.Struct()), err
}

func (s CustomReserved6) String() string {
	str, _ := text.Marshal(0xf98d843bfd7004a3, capnp.Struct(s))
	return str
}

func (s CustomReserved6) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved6) DecodeFromPtr(p capnp.Ptr) CustomReserved6 {
	return CustomReserved6(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved6) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved6) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved6) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved6) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved6_List is a list of CustomReserved6.
type CustomReserved6_List = capnp.StructList[CustomReserved6]

// NewCustomReserved6 creates a new list of CustomReserved6.
func NewCustomReserved6_List(s *capnp.Segment, sz int32) (CustomReserved6_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved6](l), err
}

// CustomReserved6_Future is a wrapper for a CustomReserved6 promised by a client call.
type CustomReserved6_Future struct{ *capnp.Future }

func (f CustomReserved6_Future) Struct() (CustomReserved6, error) {
	p, err := f.Future.Ptr()
	return CustomReserved6(p.Struct()), err
}

type CustomReserved7 capnp.Struct

// CustomReserved7_TypeID is the unique identifier for the type CustomReserved7.
const CustomReserved7_TypeID = 0xb86e6369214c01c8

func NewCustomReserved7(s *capnp.Segment) (CustomReserved7, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved7(st), err
}

func NewRootCustomReserved7(s *capnp.Segment) (CustomReserved7, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved7(st), err
}

func ReadRootCustomReserved7(msg *capnp.Message) (CustomReserved7, error) {
	root, err := msg.Root()
	return CustomReserved7(root.Struct()), err
}

func (s CustomReserved7) String() string {
	str, _ := text.Marshal(0xb86e6369214c01c8, capnp.Struct(s))
	return str
}

func (s CustomReserved7) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved7) DecodeFromPtr(p capnp.Ptr) CustomReserved7 {
	return CustomReserved7(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved7) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved7) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved7) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved7) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved7_List is a list of CustomReserved7.
type CustomReserved7_List = capnp.StructList[CustomReserved7]

// NewCustomReserved7 creates a new list of CustomReserved7.
func NewCustomReserved7_List(s *capnp.Segment, sz int32) (CustomReserved7_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved7](l), err
}

// CustomReserved7_Future is a wrapper for a CustomReserved7 promised by a client call.
type CustomReserved7_Future struct{ *capnp.Future }

func (f CustomReserved7_Future) Struct() (CustomReserved7, error) {
	p, err := f.Future.Ptr()
	return CustomReserved7(p.Struct()), err
}

type CustomReserved8 capnp.Struct

// CustomReserved8_TypeID is the unique identifier for the type CustomReserved8.
const CustomReserved8_TypeID = 0xf416ec09499d9d19

func NewCustomReserved8(s *capnp.Segment) (CustomReserved8, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved8(st), err
}

func NewRootCustomReserved8(s *capnp.Segment) (CustomReserved8, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved8(st), err
}

func ReadRootCustomReserved8(msg *capnp.Message) (CustomReserved8, error) {
	root, err := msg.Root()
	return CustomReserved8(root.Struct()), err
}

func (s CustomReserved8) String() string {
	str, _ := text.Marshal(0xf416ec09499d9d19, capnp.Struct(s))
	return str
}

func (s CustomReserved8) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved8) DecodeFromPtr(p capnp.Ptr) CustomReserved8 {
	return CustomReserved8(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved8) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved8) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved8) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved8) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved8_List is a list of CustomReserved8.
type CustomReserved8_List = capnp.StructList[CustomReserved8]

// NewCustomReserved8 creates a new list of CustomReserved8.
func NewCustomReserved8_List(s *capnp.Segment, sz int32) (CustomReserved8_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved8](l), err
}

// CustomReserved8_Future is a wrapper for a CustomReserved8 promised by a client call.
type CustomReserved8_Future struct{ *capnp.Future }

func (f CustomReserved8_Future) Struct() (CustomReserved8, error) {
	p, err := f.Future.Ptr()
	return CustomReserved8(p.Struct()), err
}

type CustomReserved9 capnp.Struct

// CustomReserved9_TypeID is the unique identifier for the type CustomReserved9.
const CustomReserved9_TypeID = 0xa1680744031fdb2d

func NewCustomReserved9(s *capnp.Segment) (CustomReserved9, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved9(st), err
}

func NewRootCustomReserved9(s *capnp.Segment) (CustomReserved9, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved9(st), err
}

func ReadRootCustomReserved9(msg *capnp.Message) (CustomReserved9, error) {
	root, err := msg.Root()
	return CustomReserved9(root.Struct()), err
}

func (s CustomReserved9) String() string {
	str, _ := text.Marshal(0xa1680744031fdb2d, capnp.Struct(s))
	return str
}

func (s CustomReserved9) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved9) DecodeFromPtr(p capnp.Ptr) CustomReserved9 {
	return CustomReserved9(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved9) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved9) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved9) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved9) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved9_List is a list of CustomReserved9.
type CustomReserved9_List = capnp.StructList[CustomReserved9]

// NewCustomReserved9 creates a new list of CustomReserved9.
func NewCustomReserved9_List(s *capnp.Segment, sz int32) (CustomReserved9_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved9](l), err
}

// CustomReserved9_Future is a wrapper for a CustomReserved9 promised by a client call.
type CustomReserved9_Future struct{ *capnp.Future }

func (f CustomReserved9_Future) Struct() (CustomReserved9, error) {
	p, err := f.Future.Ptr()
	return CustomReserved9(p.Struct()), err
}

type CustomReserved10 capnp.Struct

// CustomReserved10_TypeID is the unique identifier for the type CustomReserved10.
const CustomReserved10_TypeID = 0xcb9fd56c7057593a

func NewCustomReserved10(s *capnp.Segment) (CustomReserved10, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved10(st), err
}

func NewRootCustomReserved10(s *capnp.Segment) (CustomReserved10, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved10(st), err
}

func ReadRootCustomReserved10(msg *capnp.Message) (CustomReserved10, error) {
	root, err := msg.Root()
	return CustomReserved10(root.Struct()), err
}

func (s CustomReserved10) String() string {
	str, _ := text.Marshal(0xcb9fd56c7057593a, capnp.Struct(s))
	return str
}

func (s CustomReserved10) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved10) DecodeFromPtr(p capnp.Ptr) CustomReserved10 {
	return CustomReserved10(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved10) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved10) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved10) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved10) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved10_List is a list of CustomReserved10.
type CustomReserved10_List = capnp.StructList[CustomReserved10]

// NewCustomReserved10 creates a new list of CustomReserved10.
func NewCustomReserved10_List(s *capnp.Segment, sz int32) (CustomReserved10_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved10](l), err
}

// CustomReserved10_Future is a wrapper for a CustomReserved10 promised by a client call.
type CustomReserved10_Future struct{ *capnp.Future }

func (f CustomReserved10_Future) Struct() (CustomReserved10, error) {
	p, err := f.Future.Ptr()
	return CustomReserved10(p.Struct()), err
}

type CustomReserved11 capnp.Struct

// CustomReserved11_TypeID is the unique identifier for the type CustomReserved11.
const CustomReserved11_TypeID = 0xc2243c65e0340384

func NewCustomReserved11(s *capnp.Segment) (CustomReserved11, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved11(st), err
}

func NewRootCustomReserved11(s *capnp.Segment) (CustomReserved11, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved11(st), err
}

func ReadRootCustomReserved11(msg *capnp.Message) (CustomReserved11, error) {
	root, err := msg.Root()
	return CustomReserved11(root.Struct()), err
}

func (s CustomReserved11) String() string {
	str, _ := text.Marshal(0xc2243c65e0340384, capnp.Struct(s))
	return str
}

func (s CustomReserved11) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved11) DecodeFromPtr(p capnp.Ptr) CustomReserved11 {
	return CustomReserved11(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved11) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved11) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved11) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved11) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved11_List is a list of CustomReserved11.
type CustomReserved11_List = capnp.StructList[CustomReserved11]

// NewCustomReserved11 creates a new list of CustomReserved11.
func NewCustomReserved11_List(s *capnp.Segment, sz int32) (CustomReserved11_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved11](l), err
}

// CustomReserved11_Future is a wrapper for a CustomReserved11 promised by a client call.
type CustomReserved11_Future struct{ *capnp.Future }

func (f CustomReserved11_Future) Struct() (CustomReserved11, error) {
	p, err := f.Future.Ptr()
	return CustomReserved11(p.Struct()), err
}

type CustomReserved12 capnp.Struct

// CustomReserved12_TypeID is the unique identifier for the type CustomReserved12.
const CustomReserved12_TypeID = 0x9ccdc8676701b412

func NewCustomReserved12(s *capnp.Segment) (CustomReserved12, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved12(st), err
}

func NewRootCustomReserved12(s *capnp.Segment) (CustomReserved12, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved12(st), err
}

func ReadRootCustomReserved12(msg *capnp.Message) (CustomReserved12, error) {
	root, err := msg.Root()
	return CustomReserved12(root.Struct()), err
}

func (s CustomReserved12) String() string {
	str, _ := text.Marshal(0x9ccdc8676701b412, capnp.Struct(s))
	return str
}

func (s CustomReserved12) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved12) DecodeFromPtr(p capnp.Ptr) CustomReserved12 {
	return CustomReserved12(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved12) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved12) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved12) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved12) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved12_List is a list of CustomReserved12.
type CustomReserved12_List = capnp.StructList[CustomReserved12]

// NewCustomReserved12 creates a new list of CustomReserved12.
func NewCustomReserved12_List(s *capnp.Segment, sz int32) (CustomReserved12_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved12](l), err
}

// CustomReserved12_Future is a wrapper for a CustomReserved12 promised by a client call.
type CustomReserved12_Future struct{ *capnp.Future }

func (f CustomReserved12_Future) Struct() (CustomReserved12, error) {
	p, err := f.Future.Ptr()
	return CustomReserved12(p.Struct()), err
}

type CustomReserved13 capnp.Struct

// CustomReserved13_TypeID is the unique identifier for the type CustomReserved13.
const CustomReserved13_TypeID = 0xcd96dafb67a082d0

func NewCustomReserved13(s *capnp.Segment) (CustomReserved13, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved13(st), err
}

func NewRootCustomReserved13(s *capnp.Segment) (CustomReserved13, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved13(st), err
}

func ReadRootCustomReserved13(msg *capnp.Message) (CustomReserved13, error) {
	root, err := msg.Root()
	return CustomReserved13(root.Struct()), err
}

func (s CustomReserved13) String() string {
	str, _ := text.Marshal(0xcd96dafb67a082d0, capnp.Struct(s))
	return str
}

func (s CustomReserved13) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved13) DecodeFromPtr(p capnp.Ptr) CustomReserved13 {
	return CustomReserved13(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved13) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved13) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved13) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved13) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved13_List is a list of CustomReserved13.
type CustomReserved13_List = capnp.StructList[CustomReserved13]

// NewCustomReserved13 creates a new list of CustomReserved13.
func NewCustomReserved13_List(s *capnp.Segment, sz int32) (CustomReserved13_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved13](l), err
}

// CustomReserved13_Future is a wrapper for a CustomReserved13 promised by a client call.
type CustomReserved13_Future struct{ *capnp.Future }

func (f CustomReserved13_Future) Struct() (CustomReserved13, error) {
	p, err := f.Future.Ptr()
	return CustomReserved13(p.Struct()), err
}

type CustomReserved14 capnp.Struct

// CustomReserved14_TypeID is the unique identifier for the type CustomReserved14.
const CustomReserved14_TypeID = 0xb057204d7deadf3f

func NewCustomReserved14(s *capnp.Segment) (CustomReserved14, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved14(st), err
}

func NewRootCustomReserved14(s *capnp.Segment) (CustomReserved14, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved14(st), err
}

func ReadRootCustomReserved14(msg *capnp.Message) (CustomReserved14, error) {
	root, err := msg.Root()
	return CustomReserved14(root.Struct()), err
}

func (s CustomReserved14) String() string {
	str, _ := text.Marshal(0xb057204d7deadf3f, capnp.Struct(s))
	return str
}

func (s CustomReserved14) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved14) DecodeFromPtr(p capnp.Ptr) CustomReserved14 {
	return CustomReserved14(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved14) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved14) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved14) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved14) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved14_List is a list of CustomReserved14.
type CustomReserved14_List = capnp.StructList[CustomReserved14]

// NewCustomReserved14 creates a new list of CustomReserved14.
func NewCustomReserved14_List(s *capnp.Segment, sz int32) (CustomReserved14_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved14](l), err
}

// CustomReserved14_Future is a wrapper for a CustomReserved14 promised by a client call.
type CustomReserved14_Future struct{ *capnp.Future }

func (f CustomReserved14_Future) Struct() (CustomReserved14, error) {
	p, err := f.Future.Ptr()
	return CustomReserved14(p.Struct()), err
}

type CustomReserved15 capnp.Struct

// CustomReserved15_TypeID is the unique identifier for the type CustomReserved15.
const CustomReserved15_TypeID = 0xbd443b539493bc68

func NewCustomReserved15(s *capnp.Segment) (CustomReserved15, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved15(st), err
}

func NewRootCustomReserved15(s *capnp.Segment) (CustomReserved15, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved15(st), err
}

func ReadRootCustomReserved15(msg *capnp.Message) (CustomReserved15, error) {
	root, err := msg.Root()
	return CustomReserved15(root.Struct()), err
}

func (s CustomReserved15) String() string {
	str, _ := text.Marshal(0xbd443b539493bc68, capnp.Struct(s))
	return str
}

func (s CustomReserved15) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved15) DecodeFromPtr(p capnp.Ptr) CustomReserved15 {
	return CustomReserved15(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved15) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved15) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved15) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved15) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved15_List is a list of CustomReserved15.
type CustomReserved15_List = capnp.StructList[CustomReserved15]

// NewCustomReserved15 creates a new list of CustomReserved15.
func NewCustomReserved15_List(s *capnp.Segment, sz int32) (CustomReserved15_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved15](l), err
}

// CustomReserved15_Future is a wrapper for a CustomReserved15 promised by a client call.
type CustomReserved15_Future struct{ *capnp.Future }

func (f CustomReserved15_Future) Struct() (CustomReserved15, error) {
	p, err := f.Future.Ptr()
	return CustomReserved15(p.Struct()), err
}

type CustomReserved16 capnp.Struct

// CustomReserved16_TypeID is the unique identifier for the type CustomReserved16.
const CustomReserved16_TypeID = 0xfc6241ed8877b611

func NewCustomReserved16(s *capnp.Segment) (CustomReserved16, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved16(st), err
}

func NewRootCustomReserved16(s *capnp.Segment) (CustomReserved16, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved16(st), err
}

func ReadRootCustomReserved16(msg *capnp.Message) (CustomReserved16, error) {
	root, err := msg.Root()
	return CustomReserved16(root.Struct()), err
}

func (s CustomReserved16) String() string {
	str, _ := text.Marshal(0xfc6241ed8877b611, capnp.Struct(s))
	return str
}

func (s CustomReserved16) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved16) DecodeFromPtr(p capnp.Ptr) CustomReserved16 {
	return CustomReserved16(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved16) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved16) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved16) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved16) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved16_List is a list of CustomReserved16.
type CustomReserved16_List = capnp.StructList[CustomReserved16]

// NewCustomReserved16 creates a new list of CustomReserved16.
func NewCustomReserved16_List(s *capnp.Segment, sz int32) (CustomReserved16_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved16](l), err
}

// CustomReserved16_Future is a wrapper for a CustomReserved16 promised by a client call.
type CustomReserved16_Future struct{ *capnp.Future }

func (f CustomReserved16_Future) Struct() (CustomReserved16, error) {
	p, err := f.Future.Ptr()
	return CustomReserved16(p.Struct()), err
}

type MapdExtendedOutType uint16

// MapdExtendedOutType_TypeID is the unique identifier for the type MapdExtendedOutType.
const MapdExtendedOutType_TypeID = 0xcbdaf55a12931b65

// Values of MapdExtendedOutType.
const (
	MapdExtendedOutType_paths    MapdExtendedOutType = 0
	MapdExtendedOutType_settings MapdExtendedOutType = 1
)

// String returns the enum's constant name.
func (c MapdExtendedOutType) String() string {
	switch c {
	case MapdExtendedOutType_paths:
		return "paths"
	case MapdExtendedOutType_settings:
		return "settings"

	default:
		return ""
	}
}

// MapdExtendedOutTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func MapdExtendedOutTypeFromString(c string) MapdExtendedOutType {
	switch c {
	case "paths":
		return MapdExtendedOutType_paths
	case "settings":
		return MapdExtendedOutType_settings

	default:
		return 0
	}
}

type MapdExtendedOutType_List = capnp.EnumList[MapdExtendedOutType]

func NewMapdExtendedOutType_List(s *capnp.Segment, sz int32) (MapdExtendedOutType_List, error) {
	return capnp.NewEnumList[MapdExtendedOutType](s, sz)
}

type MapdExtendedOut capnp.Struct

// MapdExtendedOut_TypeID is the unique identifier for the type MapdExtendedOut.
const MapdExtendedOut_TypeID = 0xa30662f84033036c

func NewMapdExtendedOut(s *capnp.Segment) (MapdExtendedOut, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdExtendedOut(st), err
}

func NewRootMapdExtendedOut(s *capnp.Segment) (MapdExtendedOut, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdExtendedOut(st), err
}

func ReadRootMapdExtendedOut(msg *capnp.Message) (MapdExtendedOut, error) {
	root, err := msg.Root()
	return MapdExtendedOut(root.Struct()), err
}

func (s MapdExtendedOut) String() string {
	str, _ := text.Marshal(0xa30662f84033036c, capnp.Struct(s))
	return str
}

func (s MapdExtendedOut) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdExtendedOut) DecodeFromPtr(p capnp.Ptr) MapdExtendedOut {
	return MapdExtendedOut(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdExtendedOut) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdExtendedOut) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdExtendedOut) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdExtendedOut) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdExtendedOut) Type() MapdExtendedOutType {
	return MapdExtendedOutType(capnp.Struct(s).Uint16(0))
}

func (s MapdExtendedOut) SetType(v MapdExtendedOutType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s MapdExtendedOut) Json() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MapdExtendedOut) HasJson() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdExtendedOut) JsonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MapdExtendedOut) SetJson(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// MapdExtendedOut_List is a list of MapdExtendedOut.
type MapdExtendedOut_List = capnp.StructList[MapdExtendedOut]

// NewMapdExtendedOut creates a new list of MapdExtendedOut.
func NewMapdExtendedOut_List(s *capnp.Segment, sz int32) (MapdExtendedOut_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[MapdExtendedOut](l), err
}

// MapdExtendedOut_Future is a wrapper for a MapdExtendedOut promised by a client call.
type MapdExtendedOut_Future struct{ *capnp.Future }

func (f MapdExtendedOut_Future) Struct() (MapdExtendedOut, error) {
	p, err := f.Future.Ptr()
	return MapdExtendedOut(p.Struct()), err
}

type MapdInputType uint16

// MapdInputType_TypeID is the unique identifier for the type MapdInputType.
const MapdInputType_TypeID = 0x859f26628fc24358

// Values of MapdInputType.
const (
	MapdInputType_download                    MapdInputType = 0
	MapdInputType_setTargetLateralAccel       MapdInputType = 1
	MapdInputType_setSpeedLimitOffset         MapdInputType = 2
	MapdInputType_setSpeedLimitControl        MapdInputType = 3
	MapdInputType_setCurveSpeedControl        MapdInputType = 4
	MapdInputType_setVisionCurveSpeedControl  MapdInputType = 5
	MapdInputType_setLogLevel                 MapdInputType = 6
	MapdInputType_setVtscTargetLatA           MapdInputType = 7
	MapdInputType_setVtscMinTargetV           MapdInputType = 8
	MapdInputType_reloadSettings              MapdInputType = 9
	MapdInputType_saveSettings                MapdInputType = 10
	MapdInputType_setEnableSpeed              MapdInputType = 11
	MapdInputType_setVtscUseEnableSpeed       MapdInputType = 12
	MapdInputType_setCurveUseEnableSpeed      MapdInputType = 13
	MapdInputType_setSpeedLimitUseEnableSpeed MapdInputType = 14
	MapdInputType_setHoldLastSeenSpeedLimit   MapdInputType = 15
	MapdInputType_setCurveTargetJerk          MapdInputType = 16
	MapdInputType_setCurveTargetAccel         MapdInputType = 17
	MapdInputType_setCurveTargetOffset        MapdInputType = 18
	MapdInputType_setDefaultLaneWidth         MapdInputType = 19
	MapdInputType_setCurveTargetLatA          MapdInputType = 20
	MapdInputType_loadDefaultSettings         MapdInputType = 21
	MapdInputType_loadRecommendedSettings     MapdInputType = 22
)

// String returns the enum's constant name.
func (c MapdInputType) String() string {
	switch c {
	case MapdInputType_download:
		return "download"
	case MapdInputType_setTargetLateralAccel:
		return "setTargetLateralAccel"
	case MapdInputType_setSpeedLimitOffset:
		return "setSpeedLimitOffset"
	case MapdInputType_setSpeedLimitControl:
		return "setSpeedLimitControl"
	case MapdInputType_setCurveSpeedControl:
		return "setCurveSpeedControl"
	case MapdInputType_setVisionCurveSpeedControl:
		return "setVisionCurveSpeedControl"
	case MapdInputType_setLogLevel:
		return "setLogLevel"
	case MapdInputType_setVtscTargetLatA:
		return "setVtscTargetLatA"
	case MapdInputType_setVtscMinTargetV:
		return "setVtscMinTargetV"
	case MapdInputType_reloadSettings:
		return "reloadSettings"
	case MapdInputType_saveSettings:
		return "saveSettings"
	case MapdInputType_setEnableSpeed:
		return "setEnableSpeed"
	case MapdInputType_setVtscUseEnableSpeed:
		return "setVtscUseEnableSpeed"
	case MapdInputType_setCurveUseEnableSpeed:
		return "setCurveUseEnableSpeed"
	case MapdInputType_setSpeedLimitUseEnableSpeed:
		return "setSpeedLimitUseEnableSpeed"
	case MapdInputType_setHoldLastSeenSpeedLimit:
		return "setHoldLastSeenSpeedLimit"
	case MapdInputType_setCurveTargetJerk:
		return "setCurveTargetJerk"
	case MapdInputType_setCurveTargetAccel:
		return "setCurveTargetAccel"
	case MapdInputType_setCurveTargetOffset:
		return "setCurveTargetOffset"
	case MapdInputType_setDefaultLaneWidth:
		return "setDefaultLaneWidth"
	case MapdInputType_setCurveTargetLatA:
		return "setCurveTargetLatA"
	case MapdInputType_loadDefaultSettings:
		return "loadDefaultSettings"
	case MapdInputType_loadRecommendedSettings:
		return "loadRecommendedSettings"

	default:
		return ""
	}
}

// MapdInputTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func MapdInputTypeFromString(c string) MapdInputType {
	switch c {
	case "download":
		return MapdInputType_download
	case "setTargetLateralAccel":
		return MapdInputType_setTargetLateralAccel
	case "setSpeedLimitOffset":
		return MapdInputType_setSpeedLimitOffset
	case "setSpeedLimitControl":
		return MapdInputType_setSpeedLimitControl
	case "setCurveSpeedControl":
		return MapdInputType_setCurveSpeedControl
	case "setVisionCurveSpeedControl":
		return MapdInputType_setVisionCurveSpeedControl
	case "setLogLevel":
		return MapdInputType_setLogLevel
	case "setVtscTargetLatA":
		return MapdInputType_setVtscTargetLatA
	case "setVtscMinTargetV":
		return MapdInputType_setVtscMinTargetV
	case "reloadSettings":
		return MapdInputType_reloadSettings
	case "saveSettings":
		return MapdInputType_saveSettings
	case "setEnableSpeed":
		return MapdInputType_setEnableSpeed
	case "setVtscUseEnableSpeed":
		return MapdInputType_setVtscUseEnableSpeed
	case "setCurveUseEnableSpeed":
		return MapdInputType_setCurveUseEnableSpeed
	case "setSpeedLimitUseEnableSpeed":
		return MapdInputType_setSpeedLimitUseEnableSpeed
	case "setHoldLastSeenSpeedLimit":
		return MapdInputType_setHoldLastSeenSpeedLimit
	case "setCurveTargetJerk":
		return MapdInputType_setCurveTargetJerk
	case "setCurveTargetAccel":
		return MapdInputType_setCurveTargetAccel
	case "setCurveTargetOffset":
		return MapdInputType_setCurveTargetOffset
	case "setDefaultLaneWidth":
		return MapdInputType_setDefaultLaneWidth
	case "setCurveTargetLatA":
		return MapdInputType_setCurveTargetLatA
	case "loadDefaultSettings":
		return MapdInputType_loadDefaultSettings
	case "loadRecommendedSettings":
		return MapdInputType_loadRecommendedSettings

	default:
		return 0
	}
}

type MapdInputType_List = capnp.EnumList[MapdInputType]

func NewMapdInputType_List(s *capnp.Segment, sz int32) (MapdInputType_List, error) {
	return capnp.NewEnumList[MapdInputType](s, sz)
}

type SpeedLimitOffsetType uint16

// SpeedLimitOffsetType_TypeID is the unique identifier for the type SpeedLimitOffsetType.
const SpeedLimitOffsetType_TypeID = 0xa5a3dfadcac04344

// Values of SpeedLimitOffsetType.
const (
	SpeedLimitOffsetType_static  SpeedLimitOffsetType = 0
	SpeedLimitOffsetType_percent SpeedLimitOffsetType = 1
)

// String returns the enum's constant name.
func (c SpeedLimitOffsetType) String() string {
	switch c {
	case SpeedLimitOffsetType_static:
		return "static"
	case SpeedLimitOffsetType_percent:
		return "percent"

	default:
		return ""
	}
}

// SpeedLimitOffsetTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func SpeedLimitOffsetTypeFromString(c string) SpeedLimitOffsetType {
	switch c {
	case "static":
		return SpeedLimitOffsetType_static
	case "percent":
		return SpeedLimitOffsetType_percent

	default:
		return 0
	}
}

type SpeedLimitOffsetType_List = capnp.EnumList[SpeedLimitOffsetType]

func NewSpeedLimitOffsetType_List(s *capnp.Segment, sz int32) (SpeedLimitOffsetType_List, error) {
	return capnp.NewEnumList[SpeedLimitOffsetType](s, sz)
}

type MapdIn capnp.Struct

// MapdIn_TypeID is the unique identifier for the type MapdIn.
const MapdIn_TypeID = 0xc86a3d38d13eb3ef

func NewMapdIn(s *capnp.Segment) (MapdIn, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdIn(st), err
}

func NewRootMapdIn(s *capnp.Segment) (MapdIn, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdIn(st), err
}

func ReadRootMapdIn(msg *capnp.Message) (MapdIn, error) {
	root, err := msg.Root()
	return MapdIn(root.Struct()), err
}

func (s MapdIn) String() string {
	str, _ := text.Marshal(0xc86a3d38d13eb3ef, capnp.Struct(s))
	return str
}

func (s MapdIn) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdIn) DecodeFromPtr(p capnp.Ptr) MapdIn {
	return MapdIn(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdIn) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdIn) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdIn) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdIn) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdIn) Type() MapdInputType {
	return MapdInputType(capnp.Struct(s).Uint16(0))
}

func (s MapdIn) SetType(v MapdInputType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s MapdIn) Float() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s MapdIn) SetFloat(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s MapdIn) Str() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MapdIn) HasStr() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdIn) StrBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MapdIn) SetStr(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s MapdIn) Bool() bool {
	return capnp.Struct(s).Bit(16)
}

func (s MapdIn) SetBool(v bool) {
	capnp.Struct(s).SetBit(16, v)
}

// MapdIn_List is a list of MapdIn.
type MapdIn_List = capnp.StructList[MapdIn]

// NewMapdIn creates a new list of MapdIn.
func NewMapdIn_List(s *capnp.Segment, sz int32) (MapdIn_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[MapdIn](l), err
}

// MapdIn_Future is a wrapper for a MapdIn promised by a client call.
type MapdIn_Future struct{ *capnp.Future }

func (f MapdIn_Future) Struct() (MapdIn, error) {
	p, err := f.Future.Ptr()
	return MapdIn(p.Struct()), err
}

type RoadContext uint16

// RoadContext_TypeID is the unique identifier for the type RoadContext.
const RoadContext_TypeID = 0xabefa88b9563dbae

// Values of RoadContext.
const (
	RoadContext_freeway RoadContext = 0
	RoadContext_city    RoadContext = 1
	RoadContext_unknown RoadContext = 2
)

// String returns the enum's constant name.
func (c RoadContext) String() string {
	switch c {
	case RoadContext_freeway:
		return "freeway"
	case RoadContext_city:
		return "city"
	case RoadContext_unknown:
		return "unknown"

	default:
		return ""
	}
}

// RoadContextFromString returns the enum value with a name,
// or the zero value if there's no such value.
func RoadContextFromString(c string) RoadContext {
	switch c {
	case "freeway":
		return RoadContext_freeway
	case "city":
		return RoadContext_city
	case "unknown":
		return RoadContext_unknown

	default:
		return 0
	}
}

type RoadContext_List = capnp.EnumList[RoadContext]

func NewRoadContext_List(s *capnp.Segment, sz int32) (RoadContext_List, error) {
	return capnp.NewEnumList[RoadContext](s, sz)
}

type MapdOut capnp.Struct

// MapdOut_TypeID is the unique identifier for the type MapdOut.
const MapdOut_TypeID = 0xa4f1eb3323f5f582

func NewMapdOut(s *capnp.Segment) (MapdOut, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 5})
	return MapdOut(st), err
}

func NewRootMapdOut(s *capnp.Segment) (MapdOut, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 5})
	return MapdOut(st), err
}

func ReadRootMapdOut(msg *capnp.Message) (MapdOut, error) {
	root, err := msg.Root()
	return MapdOut(root.Struct()), err
}

func (s MapdOut) String() string {
	str, _ := text.Marshal(0xa4f1eb3323f5f582, capnp.Struct(s))
	return str
}

func (s MapdOut) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdOut) DecodeFromPtr(p capnp.Ptr) MapdOut {
	return MapdOut(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdOut) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdOut) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdOut) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdOut) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdOut) WayName() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MapdOut) HasWayName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdOut) WayNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MapdOut) SetWayName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s MapdOut) WayRef() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s MapdOut) HasWayRef() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s MapdOut) WayRefBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s MapdOut) SetWayRef(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s MapdOut) RoadName() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s MapdOut) HasRoadName() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s MapdOut) RoadNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s MapdOut) SetRoadName(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s MapdOut) SpeedLimit() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(0))
}

func (s MapdOut) SetSpeedLimit(v float32) {
	capnp.Struct(s).SetUint32(0, math.Float32bits(v))
}

func (s MapdOut) NextSpeedLimit() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s MapdOut) SetNextSpeedLimit(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s MapdOut) NextSpeedLimitDistance() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(8))
}

func (s MapdOut) SetNextSpeedLimitDistance(v float32) {
	capnp.Struct(s).SetUint32(8, math.Float32bits(v))
}

func (s MapdOut) Hazard() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s MapdOut) HasHazard() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s MapdOut) HazardBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s MapdOut) SetHazard(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s MapdOut) NextHazard() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s MapdOut) HasNextHazard() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s MapdOut) NextHazardBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s MapdOut) SetNextHazard(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s MapdOut) NextHazardDistance() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(12))
}

func (s MapdOut) SetNextHazardDistance(v float32) {
	capnp.Struct(s).SetUint32(12, math.Float32bits(v))
}

func (s MapdOut) AdvisorySpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(16))
}

func (s MapdOut) SetAdvisorySpeed(v float32) {
	capnp.Struct(s).SetUint32(16, math.Float32bits(v))
}

func (s MapdOut) NextAdvisorySpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(20))
}

func (s MapdOut) SetNextAdvisorySpeed(v float32) {
	capnp.Struct(s).SetUint32(20, math.Float32bits(v))
}

func (s MapdOut) NextAdvisorySpeedDistance() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(24))
}

func (s MapdOut) SetNextAdvisorySpeedDistance(v float32) {
	capnp.Struct(s).SetUint32(24, math.Float32bits(v))
}

func (s MapdOut) OneWay() bool {
	return capnp.Struct(s).Bit(224)
}

func (s MapdOut) SetOneWay(v bool) {
	capnp.Struct(s).SetBit(224, v)
}

func (s MapdOut) Lanes() uint8 {
	return capnp.Struct(s).Uint8(29)
}

func (s MapdOut) SetLanes(v uint8) {
	capnp.Struct(s).SetUint8(29, v)
}

func (s MapdOut) TileLoaded() bool {
	return capnp.Struct(s).Bit(225)
}

func (s MapdOut) SetTileLoaded(v bool) {
	capnp.Struct(s).SetBit(225, v)
}

func (s MapdOut) SpeedLimitOffset() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(32))
}

func (s MapdOut) SetSpeedLimitOffset(v float32) {
	capnp.Struct(s).SetUint32(32, math.Float32bits(v))
}

func (s MapdOut) SuggestedSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(36))
}

func (s MapdOut) SetSuggestedSpeed(v float32) {
	capnp.Struct(s).SetUint32(36, math.Float32bits(v))
}

func (s MapdOut) EstimatedRoadWidth() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(40))
}

func (s MapdOut) SetEstimatedRoadWidth(v float32) {
	capnp.Struct(s).SetUint32(40, math.Float32bits(v))
}

func (s MapdOut) RoadContext() RoadContext {
	return RoadContext(capnp.Struct(s).Uint16(30))
}

func (s MapdOut) SetRoadContext(v RoadContext) {
	capnp.Struct(s).SetUint16(30, uint16(v))
}

func (s MapdOut) DistanceFromWayCenter() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(44))
}

func (s MapdOut) SetDistanceFromWayCenter(v float32) {
	capnp.Struct(s).SetUint32(44, math.Float32bits(v))
}

func (s MapdOut) VtscSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(48))
}

func (s MapdOut) SetVtscSpeed(v float32) {
	capnp.Struct(s).SetUint32(48, math.Float32bits(v))
}

func (s MapdOut) CurveSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(52))
}

func (s MapdOut) SetCurveSpeed(v float32) {
	capnp.Struct(s).SetUint32(52, math.Float32bits(v))
}

// MapdOut_List is a list of MapdOut.
type MapdOut_List = capnp.StructList[MapdOut]

// NewMapdOut creates a new list of MapdOut.
func NewMapdOut_List(s *capnp.Segment, sz int32) (MapdOut_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 56, PointerCount: 5}, sz)
	return capnp.StructList[MapdOut](l), err
}

// MapdOut_Future is a wrapper for a MapdOut promised by a client call.
type MapdOut_Future struct{ *capnp.Future }

func (f MapdOut_Future) Struct() (MapdOut, error) {
	p, err := f.Future.Ptr()
	return MapdOut(p.Struct()), err
}

const schema_b526ba661d550a59 = "x\xda\x94\x97\x7fl\x1c\xd5\x11\xc7g\xde\xde\xdd\xfa\x9c" +
	"\xbb\x9c\xd7o\x83J\xa3\xc8\xa5\xa5\xa8AM\x13\xe7G" +
	"\x01Sj\x1c;Ub]\x1a\xce\x1b\xc7\xb1\x15\xa4\xec" +
	"\xdd>\xdb\x9b\x9cw\xaf\xb7\xcfv\xce\x02\x85\xa6 %" +
	"m#THQAX@C\xd4\xb4U\xd2B\xa1\xa2" +
	"\x11\xa8`Q\xc9-\x8dT\x10U\xd5\xd0*\x01\xa9\x02" +
	"\xf5\x87 j\"5j\xac\xab\xe6\xdd/\x13o\x15\xee" +
	"\xaf\xf3~\xe6\xbb3\xf3f\xdf\x9by^\xb75rw" +
	"\xa43\xf9\xa38\xb0L!\x1a+\x1b\xfb\x87\xdf\xf3\xe4" +
	"\xe9\x07\xc0X\x89\xe5\xe1\xd6\xc1U\xa3gny\x11\"" +
	":\xc0\x86_EF\x90\x9f\x8d\xe8\xa0\x95\x7fv)}" +
	"\xc7\xc8Gs\xdf\x0cQ\xfd\x98T\xaf(\xd5\xee\xde\xb9" +
	"\x87\xb3\xb7<\xf5\x10\x18+YC\x05\xb8\xe1\xf1H?" +
	"\xf2SU\xf9Z\x06Xn\x7f\x01\xc7\xc6\xe6\xcf>\x19" +
	"\xe2\xf0T,\x8b\xfc\xb5\x189\\\xf3N\x87\xd6\xa7\x8f" +
	"?\x13\xa2\x9a\x8d\x8d \x7fN\xa9\xf2\xda\x86\xbb\xff\x93" +
	"\x8d\x1d\x87\xccJ\\$\x8b\"\xe9\x8e\x92\xee\x99\x98\x0e" +
	"\xc0gc\xd3\x80\xe5C\x97/\x7fn\xc3?.>K" +
	"j}\x91:J\xea+\xb1O#\x8f\xeb\xf4gT\xff" +
	"S\x04\xb0\xdc\xd7\xfb\xea\xefN\x9d?~b\xc9\x9a&" +
	"\x13\x87\x90\x1fI\x90\xe3\x87\x12\xb7\x01\x96\x07\x9f\xcd\xfc" +
	"\xf9\x8bSgO\x84${$1\x82|6A\xc9\x9e" +
	"~'\xf7\xfd\xef\x9c\xfc\xf0\xa7K\xfc\x95\x12]\x0d\x7f" +
	";\x00\xcb\xf7\xbe\xf8~\xe7\xc3\x0b\xe7O\x87\xf8{\x9c" +
	"\xfc\x9dR\xfe\xba\xcf\xff\xfd\xfe\xed\x9f\x19\xfayh\xd4" +
	"l-\xea<\xa6ors\xdeK!\xaa\x12\xf9:\xaa" +
	"T\xe3/?z\xcc\xba\xb3\xef\x95\x10\x95K\xbe\xeeW" +
	"\xaa\x07\xb5\x8d\x17\xc4Wn\x9e\x0bQ\x0d\x93jB\xa9" +
	">\xfc\xc5W\xdf\xbc\xfd\xae}\xf3\xa1\x1fe[\xa2\x1d" +
	"\xf9\xb0Z\xeb`\xe2}\xc0r\xd7\xf0P!\xff\xc7\xa7" +
	"\xde\x08\xf1\xb9:\x99E~W\x92|\x8a\x95\x8f\xb6\x8f" +
	"\\>\xf7\xc6\x92\xda\xdd\x98\x9cA\xbe&I\xfeV'" +
	"\xe9[\xfc\xe1\xd0\xd3c\xff=\xf7\xd8\xd9\x10\x7f\x9d\xe4" +
	"o\x8b\xf2\xb7)\xdd\xf7\xad\x1f\x0c=v.DuS" +
	"r\x04\xf9&\xa5\x9a\xf3~\xbdl\xd7\xeb{\xfe\x1d\xa2" +
	"2H\xf5y\xa5\xbaqvv[\xfc\x9f7\\\x0aQ" +
	"!\xa9V(\xd5\xf1Ha\xe1\xce\x07\x8f^\x09Q]" +
	"\xa4\xef\x10U*\xe3\x97\xd3\x87\xff\xd5\x93\xbd\x1a\xa2z" +
	"\x97*|9\xa1\xc3\xdarN\x14\x85\x9d_\x9b\x8bL" +
	"\x06\xd2\x9fX\x9bS?_\xca\xd9\x05\xaf\xd0\xd5\xab\x1e" +
	"\x06D \x8aSBs6\xde\x83\xd8\x8c~\xdd\xf5\xf4" +
	"\xdb\xed\x82\xb3\xcd+L\xca\x9d\xa5\x82\x00\xb8\x071\xb3" +
	"\x07\x19\x00Ob?\x00\"\x8f\xe3\xf3\x00\xc8x\x1c\x7f" +
	"\x08\x80\x1a\x8f\xe3O\x000R\xfd\x8d\xf28\x9e\x03\xc0" +
	"\x18Ob\x16\x00u\x1e\xc7G\x00\xb0\xa5\xfa\x1b\xe7q" +
	"\x9c\x01\xc0V\x1e\xc5}\x00\xb8\x8c\xa3zN\x18\x0b\xe4" +
	"6i,\x9c\x01\xc0\xe5\xc6\xc2{\x00\x98\xe2\x88o\x01" +
	"`\x1b\x8f\xe2\x13\x00h\xf0\xa8\x0a\xda\xce\xa3*\x18\xaf" +
	">\x9bU\xfb\x8a\xea\xf3\x0d<\x8as\x00e\xc7\x9f\xf6" +
	"\xf2\xbe\xed\x00@9\x10r\xa7]\x1c\x13(\xd3\xb6\x14" +
	"E;\xdf\xd1\x93\xcb\x89<q\xab \x84\x83iw\xc2" +
	"\x95;FG\xf5@\xc8kh\xaf\xef\xa5d\xd1W\xe2" +
	"\xde\xc9\xe2\x94@e\\\x8cw\xb9\x81\xeb3OYk" +
	"FY\xd4*\xc6\xb4?\x96\x16\xa0OU\xc2\xed\x92A" +
	"n'R.\x94\x0a\xf6\xd4\xd8vt=\x95\xa2\xc4]" +
	"\xe5\xa2\xa0\xc4-\x01\xddR\xba\xdeXP\x0e\xec)a" +
	"\x09)!Uy\x14r\x8bgg\xf3\xd0]\x09Ws" +
	"2\x88\x81P\x06\xd1Q\xe7\x95\x94\x07\xab\x86E/\xa8" +
	"?\x98Zb\xcd*\xac\x82^\xb5n\xf5\xf3N\x9a\xd9" +
	"\x81\xb4\x84\xf0\x94\x94\x94(\x1b.+\xd9\xf6\x0b\xad\xb8" +
	"\xffZ\xd8\x93\xd3\xab\xd5]Lw\x8c\xa6F\xab\xe5\xed" +
	"\x13\xa3\xf6$\xe6e\xda\xf6\xc4\x90\xab;r\xfcZq" +
	"\xda\xd6dO\x99\xca@Z\x9c\xccKZ\xbf\xab\xd3\xf2" +
	"\x89\x0e\x88\x9c\xafOL\x08\xcf\x11\x8e\xb2xc\x01\xd4" +
	"\xb6\xf6\xf5N\x82\xeet\xaeo\xf2\xe8\xdc\xf1I\x8e\xce" +
	"\x96\x03R%\xb4C\x9b\x94tvZ\xb4\x08@\x04\x01" +
	"\x8c\xd5\xb7\x02dn\xd60\xb3\x8e!\xa2\x89\xc4\xd6\x10" +
	"\xfb\x82\x86\x99\x8d\x0cS\xb2T\x10\x98j\xb4B@L" +
	"\x01\xa6\xf6\x05\xbe\x87\x09`\x98\x80Fx\xed\xff\x84\xaf" +
	"\x85\xdd]\x0b\xcb\x87\xd9f\x00k'\xd3\xd0\xda\xcb\x18" +
	"\x1a\xd5\xd0\xfc^\xd6\x05`\xed&\xee\x10g\xccT\xc7" +
	"\xdcf\xfd\x00\xd6^\xe2y\xc6\x105\x135\x00\xee\xb2" +
	"\x11\x00k\x9c\xb0$y\x04M\x8c\x00\xf0o\xb0\x19\x00" +
	"\xab@\xfc>\xe2Qfb\x14\x80\x97\xd8\x19\x00\xeb>" +
	"\xe2\x87\x89\xc74\x13c4\x00U\xd8\x07\x88\x7f\x97\xb8" +
	"\x1e1in\xf0#\xca\xffa\xe2\xc7\x88\xb7h&\xb6" +
	"\x00\xf0\xef\xb1'\x00\xacc\xc4\x9f&\x1e\x8f\x98\x18\xa7" +
	"\x89\xcf\x8a\x00\xd6\x93\xc4O\x12o\x8d\x9a\xd8\x0a\xc0O" +
	"\xb0G\x00\xac\x93\xc4_ \xbe,f\xe22\x00\xfe\x1c" +
	"{\x0b\xc0z\x89\xf8\xeb\xc4\x13\x17LL\x00\xf0\xd7T" +
	">/\x13\x9f'\x9e\\eb\x12\x80\xff\x86\xad\x07\xb0" +
	"^%\xfe{\xe2\xcb\xdf5q9\x00\xff\xad\xcas\x9e" +
	"\xf8\xdb\xc4S-&\xa6\x00\xf8\x9b\xec\xdb\x00\xd6\xdb\xc4" +
	"/\x10o\x8b\x9b\xd8\x06\xc0\xff\xaa\xea\xf3\x17\xe2\x1f\x10" +
	"7ZM4\x00\xf8\xdf\xd4\xba> ~\x89x{\xca" +
	"\xc4v\x00~\x91e\x01\xac\x8f\x88_%\xce\x97\x99\xc8" +
	"\x01\xf8\x15\xf6<\x80u\x95x\x8b\xc6\xd00\x13&\x9a" +
	"\x00<\xaa\x0d\x00X\x11MC\xab\x8d\xf8\x8a\xa4\x89+" +
	"\xa8[k\x94g\x82\xf8\xa74\x86\x07\xa7\xed\xd2\xd7\xed" +
	"\x09Q\xdbH\xdd\xd3vi@\x8c\xd6\xf7U\xd1\xb7\x1d" +
	"\xb2\x03\xb5\xe2*\x0b\xaaG\x1e4Wb+0l\x05" +
	",{\xe2\x80j\x1b\xd0\xad\xba\xc1R\x03Vx\x9f\xdb" +
	"\x1dH\xdb\xcb\x89\x9a\xa0{\xdc\x9e\xb1\x8bN\xdd;\xe9" +
	"\xb7\xda36h!\x10\x8bN\x9fK\xefk\x0d\x07e" +
	"\xdb\x99r\x03\xbfX\x82Jg\xfbX\xe4\x1eg\xcaE" +
	"2VRXbc5[\xd5o\x0e\x1b\x89\xf9\x9e\x18" +
	"\xb2K\x88\xc0\x10\x01;\xf2\xb6'\x02\x8c\x01\xc3\x18`" +
	"Y\xbay\x91\xa6\x11\xa2\x09\xa7&\xa9W\x06\xd5\xc0\x08" +
	"\x84\xa4\x81V\x8d\x18L\x8e\x8d\x89@R\x81>\x9e\xa6" +
	"\x08\xa4;aK\x81\xce\x80o;C\xae\xa3\xc9\xf1\xba" +
	"\x91\xeaO\x13\x03tq@b\xaaq\x97\xac4\x81\xb2" +
	"\xe3V\xab\xf9\xb5\xa2?1d\x97z;\x84'E\xb1" +
	"\xfe\xfe\x94\x0cr\xea\xb3,Z{\xae:\x8bT\xeau" +
	"Xm \xd1\x90\x06R\xef\xf1\xd5U\xa9\x1b\x80jb" +
	"\xd4\x19\x0c\xa3\x8b\xb21\xe2\x9b\x01\xe8\xdbJ7w\xb0" +
	" \x8a9\xe1\xc9f\xba\xe8\xa6\xc5]4\xac\x8dQu" +
	"z\xbb}O\x8a\x03\xaa\x95%T\xf0U\x9bU\xf0\x15" +
	"\xb7\xd2\xdd\xc3Hn\x0688Z\x14b\xda.\xa5r" +
	"\xae,\x1d\x9c\xf4\xf6{\xfe\xb4\xd7L&\x9dM\xf5\x7f" +
	"\xdd\xe9l\xf6\xaeu[\xb3\x0165\xfbB\xe7\xf5\x8a" +
	"\xa9ns\xe8Q\x1d\xdb\xea\x93\xc8\xa6\xa9\xb3G\xc3\xcc" +
	"xc\x1e\x18b=@f\xaf\x86\x99<C\xac\xcc\x02" +
	"\xc3\xfd,@\xc6\xd10S`hhmj\x12\x18\x13" +
	"\xf4\xf6\xb8\x86\x19\xd9\x98Y\xf5\x7f\x0f+\xdb\xb5c4" +
	"\xef\xdb\xf5\xd6\xa0\x07\xb2X;\xe1\xa9\xac\xef\xe7\xeb\xe7" +
	"\xa8\x99\xa5\xaekj\xfavW\xee\xaf\x8b6\xef\xfa\xca" +
	"\xe6\xed\x07\xe8(\xd8r\\\xdd\xa0*W\x06\x80\xa6\x12" +
	"\xd9\xd0\xe4.hV\xdf\xec\xb5\xe4\xf6&\xf5_nv" +
	"\x93\xd1\x0b\xff\x0b\x00\x00\xff\xff\xc3\x8b\x9d\xaf"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b526ba661d550a59,
		Nodes: []uint64{
			0x80ae746ee2596b11,
			0x81c2f05a394cf4af,
			0x859f26628fc24358,
			0x9ccdc8676701b412,
			0xa1680744031fdb2d,
			0xa30662f84033036c,
			0xa4f1eb3323f5f582,
			0xa5a3dfadcac04344,
			0xa5cd762cd951a455,
			0xabefa88b9563dbae,
			0xaedffd8f31e7b55d,
			0xb057204d7deadf3f,
			0xb86e6369214c01c8,
			0xbd443b539493bc68,
			0xc2243c65e0340384,
			0xc86a3d38d13eb3ef,
			0xcb9fd56c7057593a,
			0xcbdaf55a12931b65,
			0xcd96dafb67a082d0,
			0xda96579883444c35,
			0xf35cc4560bbf6ec2,
			0xf416ec09499d9d19,
			0xf98d843bfd7004a3,
			0xfc6241ed8877b611,
		},
		Compressed: true,
	})
}
