// Code generated by capnpc-go. DO NOT EDIT.

package custom

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
)

type CustomReserved0 capnp.Struct

// CustomReserved0_TypeID is the unique identifier for the type CustomReserved0.
const CustomReserved0_TypeID = 0x81c2f05a394cf4af

func NewCustomReserved0(s *capnp.Segment) (CustomReserved0, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved0(st), err
}

func NewRootCustomReserved0(s *capnp.Segment) (CustomReserved0, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved0(st), err
}

func ReadRootCustomReserved0(msg *capnp.Message) (CustomReserved0, error) {
	root, err := msg.Root()
	return CustomReserved0(root.Struct()), err
}

func (s CustomReserved0) String() string {
	str, _ := text.Marshal(0x81c2f05a394cf4af, capnp.Struct(s))
	return str
}

func (s CustomReserved0) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved0) DecodeFromPtr(p capnp.Ptr) CustomReserved0 {
	return CustomReserved0(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved0) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved0) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved0) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved0) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved0_List is a list of CustomReserved0.
type CustomReserved0_List = capnp.StructList[CustomReserved0]

// NewCustomReserved0 creates a new list of CustomReserved0.
func NewCustomReserved0_List(s *capnp.Segment, sz int32) (CustomReserved0_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved0](l), err
}

// CustomReserved0_Future is a wrapper for a CustomReserved0 promised by a client call.
type CustomReserved0_Future struct{ *capnp.Future }

func (f CustomReserved0_Future) Struct() (CustomReserved0, error) {
	p, err := f.Future.Ptr()
	return CustomReserved0(p.Struct()), err
}

type CustomReserved1 capnp.Struct

// CustomReserved1_TypeID is the unique identifier for the type CustomReserved1.
const CustomReserved1_TypeID = 0xaedffd8f31e7b55d

func NewCustomReserved1(s *capnp.Segment) (CustomReserved1, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved1(st), err
}

func NewRootCustomReserved1(s *capnp.Segment) (CustomReserved1, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved1(st), err
}

func ReadRootCustomReserved1(msg *capnp.Message) (CustomReserved1, error) {
	root, err := msg.Root()
	return CustomReserved1(root.Struct()), err
}

func (s CustomReserved1) String() string {
	str, _ := text.Marshal(0xaedffd8f31e7b55d, capnp.Struct(s))
	return str
}

func (s CustomReserved1) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved1) DecodeFromPtr(p capnp.Ptr) CustomReserved1 {
	return CustomReserved1(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved1) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved1) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved1) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved1) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved1_List is a list of CustomReserved1.
type CustomReserved1_List = capnp.StructList[CustomReserved1]

// NewCustomReserved1 creates a new list of CustomReserved1.
func NewCustomReserved1_List(s *capnp.Segment, sz int32) (CustomReserved1_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved1](l), err
}

// CustomReserved1_Future is a wrapper for a CustomReserved1 promised by a client call.
type CustomReserved1_Future struct{ *capnp.Future }

func (f CustomReserved1_Future) Struct() (CustomReserved1, error) {
	p, err := f.Future.Ptr()
	return CustomReserved1(p.Struct()), err
}

type CustomReserved2 capnp.Struct

// CustomReserved2_TypeID is the unique identifier for the type CustomReserved2.
const CustomReserved2_TypeID = 0xf35cc4560bbf6ec2

func NewCustomReserved2(s *capnp.Segment) (CustomReserved2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved2(st), err
}

func NewRootCustomReserved2(s *capnp.Segment) (CustomReserved2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved2(st), err
}

func ReadRootCustomReserved2(msg *capnp.Message) (CustomReserved2, error) {
	root, err := msg.Root()
	return CustomReserved2(root.Struct()), err
}

func (s CustomReserved2) String() string {
	str, _ := text.Marshal(0xf35cc4560bbf6ec2, capnp.Struct(s))
	return str
}

func (s CustomReserved2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved2) DecodeFromPtr(p capnp.Ptr) CustomReserved2 {
	return CustomReserved2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved2_List is a list of CustomReserved2.
type CustomReserved2_List = capnp.StructList[CustomReserved2]

// NewCustomReserved2 creates a new list of CustomReserved2.
func NewCustomReserved2_List(s *capnp.Segment, sz int32) (CustomReserved2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved2](l), err
}

// CustomReserved2_Future is a wrapper for a CustomReserved2 promised by a client call.
type CustomReserved2_Future struct{ *capnp.Future }

func (f CustomReserved2_Future) Struct() (CustomReserved2, error) {
	p, err := f.Future.Ptr()
	return CustomReserved2(p.Struct()), err
}

type CustomReserved3 capnp.Struct

// CustomReserved3_TypeID is the unique identifier for the type CustomReserved3.
const CustomReserved3_TypeID = 0xda96579883444c35

func NewCustomReserved3(s *capnp.Segment) (CustomReserved3, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved3(st), err
}

func NewRootCustomReserved3(s *capnp.Segment) (CustomReserved3, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved3(st), err
}

func ReadRootCustomReserved3(msg *capnp.Message) (CustomReserved3, error) {
	root, err := msg.Root()
	return CustomReserved3(root.Struct()), err
}

func (s CustomReserved3) String() string {
	str, _ := text.Marshal(0xda96579883444c35, capnp.Struct(s))
	return str
}

func (s CustomReserved3) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved3) DecodeFromPtr(p capnp.Ptr) CustomReserved3 {
	return CustomReserved3(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved3) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved3) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved3) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved3) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved3_List is a list of CustomReserved3.
type CustomReserved3_List = capnp.StructList[CustomReserved3]

// NewCustomReserved3 creates a new list of CustomReserved3.
func NewCustomReserved3_List(s *capnp.Segment, sz int32) (CustomReserved3_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved3](l), err
}

// CustomReserved3_Future is a wrapper for a CustomReserved3 promised by a client call.
type CustomReserved3_Future struct{ *capnp.Future }

func (f CustomReserved3_Future) Struct() (CustomReserved3, error) {
	p, err := f.Future.Ptr()
	return CustomReserved3(p.Struct()), err
}

type CustomReserved4 capnp.Struct

// CustomReserved4_TypeID is the unique identifier for the type CustomReserved4.
const CustomReserved4_TypeID = 0x80ae746ee2596b11

func NewCustomReserved4(s *capnp.Segment) (CustomReserved4, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved4(st), err
}

func NewRootCustomReserved4(s *capnp.Segment) (CustomReserved4, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved4(st), err
}

func ReadRootCustomReserved4(msg *capnp.Message) (CustomReserved4, error) {
	root, err := msg.Root()
	return CustomReserved4(root.Struct()), err
}

func (s CustomReserved4) String() string {
	str, _ := text.Marshal(0x80ae746ee2596b11, capnp.Struct(s))
	return str
}

func (s CustomReserved4) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved4) DecodeFromPtr(p capnp.Ptr) CustomReserved4 {
	return CustomReserved4(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved4) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved4) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved4) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved4) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved4_List is a list of CustomReserved4.
type CustomReserved4_List = capnp.StructList[CustomReserved4]

// NewCustomReserved4 creates a new list of CustomReserved4.
func NewCustomReserved4_List(s *capnp.Segment, sz int32) (CustomReserved4_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved4](l), err
}

// CustomReserved4_Future is a wrapper for a CustomReserved4 promised by a client call.
type CustomReserved4_Future struct{ *capnp.Future }

func (f CustomReserved4_Future) Struct() (CustomReserved4, error) {
	p, err := f.Future.Ptr()
	return CustomReserved4(p.Struct()), err
}

type CustomReserved5 capnp.Struct

// CustomReserved5_TypeID is the unique identifier for the type CustomReserved5.
const CustomReserved5_TypeID = 0xa5cd762cd951a455

func NewCustomReserved5(s *capnp.Segment) (CustomReserved5, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved5(st), err
}

func NewRootCustomReserved5(s *capnp.Segment) (CustomReserved5, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved5(st), err
}

func ReadRootCustomReserved5(msg *capnp.Message) (CustomReserved5, error) {
	root, err := msg.Root()
	return CustomReserved5(root.Struct()), err
}

func (s CustomReserved5) String() string {
	str, _ := text.Marshal(0xa5cd762cd951a455, capnp.Struct(s))
	return str
}

func (s CustomReserved5) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved5) DecodeFromPtr(p capnp.Ptr) CustomReserved5 {
	return CustomReserved5(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved5) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved5) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved5) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved5) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved5_List is a list of CustomReserved5.
type CustomReserved5_List = capnp.StructList[CustomReserved5]

// NewCustomReserved5 creates a new list of CustomReserved5.
func NewCustomReserved5_List(s *capnp.Segment, sz int32) (CustomReserved5_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved5](l), err
}

// CustomReserved5_Future is a wrapper for a CustomReserved5 promised by a client call.
type CustomReserved5_Future struct{ *capnp.Future }

func (f CustomReserved5_Future) Struct() (CustomReserved5, error) {
	p, err := f.Future.Ptr()
	return CustomReserved5(p.Struct()), err
}

type CustomReserved6 capnp.Struct

// CustomReserved6_TypeID is the unique identifier for the type CustomReserved6.
const CustomReserved6_TypeID = 0xf98d843bfd7004a3

func NewCustomReserved6(s *capnp.Segment) (CustomReserved6, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved6(st), err
}

func NewRootCustomReserved6(s *capnp.Segment) (CustomReserved6, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved6(st), err
}

func ReadRootCustomReserved6(msg *capnp.Message) (CustomReserved6, error) {
	root, err := msg.Root()
	return CustomReserved6(root.Struct()), err
}

func (s CustomReserved6) String() string {
	str, _ := text.Marshal(0xf98d843bfd7004a3, capnp.Struct(s))
	return str
}

func (s CustomReserved6) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved6) DecodeFromPtr(p capnp.Ptr) CustomReserved6 {
	return CustomReserved6(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved6) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved6) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved6) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved6) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved6_List is a list of CustomReserved6.
type CustomReserved6_List = capnp.StructList[CustomReserved6]

// NewCustomReserved6 creates a new list of CustomReserved6.
func NewCustomReserved6_List(s *capnp.Segment, sz int32) (CustomReserved6_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved6](l), err
}

// CustomReserved6_Future is a wrapper for a CustomReserved6 promised by a client call.
type CustomReserved6_Future struct{ *capnp.Future }

func (f CustomReserved6_Future) Struct() (CustomReserved6, error) {
	p, err := f.Future.Ptr()
	return CustomReserved6(p.Struct()), err
}

type CustomReserved7 capnp.Struct

// CustomReserved7_TypeID is the unique identifier for the type CustomReserved7.
const CustomReserved7_TypeID = 0xb86e6369214c01c8

func NewCustomReserved7(s *capnp.Segment) (CustomReserved7, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved7(st), err
}

func NewRootCustomReserved7(s *capnp.Segment) (CustomReserved7, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved7(st), err
}

func ReadRootCustomReserved7(msg *capnp.Message) (CustomReserved7, error) {
	root, err := msg.Root()
	return CustomReserved7(root.Struct()), err
}

func (s CustomReserved7) String() string {
	str, _ := text.Marshal(0xb86e6369214c01c8, capnp.Struct(s))
	return str
}

func (s CustomReserved7) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved7) DecodeFromPtr(p capnp.Ptr) CustomReserved7 {
	return CustomReserved7(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved7) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved7) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved7) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved7) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved7_List is a list of CustomReserved7.
type CustomReserved7_List = capnp.StructList[CustomReserved7]

// NewCustomReserved7 creates a new list of CustomReserved7.
func NewCustomReserved7_List(s *capnp.Segment, sz int32) (CustomReserved7_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved7](l), err
}

// CustomReserved7_Future is a wrapper for a CustomReserved7 promised by a client call.
type CustomReserved7_Future struct{ *capnp.Future }

func (f CustomReserved7_Future) Struct() (CustomReserved7, error) {
	p, err := f.Future.Ptr()
	return CustomReserved7(p.Struct()), err
}

type CustomReserved8 capnp.Struct

// CustomReserved8_TypeID is the unique identifier for the type CustomReserved8.
const CustomReserved8_TypeID = 0xf416ec09499d9d19

func NewCustomReserved8(s *capnp.Segment) (CustomReserved8, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved8(st), err
}

func NewRootCustomReserved8(s *capnp.Segment) (CustomReserved8, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved8(st), err
}

func ReadRootCustomReserved8(msg *capnp.Message) (CustomReserved8, error) {
	root, err := msg.Root()
	return CustomReserved8(root.Struct()), err
}

func (s CustomReserved8) String() string {
	str, _ := text.Marshal(0xf416ec09499d9d19, capnp.Struct(s))
	return str
}

func (s CustomReserved8) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved8) DecodeFromPtr(p capnp.Ptr) CustomReserved8 {
	return CustomReserved8(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved8) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved8) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved8) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved8) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved8_List is a list of CustomReserved8.
type CustomReserved8_List = capnp.StructList[CustomReserved8]

// NewCustomReserved8 creates a new list of CustomReserved8.
func NewCustomReserved8_List(s *capnp.Segment, sz int32) (CustomReserved8_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved8](l), err
}

// CustomReserved8_Future is a wrapper for a CustomReserved8 promised by a client call.
type CustomReserved8_Future struct{ *capnp.Future }

func (f CustomReserved8_Future) Struct() (CustomReserved8, error) {
	p, err := f.Future.Ptr()
	return CustomReserved8(p.Struct()), err
}

type CustomReserved9 capnp.Struct

// CustomReserved9_TypeID is the unique identifier for the type CustomReserved9.
const CustomReserved9_TypeID = 0xa1680744031fdb2d

func NewCustomReserved9(s *capnp.Segment) (CustomReserved9, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved9(st), err
}

func NewRootCustomReserved9(s *capnp.Segment) (CustomReserved9, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved9(st), err
}

func ReadRootCustomReserved9(msg *capnp.Message) (CustomReserved9, error) {
	root, err := msg.Root()
	return CustomReserved9(root.Struct()), err
}

func (s CustomReserved9) String() string {
	str, _ := text.Marshal(0xa1680744031fdb2d, capnp.Struct(s))
	return str
}

func (s CustomReserved9) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved9) DecodeFromPtr(p capnp.Ptr) CustomReserved9 {
	return CustomReserved9(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved9) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved9) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved9) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved9) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved9_List is a list of CustomReserved9.
type CustomReserved9_List = capnp.StructList[CustomReserved9]

// NewCustomReserved9 creates a new list of CustomReserved9.
func NewCustomReserved9_List(s *capnp.Segment, sz int32) (CustomReserved9_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved9](l), err
}

// CustomReserved9_Future is a wrapper for a CustomReserved9 promised by a client call.
type CustomReserved9_Future struct{ *capnp.Future }

func (f CustomReserved9_Future) Struct() (CustomReserved9, error) {
	p, err := f.Future.Ptr()
	return CustomReserved9(p.Struct()), err
}

type CustomReserved10 capnp.Struct

// CustomReserved10_TypeID is the unique identifier for the type CustomReserved10.
const CustomReserved10_TypeID = 0xcb9fd56c7057593a

func NewCustomReserved10(s *capnp.Segment) (CustomReserved10, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved10(st), err
}

func NewRootCustomReserved10(s *capnp.Segment) (CustomReserved10, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved10(st), err
}

func ReadRootCustomReserved10(msg *capnp.Message) (CustomReserved10, error) {
	root, err := msg.Root()
	return CustomReserved10(root.Struct()), err
}

func (s CustomReserved10) String() string {
	str, _ := text.Marshal(0xcb9fd56c7057593a, capnp.Struct(s))
	return str
}

func (s CustomReserved10) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved10) DecodeFromPtr(p capnp.Ptr) CustomReserved10 {
	return CustomReserved10(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved10) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved10) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved10) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved10) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved10_List is a list of CustomReserved10.
type CustomReserved10_List = capnp.StructList[CustomReserved10]

// NewCustomReserved10 creates a new list of CustomReserved10.
func NewCustomReserved10_List(s *capnp.Segment, sz int32) (CustomReserved10_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved10](l), err
}

// CustomReserved10_Future is a wrapper for a CustomReserved10 promised by a client call.
type CustomReserved10_Future struct{ *capnp.Future }

func (f CustomReserved10_Future) Struct() (CustomReserved10, error) {
	p, err := f.Future.Ptr()
	return CustomReserved10(p.Struct()), err
}

type CustomReserved11 capnp.Struct

// CustomReserved11_TypeID is the unique identifier for the type CustomReserved11.
const CustomReserved11_TypeID = 0xc2243c65e0340384

func NewCustomReserved11(s *capnp.Segment) (CustomReserved11, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved11(st), err
}

func NewRootCustomReserved11(s *capnp.Segment) (CustomReserved11, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved11(st), err
}

func ReadRootCustomReserved11(msg *capnp.Message) (CustomReserved11, error) {
	root, err := msg.Root()
	return CustomReserved11(root.Struct()), err
}

func (s CustomReserved11) String() string {
	str, _ := text.Marshal(0xc2243c65e0340384, capnp.Struct(s))
	return str
}

func (s CustomReserved11) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved11) DecodeFromPtr(p capnp.Ptr) CustomReserved11 {
	return CustomReserved11(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved11) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved11) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved11) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved11) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved11_List is a list of CustomReserved11.
type CustomReserved11_List = capnp.StructList[CustomReserved11]

// NewCustomReserved11 creates a new list of CustomReserved11.
func NewCustomReserved11_List(s *capnp.Segment, sz int32) (CustomReserved11_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved11](l), err
}

// CustomReserved11_Future is a wrapper for a CustomReserved11 promised by a client call.
type CustomReserved11_Future struct{ *capnp.Future }

func (f CustomReserved11_Future) Struct() (CustomReserved11, error) {
	p, err := f.Future.Ptr()
	return CustomReserved11(p.Struct()), err
}

type CustomReserved12 capnp.Struct

// CustomReserved12_TypeID is the unique identifier for the type CustomReserved12.
const CustomReserved12_TypeID = 0x9ccdc8676701b412

func NewCustomReserved12(s *capnp.Segment) (CustomReserved12, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved12(st), err
}

func NewRootCustomReserved12(s *capnp.Segment) (CustomReserved12, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved12(st), err
}

func ReadRootCustomReserved12(msg *capnp.Message) (CustomReserved12, error) {
	root, err := msg.Root()
	return CustomReserved12(root.Struct()), err
}

func (s CustomReserved12) String() string {
	str, _ := text.Marshal(0x9ccdc8676701b412, capnp.Struct(s))
	return str
}

func (s CustomReserved12) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved12) DecodeFromPtr(p capnp.Ptr) CustomReserved12 {
	return CustomReserved12(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved12) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved12) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved12) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved12) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved12_List is a list of CustomReserved12.
type CustomReserved12_List = capnp.StructList[CustomReserved12]

// NewCustomReserved12 creates a new list of CustomReserved12.
func NewCustomReserved12_List(s *capnp.Segment, sz int32) (CustomReserved12_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved12](l), err
}

// CustomReserved12_Future is a wrapper for a CustomReserved12 promised by a client call.
type CustomReserved12_Future struct{ *capnp.Future }

func (f CustomReserved12_Future) Struct() (CustomReserved12, error) {
	p, err := f.Future.Ptr()
	return CustomReserved12(p.Struct()), err
}

type CustomReserved13 capnp.Struct

// CustomReserved13_TypeID is the unique identifier for the type CustomReserved13.
const CustomReserved13_TypeID = 0xcd96dafb67a082d0

func NewCustomReserved13(s *capnp.Segment) (CustomReserved13, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved13(st), err
}

func NewRootCustomReserved13(s *capnp.Segment) (CustomReserved13, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved13(st), err
}

func ReadRootCustomReserved13(msg *capnp.Message) (CustomReserved13, error) {
	root, err := msg.Root()
	return CustomReserved13(root.Struct()), err
}

func (s CustomReserved13) String() string {
	str, _ := text.Marshal(0xcd96dafb67a082d0, capnp.Struct(s))
	return str
}

func (s CustomReserved13) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved13) DecodeFromPtr(p capnp.Ptr) CustomReserved13 {
	return CustomReserved13(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved13) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved13) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved13) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved13) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved13_List is a list of CustomReserved13.
type CustomReserved13_List = capnp.StructList[CustomReserved13]

// NewCustomReserved13 creates a new list of CustomReserved13.
func NewCustomReserved13_List(s *capnp.Segment, sz int32) (CustomReserved13_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved13](l), err
}

// CustomReserved13_Future is a wrapper for a CustomReserved13 promised by a client call.
type CustomReserved13_Future struct{ *capnp.Future }

func (f CustomReserved13_Future) Struct() (CustomReserved13, error) {
	p, err := f.Future.Ptr()
	return CustomReserved13(p.Struct()), err
}

type CustomReserved14 capnp.Struct

// CustomReserved14_TypeID is the unique identifier for the type CustomReserved14.
const CustomReserved14_TypeID = 0xb057204d7deadf3f

func NewCustomReserved14(s *capnp.Segment) (CustomReserved14, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved14(st), err
}

func NewRootCustomReserved14(s *capnp.Segment) (CustomReserved14, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved14(st), err
}

func ReadRootCustomReserved14(msg *capnp.Message) (CustomReserved14, error) {
	root, err := msg.Root()
	return CustomReserved14(root.Struct()), err
}

func (s CustomReserved14) String() string {
	str, _ := text.Marshal(0xb057204d7deadf3f, capnp.Struct(s))
	return str
}

func (s CustomReserved14) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved14) DecodeFromPtr(p capnp.Ptr) CustomReserved14 {
	return CustomReserved14(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved14) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved14) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved14) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved14) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved14_List is a list of CustomReserved14.
type CustomReserved14_List = capnp.StructList[CustomReserved14]

// NewCustomReserved14 creates a new list of CustomReserved14.
func NewCustomReserved14_List(s *capnp.Segment, sz int32) (CustomReserved14_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved14](l), err
}

// CustomReserved14_Future is a wrapper for a CustomReserved14 promised by a client call.
type CustomReserved14_Future struct{ *capnp.Future }

func (f CustomReserved14_Future) Struct() (CustomReserved14, error) {
	p, err := f.Future.Ptr()
	return CustomReserved14(p.Struct()), err
}

type CustomReserved15 capnp.Struct

// CustomReserved15_TypeID is the unique identifier for the type CustomReserved15.
const CustomReserved15_TypeID = 0xbd443b539493bc68

func NewCustomReserved15(s *capnp.Segment) (CustomReserved15, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved15(st), err
}

func NewRootCustomReserved15(s *capnp.Segment) (CustomReserved15, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved15(st), err
}

func ReadRootCustomReserved15(msg *capnp.Message) (CustomReserved15, error) {
	root, err := msg.Root()
	return CustomReserved15(root.Struct()), err
}

func (s CustomReserved15) String() string {
	str, _ := text.Marshal(0xbd443b539493bc68, capnp.Struct(s))
	return str
}

func (s CustomReserved15) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved15) DecodeFromPtr(p capnp.Ptr) CustomReserved15 {
	return CustomReserved15(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved15) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved15) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved15) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved15) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved15_List is a list of CustomReserved15.
type CustomReserved15_List = capnp.StructList[CustomReserved15]

// NewCustomReserved15 creates a new list of CustomReserved15.
func NewCustomReserved15_List(s *capnp.Segment, sz int32) (CustomReserved15_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved15](l), err
}

// CustomReserved15_Future is a wrapper for a CustomReserved15 promised by a client call.
type CustomReserved15_Future struct{ *capnp.Future }

func (f CustomReserved15_Future) Struct() (CustomReserved15, error) {
	p, err := f.Future.Ptr()
	return CustomReserved15(p.Struct()), err
}

type CustomReserved16 capnp.Struct

// CustomReserved16_TypeID is the unique identifier for the type CustomReserved16.
const CustomReserved16_TypeID = 0xfc6241ed8877b611

func NewCustomReserved16(s *capnp.Segment) (CustomReserved16, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved16(st), err
}

func NewRootCustomReserved16(s *capnp.Segment) (CustomReserved16, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved16(st), err
}

func ReadRootCustomReserved16(msg *capnp.Message) (CustomReserved16, error) {
	root, err := msg.Root()
	return CustomReserved16(root.Struct()), err
}

func (s CustomReserved16) String() string {
	str, _ := text.Marshal(0xfc6241ed8877b611, capnp.Struct(s))
	return str
}

func (s CustomReserved16) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved16) DecodeFromPtr(p capnp.Ptr) CustomReserved16 {
	return CustomReserved16(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved16) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved16) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved16) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved16) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved16_List is a list of CustomReserved16.
type CustomReserved16_List = capnp.StructList[CustomReserved16]

// NewCustomReserved16 creates a new list of CustomReserved16.
func NewCustomReserved16_List(s *capnp.Segment, sz int32) (CustomReserved16_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved16](l), err
}

// CustomReserved16_Future is a wrapper for a CustomReserved16 promised by a client call.
type CustomReserved16_Future struct{ *capnp.Future }

func (f CustomReserved16_Future) Struct() (CustomReserved16, error) {
	p, err := f.Future.Ptr()
	return CustomReserved16(p.Struct()), err
}

type MapdExtendedOutType uint16

// MapdExtendedOutType_TypeID is the unique identifier for the type MapdExtendedOutType.
const MapdExtendedOutType_TypeID = 0xcbdaf55a12931b65

// Values of MapdExtendedOutType.
const (
	MapdExtendedOutType_paths    MapdExtendedOutType = 0
	MapdExtendedOutType_settings MapdExtendedOutType = 1
)

// String returns the enum's constant name.
func (c MapdExtendedOutType) String() string {
	switch c {
	case MapdExtendedOutType_paths:
		return "paths"
	case MapdExtendedOutType_settings:
		return "settings"

	default:
		return ""
	}
}

// MapdExtendedOutTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func MapdExtendedOutTypeFromString(c string) MapdExtendedOutType {
	switch c {
	case "paths":
		return MapdExtendedOutType_paths
	case "settings":
		return MapdExtendedOutType_settings

	default:
		return 0
	}
}

type MapdExtendedOutType_List = capnp.EnumList[MapdExtendedOutType]

func NewMapdExtendedOutType_List(s *capnp.Segment, sz int32) (MapdExtendedOutType_List, error) {
	return capnp.NewEnumList[MapdExtendedOutType](s, sz)
}

type MapdExtendedOut capnp.Struct

// MapdExtendedOut_TypeID is the unique identifier for the type MapdExtendedOut.
const MapdExtendedOut_TypeID = 0xa30662f84033036c

func NewMapdExtendedOut(s *capnp.Segment) (MapdExtendedOut, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdExtendedOut(st), err
}

func NewRootMapdExtendedOut(s *capnp.Segment) (MapdExtendedOut, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdExtendedOut(st), err
}

func ReadRootMapdExtendedOut(msg *capnp.Message) (MapdExtendedOut, error) {
	root, err := msg.Root()
	return MapdExtendedOut(root.Struct()), err
}

func (s MapdExtendedOut) String() string {
	str, _ := text.Marshal(0xa30662f84033036c, capnp.Struct(s))
	return str
}

func (s MapdExtendedOut) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdExtendedOut) DecodeFromPtr(p capnp.Ptr) MapdExtendedOut {
	return MapdExtendedOut(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdExtendedOut) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdExtendedOut) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdExtendedOut) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdExtendedOut) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdExtendedOut) Type() MapdExtendedOutType {
	return MapdExtendedOutType(capnp.Struct(s).Uint16(0))
}

func (s MapdExtendedOut) SetType(v MapdExtendedOutType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s MapdExtendedOut) Json() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MapdExtendedOut) HasJson() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdExtendedOut) JsonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MapdExtendedOut) SetJson(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// MapdExtendedOut_List is a list of MapdExtendedOut.
type MapdExtendedOut_List = capnp.StructList[MapdExtendedOut]

// NewMapdExtendedOut creates a new list of MapdExtendedOut.
func NewMapdExtendedOut_List(s *capnp.Segment, sz int32) (MapdExtendedOut_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[MapdExtendedOut](l), err
}

// MapdExtendedOut_Future is a wrapper for a MapdExtendedOut promised by a client call.
type MapdExtendedOut_Future struct{ *capnp.Future }

func (f MapdExtendedOut_Future) Struct() (MapdExtendedOut, error) {
	p, err := f.Future.Ptr()
	return MapdExtendedOut(p.Struct()), err
}

type MapdInputType uint16

// MapdInputType_TypeID is the unique identifier for the type MapdInputType.
const MapdInputType_TypeID = 0x859f26628fc24358

// Values of MapdInputType.
const (
	MapdInputType_download                               MapdInputType = 0
	MapdInputType_setTargetLateralAccel                  MapdInputType = 1
	MapdInputType_setSpeedLimitOffset                    MapdInputType = 2
	MapdInputType_setSpeedLimitControl                   MapdInputType = 3
	MapdInputType_setCurveSpeedControl                   MapdInputType = 4
	MapdInputType_setVisionCurveSpeedControl             MapdInputType = 5
	MapdInputType_setLogLevel                            MapdInputType = 6
	MapdInputType_setVisionCurveTargetLatA               MapdInputType = 7
	MapdInputType_setVisionCurveMinTargetV               MapdInputType = 8
	MapdInputType_reloadSettings                         MapdInputType = 9
	MapdInputType_saveSettings                           MapdInputType = 10
	MapdInputType_setEnableSpeed                         MapdInputType = 11
	MapdInputType_setVisionCurveUseEnableSpeed           MapdInputType = 12
	MapdInputType_setCurveUseEnableSpeed                 MapdInputType = 13
	MapdInputType_setSpeedLimitUseEnableSpeed            MapdInputType = 14
	MapdInputType_setHoldLastSeenSpeedLimit              MapdInputType = 15
	MapdInputType_setCurveTargetJerk                     MapdInputType = 16
	MapdInputType_setCurveTargetAccel                    MapdInputType = 17
	MapdInputType_setCurveTargetOffset                   MapdInputType = 18
	MapdInputType_setDefaultLaneWidth                    MapdInputType = 19
	MapdInputType_setCurveTargetLatA                     MapdInputType = 20
	MapdInputType_loadDefaultSettings                    MapdInputType = 21
	MapdInputType_loadRecommendedSettings                MapdInputType = 22
	MapdInputType_setSlowDownForNextSpeedLimit           MapdInputType = 23
	MapdInputType_setSpeedUpForNextSpeedLimit            MapdInputType = 24
	MapdInputType_setHoldSpeedLimitWhileChangingSetSpeed MapdInputType = 25
)

// String returns the enum's constant name.
func (c MapdInputType) String() string {
	switch c {
	case MapdInputType_download:
		return "download"
	case MapdInputType_setTargetLateralAccel:
		return "setTargetLateralAccel"
	case MapdInputType_setSpeedLimitOffset:
		return "setSpeedLimitOffset"
	case MapdInputType_setSpeedLimitControl:
		return "setSpeedLimitControl"
	case MapdInputType_setCurveSpeedControl:
		return "setCurveSpeedControl"
	case MapdInputType_setVisionCurveSpeedControl:
		return "setVisionCurveSpeedControl"
	case MapdInputType_setLogLevel:
		return "setLogLevel"
	case MapdInputType_setVisionCurveTargetLatA:
		return "setVisionCurveTargetLatA"
	case MapdInputType_setVisionCurveMinTargetV:
		return "setVisionCurveMinTargetV"
	case MapdInputType_reloadSettings:
		return "reloadSettings"
	case MapdInputType_saveSettings:
		return "saveSettings"
	case MapdInputType_setEnableSpeed:
		return "setEnableSpeed"
	case MapdInputType_setVisionCurveUseEnableSpeed:
		return "setVisionCurveUseEnableSpeed"
	case MapdInputType_setCurveUseEnableSpeed:
		return "setCurveUseEnableSpeed"
	case MapdInputType_setSpeedLimitUseEnableSpeed:
		return "setSpeedLimitUseEnableSpeed"
	case MapdInputType_setHoldLastSeenSpeedLimit:
		return "setHoldLastSeenSpeedLimit"
	case MapdInputType_setCurveTargetJerk:
		return "setCurveTargetJerk"
	case MapdInputType_setCurveTargetAccel:
		return "setCurveTargetAccel"
	case MapdInputType_setCurveTargetOffset:
		return "setCurveTargetOffset"
	case MapdInputType_setDefaultLaneWidth:
		return "setDefaultLaneWidth"
	case MapdInputType_setCurveTargetLatA:
		return "setCurveTargetLatA"
	case MapdInputType_loadDefaultSettings:
		return "loadDefaultSettings"
	case MapdInputType_loadRecommendedSettings:
		return "loadRecommendedSettings"
	case MapdInputType_setSlowDownForNextSpeedLimit:
		return "setSlowDownForNextSpeedLimit"
	case MapdInputType_setSpeedUpForNextSpeedLimit:
		return "setSpeedUpForNextSpeedLimit"
	case MapdInputType_setHoldSpeedLimitWhileChangingSetSpeed:
		return "setHoldSpeedLimitWhileChangingSetSpeed"

	default:
		return ""
	}
}

// MapdInputTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func MapdInputTypeFromString(c string) MapdInputType {
	switch c {
	case "download":
		return MapdInputType_download
	case "setTargetLateralAccel":
		return MapdInputType_setTargetLateralAccel
	case "setSpeedLimitOffset":
		return MapdInputType_setSpeedLimitOffset
	case "setSpeedLimitControl":
		return MapdInputType_setSpeedLimitControl
	case "setCurveSpeedControl":
		return MapdInputType_setCurveSpeedControl
	case "setVisionCurveSpeedControl":
		return MapdInputType_setVisionCurveSpeedControl
	case "setLogLevel":
		return MapdInputType_setLogLevel
	case "setVisionCurveTargetLatA":
		return MapdInputType_setVisionCurveTargetLatA
	case "setVisionCurveMinTargetV":
		return MapdInputType_setVisionCurveMinTargetV
	case "reloadSettings":
		return MapdInputType_reloadSettings
	case "saveSettings":
		return MapdInputType_saveSettings
	case "setEnableSpeed":
		return MapdInputType_setEnableSpeed
	case "setVisionCurveUseEnableSpeed":
		return MapdInputType_setVisionCurveUseEnableSpeed
	case "setCurveUseEnableSpeed":
		return MapdInputType_setCurveUseEnableSpeed
	case "setSpeedLimitUseEnableSpeed":
		return MapdInputType_setSpeedLimitUseEnableSpeed
	case "setHoldLastSeenSpeedLimit":
		return MapdInputType_setHoldLastSeenSpeedLimit
	case "setCurveTargetJerk":
		return MapdInputType_setCurveTargetJerk
	case "setCurveTargetAccel":
		return MapdInputType_setCurveTargetAccel
	case "setCurveTargetOffset":
		return MapdInputType_setCurveTargetOffset
	case "setDefaultLaneWidth":
		return MapdInputType_setDefaultLaneWidth
	case "setCurveTargetLatA":
		return MapdInputType_setCurveTargetLatA
	case "loadDefaultSettings":
		return MapdInputType_loadDefaultSettings
	case "loadRecommendedSettings":
		return MapdInputType_loadRecommendedSettings
	case "setSlowDownForNextSpeedLimit":
		return MapdInputType_setSlowDownForNextSpeedLimit
	case "setSpeedUpForNextSpeedLimit":
		return MapdInputType_setSpeedUpForNextSpeedLimit
	case "setHoldSpeedLimitWhileChangingSetSpeed":
		return MapdInputType_setHoldSpeedLimitWhileChangingSetSpeed

	default:
		return 0
	}
}

type MapdInputType_List = capnp.EnumList[MapdInputType]

func NewMapdInputType_List(s *capnp.Segment, sz int32) (MapdInputType_List, error) {
	return capnp.NewEnumList[MapdInputType](s, sz)
}

type SpeedLimitOffsetType uint16

// SpeedLimitOffsetType_TypeID is the unique identifier for the type SpeedLimitOffsetType.
const SpeedLimitOffsetType_TypeID = 0xa5a3dfadcac04344

// Values of SpeedLimitOffsetType.
const (
	SpeedLimitOffsetType_static  SpeedLimitOffsetType = 0
	SpeedLimitOffsetType_percent SpeedLimitOffsetType = 1
)

// String returns the enum's constant name.
func (c SpeedLimitOffsetType) String() string {
	switch c {
	case SpeedLimitOffsetType_static:
		return "static"
	case SpeedLimitOffsetType_percent:
		return "percent"

	default:
		return ""
	}
}

// SpeedLimitOffsetTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func SpeedLimitOffsetTypeFromString(c string) SpeedLimitOffsetType {
	switch c {
	case "static":
		return SpeedLimitOffsetType_static
	case "percent":
		return SpeedLimitOffsetType_percent

	default:
		return 0
	}
}

type SpeedLimitOffsetType_List = capnp.EnumList[SpeedLimitOffsetType]

func NewSpeedLimitOffsetType_List(s *capnp.Segment, sz int32) (SpeedLimitOffsetType_List, error) {
	return capnp.NewEnumList[SpeedLimitOffsetType](s, sz)
}

type MapdIn capnp.Struct

// MapdIn_TypeID is the unique identifier for the type MapdIn.
const MapdIn_TypeID = 0xc86a3d38d13eb3ef

func NewMapdIn(s *capnp.Segment) (MapdIn, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdIn(st), err
}

func NewRootMapdIn(s *capnp.Segment) (MapdIn, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdIn(st), err
}

func ReadRootMapdIn(msg *capnp.Message) (MapdIn, error) {
	root, err := msg.Root()
	return MapdIn(root.Struct()), err
}

func (s MapdIn) String() string {
	str, _ := text.Marshal(0xc86a3d38d13eb3ef, capnp.Struct(s))
	return str
}

func (s MapdIn) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdIn) DecodeFromPtr(p capnp.Ptr) MapdIn {
	return MapdIn(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdIn) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdIn) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdIn) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdIn) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdIn) Type() MapdInputType {
	return MapdInputType(capnp.Struct(s).Uint16(0))
}

func (s MapdIn) SetType(v MapdInputType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s MapdIn) Float() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s MapdIn) SetFloat(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s MapdIn) Str() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MapdIn) HasStr() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdIn) StrBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MapdIn) SetStr(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s MapdIn) Bool() bool {
	return capnp.Struct(s).Bit(16)
}

func (s MapdIn) SetBool(v bool) {
	capnp.Struct(s).SetBit(16, v)
}

// MapdIn_List is a list of MapdIn.
type MapdIn_List = capnp.StructList[MapdIn]

// NewMapdIn creates a new list of MapdIn.
func NewMapdIn_List(s *capnp.Segment, sz int32) (MapdIn_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[MapdIn](l), err
}

// MapdIn_Future is a wrapper for a MapdIn promised by a client call.
type MapdIn_Future struct{ *capnp.Future }

func (f MapdIn_Future) Struct() (MapdIn, error) {
	p, err := f.Future.Ptr()
	return MapdIn(p.Struct()), err
}

type RoadContext uint16

// RoadContext_TypeID is the unique identifier for the type RoadContext.
const RoadContext_TypeID = 0xabefa88b9563dbae

// Values of RoadContext.
const (
	RoadContext_freeway RoadContext = 0
	RoadContext_city    RoadContext = 1
	RoadContext_unknown RoadContext = 2
)

// String returns the enum's constant name.
func (c RoadContext) String() string {
	switch c {
	case RoadContext_freeway:
		return "freeway"
	case RoadContext_city:
		return "city"
	case RoadContext_unknown:
		return "unknown"

	default:
		return ""
	}
}

// RoadContextFromString returns the enum value with a name,
// or the zero value if there's no such value.
func RoadContextFromString(c string) RoadContext {
	switch c {
	case "freeway":
		return RoadContext_freeway
	case "city":
		return RoadContext_city
	case "unknown":
		return RoadContext_unknown

	default:
		return 0
	}
}

type RoadContext_List = capnp.EnumList[RoadContext]

func NewRoadContext_List(s *capnp.Segment, sz int32) (RoadContext_List, error) {
	return capnp.NewEnumList[RoadContext](s, sz)
}

type MapdOut capnp.Struct

// MapdOut_TypeID is the unique identifier for the type MapdOut.
const MapdOut_TypeID = 0xa4f1eb3323f5f582

func NewMapdOut(s *capnp.Segment) (MapdOut, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 5})
	return MapdOut(st), err
}

func NewRootMapdOut(s *capnp.Segment) (MapdOut, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 5})
	return MapdOut(st), err
}

func ReadRootMapdOut(msg *capnp.Message) (MapdOut, error) {
	root, err := msg.Root()
	return MapdOut(root.Struct()), err
}

func (s MapdOut) String() string {
	str, _ := text.Marshal(0xa4f1eb3323f5f582, capnp.Struct(s))
	return str
}

func (s MapdOut) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdOut) DecodeFromPtr(p capnp.Ptr) MapdOut {
	return MapdOut(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdOut) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdOut) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdOut) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdOut) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdOut) WayName() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MapdOut) HasWayName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdOut) WayNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MapdOut) SetWayName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s MapdOut) WayRef() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s MapdOut) HasWayRef() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s MapdOut) WayRefBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s MapdOut) SetWayRef(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s MapdOut) RoadName() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s MapdOut) HasRoadName() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s MapdOut) RoadNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s MapdOut) SetRoadName(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s MapdOut) SpeedLimit() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(0))
}

func (s MapdOut) SetSpeedLimit(v float32) {
	capnp.Struct(s).SetUint32(0, math.Float32bits(v))
}

func (s MapdOut) NextSpeedLimit() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s MapdOut) SetNextSpeedLimit(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s MapdOut) NextSpeedLimitDistance() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(8))
}

func (s MapdOut) SetNextSpeedLimitDistance(v float32) {
	capnp.Struct(s).SetUint32(8, math.Float32bits(v))
}

func (s MapdOut) Hazard() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s MapdOut) HasHazard() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s MapdOut) HazardBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s MapdOut) SetHazard(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s MapdOut) NextHazard() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s MapdOut) HasNextHazard() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s MapdOut) NextHazardBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s MapdOut) SetNextHazard(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s MapdOut) NextHazardDistance() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(12))
}

func (s MapdOut) SetNextHazardDistance(v float32) {
	capnp.Struct(s).SetUint32(12, math.Float32bits(v))
}

func (s MapdOut) AdvisorySpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(16))
}

func (s MapdOut) SetAdvisorySpeed(v float32) {
	capnp.Struct(s).SetUint32(16, math.Float32bits(v))
}

func (s MapdOut) NextAdvisorySpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(20))
}

func (s MapdOut) SetNextAdvisorySpeed(v float32) {
	capnp.Struct(s).SetUint32(20, math.Float32bits(v))
}

func (s MapdOut) NextAdvisorySpeedDistance() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(24))
}

func (s MapdOut) SetNextAdvisorySpeedDistance(v float32) {
	capnp.Struct(s).SetUint32(24, math.Float32bits(v))
}

func (s MapdOut) OneWay() bool {
	return capnp.Struct(s).Bit(224)
}

func (s MapdOut) SetOneWay(v bool) {
	capnp.Struct(s).SetBit(224, v)
}

func (s MapdOut) Lanes() uint8 {
	return capnp.Struct(s).Uint8(29)
}

func (s MapdOut) SetLanes(v uint8) {
	capnp.Struct(s).SetUint8(29, v)
}

func (s MapdOut) TileLoaded() bool {
	return capnp.Struct(s).Bit(225)
}

func (s MapdOut) SetTileLoaded(v bool) {
	capnp.Struct(s).SetBit(225, v)
}

func (s MapdOut) SpeedLimitOffset() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(32))
}

func (s MapdOut) SetSpeedLimitOffset(v float32) {
	capnp.Struct(s).SetUint32(32, math.Float32bits(v))
}

func (s MapdOut) SuggestedSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(36))
}

func (s MapdOut) SetSuggestedSpeed(v float32) {
	capnp.Struct(s).SetUint32(36, math.Float32bits(v))
}

func (s MapdOut) EstimatedRoadWidth() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(40))
}

func (s MapdOut) SetEstimatedRoadWidth(v float32) {
	capnp.Struct(s).SetUint32(40, math.Float32bits(v))
}

func (s MapdOut) RoadContext() RoadContext {
	return RoadContext(capnp.Struct(s).Uint16(30))
}

func (s MapdOut) SetRoadContext(v RoadContext) {
	capnp.Struct(s).SetUint16(30, uint16(v))
}

func (s MapdOut) DistanceFromWayCenter() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(44))
}

func (s MapdOut) SetDistanceFromWayCenter(v float32) {
	capnp.Struct(s).SetUint32(44, math.Float32bits(v))
}

func (s MapdOut) VisionCurveSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(48))
}

func (s MapdOut) SetVisionCurveSpeed(v float32) {
	capnp.Struct(s).SetUint32(48, math.Float32bits(v))
}

func (s MapdOut) CurveSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(52))
}

func (s MapdOut) SetCurveSpeed(v float32) {
	capnp.Struct(s).SetUint32(52, math.Float32bits(v))
}

// MapdOut_List is a list of MapdOut.
type MapdOut_List = capnp.StructList[MapdOut]

// NewMapdOut creates a new list of MapdOut.
func NewMapdOut_List(s *capnp.Segment, sz int32) (MapdOut_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 56, PointerCount: 5}, sz)
	return capnp.StructList[MapdOut](l), err
}

// MapdOut_Future is a wrapper for a MapdOut promised by a client call.
type MapdOut_Future struct{ *capnp.Future }

func (f MapdOut_Future) Struct() (MapdOut, error) {
	p, err := f.Future.Ptr()
	return MapdOut(p.Struct()), err
}

const schema_b526ba661d550a59 = "x\xda\x94\x97\x7f\x8c\x14\xe5\x19\xc7\x9f\xe7\x9d\xdd\x9b\xbb" +
	"c\x97\xbd\xbdw\xb0\xb5\x94\\\x7fXSM\xaf\xb0\x1c" +
	"W\xe5\xac=\x8f;\x8d\x90E\\\x068\xb8H\xc2\xec" +
	"\xce{\xbb\x03{3\xdb\x99\xf7\xeeX\xa2A\xa9&\xd8" +
	"\xd6\x18+\x9aj$\xda\")m\x03\xadV\x1bK$" +
	"\x15b\x13\xaa%)F\xd3\x14k\x00\x13\xa3\xb15z" +
	")$5\xc5l\xf3\xbc\xfbSn\x1a\xdd\xbf\xf6\xe6\xf3" +
	"|\xe7\xf95\xef\xfb>\xef-\xcbFn\x8a\xa4\xe2\xbf" +
	"\xe8\x02\x96)E;*\xc9\x1d[\xdev\xe5\x91\xbb!" +
	"\xb9\x18+[\xba7.\x99<z\xf5\xf3\x10\xd1\x01\x06" +
	"\xfe\x10\x99@~*\xa2\x83V\xf9\xcd\x85\xf4\xca\x89\x8f" +
	"N\xdc\x13\xa2\xfa%\xa9\x8e)\xd5\xe6\xd1\x13\x0ff\xaf" +
	"~\xf2>H.fM\x15\xe0\xc0c\x915\xc8\x0f\xd7" +
	"\xe4\xb3\x0c\xb0\xd2\xfb\x1c\xe6\xf3'O=\x11\xe20\xa9" +
	"g\x91\x7fC'\x87\xfdo\xf6icz\xe1g!*" +
	"\xd4'\x90/R\xaa\xa26p\xd3\x7f\xb2\x1d\x07 \xb3" +
	"\x18[dQ$\xdd\\\xc7\x04\xf2\xa8\xae\x03p\xd4g" +
	"\x01+{.^\xfc\xfa\xc0?\xe7\x9e&\xb5\xde\xa2\x8e" +
	"\x92z\xab\xfe%\xe4S\xa4\x1ep\xf4\xbfE\x00+c" +
	"\xa3/\xbdr\xf8\xec\x81\x83\xf3jz+\xb6\x07\xf9\\" +
	"\x8c\x1c\x7f\x10\xbb\x0e\xb0\xb2\xf1\xe9\xcc\xdf\xbf5s\xea" +
	"`H\xb2s1J\"N\xc9\x1ey3\xf7\xc8\x8f\x0e" +
	"}\xf8\xeby\xfe\xce\xc7\x86\x9a\xfe\xd6\x01V\xb6>\xff" +
	"n\xea\xc1O\xce\x1e\x09+>N\xc5+\x7f\xc3g\xdf" +
	"\xbfk\xedW\xc6\x7f\x1b\x1a5[\x8fz\x12\xd3_u" +
	"r\xee\x0b!\xaa\xf3\x94\xdb\xc5\x18\xa9\x0a/>\xbc\xcf" +
	"\xbca\xecX\x88\xea4\xf9zG\xa9\xee\xd5V\x9c\x13" +
	"\xdf\xbd\xeaD\x88\xea8\xa9\xdeP\xaa\x0f\x7f\xf7\xbd\xd3" +
	"\xd7\xdf\xb8\xfdd\xe8Gy&\xd6\x8b\xfc\xb8\xaa\xf5X" +
	"\xec]\xc0\xca\xd0\x96\xf1R\xf1\x8d'_\x0d\xf1\xf9P" +
	"<\x8b\xfc\xa0\xaaB,~\xb8w\xe2\xe2\x99W\xe7\xf5" +
	"\xee\x9e\xf8.\xe4\x8f\xc4\xc9\xdfCq\xfa\x16\x7f\xdd\xf3" +
	"T\xfe\xbfg\x1e=\x15\xe2\xef1\xf2wX\xf9\x1bL" +
	"\x8f\xfd\xe0\xa7\xe3\x8f\x9e\x09Q\xddO\x1d\xde\xafT'" +
	"\xdc?.\xd8\xf4\xf2\x1d\xff\x0eQ\x95I\xf5\x80R]" +
	"\xb9\x7f\xff\xea\xae\x7f]q!D\xe5\x90\xea.\xa5:" +
	"\x10)}r\xc3\xbd\x0f|\x1c\xa2\xdaB\xaa)\xa5J" +
	"\xfe~v\xef\x07#\xd9K!\xaa\xd5\x94\xfd\xd6\xb8\x0e" +
	"K+9\xe1\x0b\xab\xb84\x17\x99\x0e\xa47\xb54\xa7" +
	"~\xbe\x9d\xb3JnihT=\xac\x17\x81\xf0g\x84" +
	"f\xaf\xb8\x1d\xb1\x1d\xfd\xb2\xcf\xd2\xaf\xb5J\xf6j\xb7" +
	"4-7\x94K\x02\xe0v\xc4L\x01\x19\x00O\xe1\x1a" +
	"\x00D\xde\x8f\xcf\x02 \xe3\xfd\xf8s\x00\xd4x?\xfe" +
	"\x0a\x00#\xb5\xdf(\xef\xc73\x00\xd8\xc1S\x98\x05@" +
	"\x9d\xf7\xe3+\x00\xd8\xc9S\xea\xb7\x8b\x0f\xe2.\x00\xec" +
	"\xe6)\xdc\x0e\x80\x0bx\xbfz\x8e\xf1k\xf0}\x00\x8c" +
	"\xf3~<\x0a\x80\x0by?\xbe\x0d\x80\x09\x9e\xc2\xd7\x00" +
	"\xb0\x87\x0f\xe2\xe3\x00\x98\xe4\x83*n/\x1fT\xf1x" +
	"\xed\xd9\xa8\xd9\x17\xd5\x9e\xaf\xe0\x83x\x02\x00\xbf\xc0\x07" +
	"\x95\xdf/\xf2\x95\xca\xdf\x95\x037\xe2\x10\x02Tlo" +
	"\xd6-z\x96\x0d\x00\x95@\xc8\x0d\x96\x9f\x17(\xd3\x96" +
	"\x14\xbeU\xec\x1b\xc9\xe5D\x91\xb8Y\x12\xc2\xc6\xb43" +
	"\xe5\xc8u\x93\x93z \xe4et\xd4s\x13\xd2\xf7\x94" +
	"xt\xda\x9f\x11\xa8\x8c\xadx\x93\x138\x1es\x95\xb5" +
	"n\x94\xbeV5\xa6\xbd|Z\x80>#\xe6IUJ" +
	"\x94\xd1H5\xc5V\xdbZ\xc7\xad\x9a7\x01T|A" +
	"\x85\x98\x02\x86\xa5t\xdc|P\x09\xac\x19a\x0a)!" +
	"Q}\x14\xf2f\xd7\xca\x16a\xb8\x1a\xferg\x1b\x03" +
	"\xa1\xec\xc2L\xd4\xcd\xd5J\xea\x86\x96\xf7\xd4\x1fLU" +
	"\xde|\xad\xa4\xd7\xac\xb7zE;\xcd\xac@\x9aB\xb8" +
	"JJJ\x94M\x97\xd5\xac\xd7\x08\xcd\xdfq9\x1c\xc9" +
	"\xe9\xb5\xa6\xb7\xd2u\x93\x89\xc9Z\xd7\xc7\xc4\xa45\x8d" +
	"E\x99\xb6\\1\xee\xe8\xb6,\\.N[\x9a\x1c\xa9" +
	"P7H\x8b\xd3EImpt\xea\x02\xd1\xf5\"\xe7" +
	"E\xa7\xa6\x84k\x0b[Y\xdc|\x00TU\xd1\x9b\x1d" +
	"\xf3f\xdd[<\xff6\xb1\xb3Zd:AE6k" +
	"\xdeX\xfa\x94\xd5\xd1kV\xaa\xd9\xd4\xea\xb5\xca\xf1\x82" +
	"S\x14\xa3\x05\xcb\xcd;n\xde\x14\xc3U\xf9\xe7\xdf\xa2" +
	"\xba\x9dZ\xde\xe6\x9e^\xf9y\xf6\xf4\xcd;\xa5*{" +
	"\x9d6-iSwj\x11\x80\x08\x02$\xaf\xb9\x16 " +
	"s\x95\x86\x99e\x0c\x11\x0d$\xd6O\xec\x9b\x1afV" +
	"0L\xc8rI`\xa2yF\x03b\x020\xb1=\xf0" +
	"\\\x8c\x01\xc3\x184\xc3k\xff'|=\xec\xe6zX" +
	"\xbe\x85\xad\x02070\x0d\xcdm\x8ca\xb2\x16\x9ao" +
	"eC\x00\xe6f\xe26q\xc6\x0cu\xfeXl\x0d\x80" +
	"\xb9\x8dx\x911D\xcd@\x0d\x80;l\x02\xc0,\x10" +
	"\x96$\x8f\xa0\x81\x11\x00\xfe}\xb6\x0b\xc0,\x11\xbf\x93" +
	"x\x94\x19\x18\x05\xe0ev\x14\xc0\xbc\x93\xf8^\xe2\x1d" +
	"\x9a\x81\x1d\x00\xfc>\x15\xf6n\xe2?&\xaeG\x0c\x1a" +
	"h\xfc~\xe5\x7f/\xf1}\xc4;5\x03;i\x1a\xb1" +
	"\xc7\x01\xcc}\xc4\x9f\"\xde\x151\xb0\x0b\x80\xefg>" +
	"\x80\xf9\x04\xf1C\xc4\xbb\xa3\x06v\x03\xf0\x83\xec'\x00" +
	"\xe6!\xe2\xcf\x11_\xd0a\xe0\x02\x00\xfe\x0c{\x0d\xc0" +
	"|\x81\xf8\xcb\xc4c\xe7\x0c\x8c\x01\xf0\xe3*\x9f\x17\x89" +
	"\x9f$\x1e_b`\x1c\x80\xff\x89-\x070_\"\xfe" +
	"\x17\xe2\x0b\xcf\x1b\xb8\x10\x80\xffY\xe5y\x92\xf8\xeb\xc4" +
	"\x13\x9d\x06&\x00\xf8i\xf6C\x00\xf3u\xe2\xe7\x88\xf7" +
	"t\x19\xd8\x03\xc0\xdfR\xfd\xf9\x07\xf1\xf7\x88'\xbb\x0d" +
	"L\x02\xf0wT]\xef\x11\xbf@\xbc7a`/\x00" +
	"\x9fcY\x00\xf3#\xe2\x97\x88\xf3\x05\x06r\x00\xfe1" +
	"{\x16\xc0\xbcD\xbcSc\x984b\x06\x1a\x00<\xaa" +
	"Q\xdcNMC\xd3 \xbe(n\xe0\"\x00\x9e\xd4(" +
	"\xcf\x1e\xe2_\xd6\x18\xee\x9e\xb5\xca\xb7YS\xa2\xbe\x90" +
	"\x86g\xad\xf2z1\xd9XW\xbeg\xd9d\x07\x9a\x11" +
	"5\x16\xd46\x1bh\x8e\xc4n`\xd8\x0dXqk;" +
	"\x13\x86\xab\xfbp\x9e\x01\xab|\xcc\x19\x0e\xa4\xe5\xe6D" +
	"]0\\\xb0vY\xbe\xdd\xf0N\xfa[\xad]\x16h" +
	"!\x10}{\xcc\xa1\xf7\xb5\xa6\x83\x8ae\xcf8\x81\xe7" +
	"\x97\xa1\xaf:\x17Z#\x8f\xd83\x0e\x92\xb1\x9a\xc2<" +
	"\x1b\xab\xdbj~s\xd8L\xccs\xc5\xb8UF\x04\x86" +
	"\x08\xd8W\xb4\\\x11`\x070\xec\x00\xacH\xa7(\xd2" +
	"4\xbf4a\xd7%\x8d\xce\xa0\x9aV\x81\x904ik" +
	"\x11\x83\xe9|^\x04\x92\x1a\xf4\xe94E \x9d)K" +
	"\x0a\xb4\xd7{\x96=\xee\xd8\x9a,4\x8c\xd4\x7f\x1aW" +
	"\xa0\x8b\x9d\x12\x13\xcdKn\xf5\x10\xa8\xd8N\xad\x9b\xb7" +
	"\xf8\xde\xd4\xb8U\x1e\xed\x13\xae\x14~\xe3\xfd\x19\x9a3" +
	"\xee\xe84\xd6g_KF\xb9\xda@T%4`\xed" +
	" \x89\x86\x1c$\x8d\x89R\xabN]Q\xd4aF'" +
	"D29DY%\xbbV\x01\xd07\x96NnwI" +
	"\xf89\xe1\xcavN\xd3\xc1\xd6\xd34\xec8\xa3.\x8d" +
	"\x0e{\xae\x14;\xd5\x91\x16S\xc1\x97\xacR\xc1\x17]" +
	"K\x97\xa3d|\x15\xc0\xeeI_\x88Y\xab\x9c\xc89" +
	"\xb2\xbc{\xda\xdd\xe1z\xb3n;\x99\xa4\xda\x9a\x03\xba" +
	"\x9dj\xf72x]\xbb\x01\x06\xdb}!\xf5Y\xcdT" +
	"\xd7Mt\xa9\x8f=\x8d\x89d\xd1\xf4\xb9C\xc3L\xa1" +
	"9\x17\x92b9@f\x9b\x86\x99\"C\xac\xce\x84\xa4" +
	"\xf35\x80\x8c\xada\xa6\xc40\xa9\xf5\xa8\x89\x90\x9c\xa2" +
	"\xb7\x0b\x1afdsv5\xfe\x7f\xad.\xdb\xbe\xc9\xa2" +
	"g5\x8e\x08=\x90~}\xa7'\xb2\x9eWl\xec\xa7" +
	"vJ]\xd6\xd6\x14\x1e\xae^\xb0[\x16\xef\xf2\xea\xe2" +
	"]\x03\xd0W\xb2dA]\xdb\xaa\x17\x14\x80\xb6\x12\x19" +
	"hs\x15\xb4\xabo\xf7zr}\x9b\xfa\xef\xb4\xbb\xc8" +
	"\xe8\x85\xff\x05\x00\x00\xff\xff\xa8\x0b\xdc^"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b526ba661d550a59,
		Nodes: []uint64{
			0x80ae746ee2596b11,
			0x81c2f05a394cf4af,
			0x859f26628fc24358,
			0x9ccdc8676701b412,
			0xa1680744031fdb2d,
			0xa30662f84033036c,
			0xa4f1eb3323f5f582,
			0xa5a3dfadcac04344,
			0xa5cd762cd951a455,
			0xabefa88b9563dbae,
			0xaedffd8f31e7b55d,
			0xb057204d7deadf3f,
			0xb86e6369214c01c8,
			0xbd443b539493bc68,
			0xc2243c65e0340384,
			0xc86a3d38d13eb3ef,
			0xcb9fd56c7057593a,
			0xcbdaf55a12931b65,
			0xcd96dafb67a082d0,
			0xda96579883444c35,
			0xf35cc4560bbf6ec2,
			0xf416ec09499d9d19,
			0xf98d843bfd7004a3,
			0xfc6241ed8877b611,
		},
		Compressed: true,
	})
}
