// Code generated by capnpc-go. DO NOT EDIT.

package custom

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
)

type CustomReserved0 capnp.Struct

// CustomReserved0_TypeID is the unique identifier for the type CustomReserved0.
const CustomReserved0_TypeID = 0x81c2f05a394cf4af

func NewCustomReserved0(s *capnp.Segment) (CustomReserved0, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved0(st), err
}

func NewRootCustomReserved0(s *capnp.Segment) (CustomReserved0, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved0(st), err
}

func ReadRootCustomReserved0(msg *capnp.Message) (CustomReserved0, error) {
	root, err := msg.Root()
	return CustomReserved0(root.Struct()), err
}

func (s CustomReserved0) String() string {
	str, _ := text.Marshal(0x81c2f05a394cf4af, capnp.Struct(s))
	return str
}

func (s CustomReserved0) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved0) DecodeFromPtr(p capnp.Ptr) CustomReserved0 {
	return CustomReserved0(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved0) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved0) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved0) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved0) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved0_List is a list of CustomReserved0.
type CustomReserved0_List = capnp.StructList[CustomReserved0]

// NewCustomReserved0 creates a new list of CustomReserved0.
func NewCustomReserved0_List(s *capnp.Segment, sz int32) (CustomReserved0_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved0](l), err
}

// CustomReserved0_Future is a wrapper for a CustomReserved0 promised by a client call.
type CustomReserved0_Future struct{ *capnp.Future }

func (f CustomReserved0_Future) Struct() (CustomReserved0, error) {
	p, err := f.Future.Ptr()
	return CustomReserved0(p.Struct()), err
}

type CustomReserved1 capnp.Struct

// CustomReserved1_TypeID is the unique identifier for the type CustomReserved1.
const CustomReserved1_TypeID = 0xaedffd8f31e7b55d

func NewCustomReserved1(s *capnp.Segment) (CustomReserved1, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved1(st), err
}

func NewRootCustomReserved1(s *capnp.Segment) (CustomReserved1, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved1(st), err
}

func ReadRootCustomReserved1(msg *capnp.Message) (CustomReserved1, error) {
	root, err := msg.Root()
	return CustomReserved1(root.Struct()), err
}

func (s CustomReserved1) String() string {
	str, _ := text.Marshal(0xaedffd8f31e7b55d, capnp.Struct(s))
	return str
}

func (s CustomReserved1) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved1) DecodeFromPtr(p capnp.Ptr) CustomReserved1 {
	return CustomReserved1(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved1) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved1) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved1) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved1) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved1_List is a list of CustomReserved1.
type CustomReserved1_List = capnp.StructList[CustomReserved1]

// NewCustomReserved1 creates a new list of CustomReserved1.
func NewCustomReserved1_List(s *capnp.Segment, sz int32) (CustomReserved1_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved1](l), err
}

// CustomReserved1_Future is a wrapper for a CustomReserved1 promised by a client call.
type CustomReserved1_Future struct{ *capnp.Future }

func (f CustomReserved1_Future) Struct() (CustomReserved1, error) {
	p, err := f.Future.Ptr()
	return CustomReserved1(p.Struct()), err
}

type CustomReserved2 capnp.Struct

// CustomReserved2_TypeID is the unique identifier for the type CustomReserved2.
const CustomReserved2_TypeID = 0xf35cc4560bbf6ec2

func NewCustomReserved2(s *capnp.Segment) (CustomReserved2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved2(st), err
}

func NewRootCustomReserved2(s *capnp.Segment) (CustomReserved2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved2(st), err
}

func ReadRootCustomReserved2(msg *capnp.Message) (CustomReserved2, error) {
	root, err := msg.Root()
	return CustomReserved2(root.Struct()), err
}

func (s CustomReserved2) String() string {
	str, _ := text.Marshal(0xf35cc4560bbf6ec2, capnp.Struct(s))
	return str
}

func (s CustomReserved2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved2) DecodeFromPtr(p capnp.Ptr) CustomReserved2 {
	return CustomReserved2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved2_List is a list of CustomReserved2.
type CustomReserved2_List = capnp.StructList[CustomReserved2]

// NewCustomReserved2 creates a new list of CustomReserved2.
func NewCustomReserved2_List(s *capnp.Segment, sz int32) (CustomReserved2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved2](l), err
}

// CustomReserved2_Future is a wrapper for a CustomReserved2 promised by a client call.
type CustomReserved2_Future struct{ *capnp.Future }

func (f CustomReserved2_Future) Struct() (CustomReserved2, error) {
	p, err := f.Future.Ptr()
	return CustomReserved2(p.Struct()), err
}

type CustomReserved3 capnp.Struct

// CustomReserved3_TypeID is the unique identifier for the type CustomReserved3.
const CustomReserved3_TypeID = 0xda96579883444c35

func NewCustomReserved3(s *capnp.Segment) (CustomReserved3, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved3(st), err
}

func NewRootCustomReserved3(s *capnp.Segment) (CustomReserved3, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved3(st), err
}

func ReadRootCustomReserved3(msg *capnp.Message) (CustomReserved3, error) {
	root, err := msg.Root()
	return CustomReserved3(root.Struct()), err
}

func (s CustomReserved3) String() string {
	str, _ := text.Marshal(0xda96579883444c35, capnp.Struct(s))
	return str
}

func (s CustomReserved3) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved3) DecodeFromPtr(p capnp.Ptr) CustomReserved3 {
	return CustomReserved3(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved3) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved3) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved3) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved3) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved3_List is a list of CustomReserved3.
type CustomReserved3_List = capnp.StructList[CustomReserved3]

// NewCustomReserved3 creates a new list of CustomReserved3.
func NewCustomReserved3_List(s *capnp.Segment, sz int32) (CustomReserved3_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved3](l), err
}

// CustomReserved3_Future is a wrapper for a CustomReserved3 promised by a client call.
type CustomReserved3_Future struct{ *capnp.Future }

func (f CustomReserved3_Future) Struct() (CustomReserved3, error) {
	p, err := f.Future.Ptr()
	return CustomReserved3(p.Struct()), err
}

type CustomReserved4 capnp.Struct

// CustomReserved4_TypeID is the unique identifier for the type CustomReserved4.
const CustomReserved4_TypeID = 0x80ae746ee2596b11

func NewCustomReserved4(s *capnp.Segment) (CustomReserved4, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved4(st), err
}

func NewRootCustomReserved4(s *capnp.Segment) (CustomReserved4, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved4(st), err
}

func ReadRootCustomReserved4(msg *capnp.Message) (CustomReserved4, error) {
	root, err := msg.Root()
	return CustomReserved4(root.Struct()), err
}

func (s CustomReserved4) String() string {
	str, _ := text.Marshal(0x80ae746ee2596b11, capnp.Struct(s))
	return str
}

func (s CustomReserved4) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved4) DecodeFromPtr(p capnp.Ptr) CustomReserved4 {
	return CustomReserved4(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved4) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved4) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved4) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved4) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved4_List is a list of CustomReserved4.
type CustomReserved4_List = capnp.StructList[CustomReserved4]

// NewCustomReserved4 creates a new list of CustomReserved4.
func NewCustomReserved4_List(s *capnp.Segment, sz int32) (CustomReserved4_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved4](l), err
}

// CustomReserved4_Future is a wrapper for a CustomReserved4 promised by a client call.
type CustomReserved4_Future struct{ *capnp.Future }

func (f CustomReserved4_Future) Struct() (CustomReserved4, error) {
	p, err := f.Future.Ptr()
	return CustomReserved4(p.Struct()), err
}

type CustomReserved5 capnp.Struct

// CustomReserved5_TypeID is the unique identifier for the type CustomReserved5.
const CustomReserved5_TypeID = 0xa5cd762cd951a455

func NewCustomReserved5(s *capnp.Segment) (CustomReserved5, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved5(st), err
}

func NewRootCustomReserved5(s *capnp.Segment) (CustomReserved5, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved5(st), err
}

func ReadRootCustomReserved5(msg *capnp.Message) (CustomReserved5, error) {
	root, err := msg.Root()
	return CustomReserved5(root.Struct()), err
}

func (s CustomReserved5) String() string {
	str, _ := text.Marshal(0xa5cd762cd951a455, capnp.Struct(s))
	return str
}

func (s CustomReserved5) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved5) DecodeFromPtr(p capnp.Ptr) CustomReserved5 {
	return CustomReserved5(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved5) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved5) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved5) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved5) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved5_List is a list of CustomReserved5.
type CustomReserved5_List = capnp.StructList[CustomReserved5]

// NewCustomReserved5 creates a new list of CustomReserved5.
func NewCustomReserved5_List(s *capnp.Segment, sz int32) (CustomReserved5_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved5](l), err
}

// CustomReserved5_Future is a wrapper for a CustomReserved5 promised by a client call.
type CustomReserved5_Future struct{ *capnp.Future }

func (f CustomReserved5_Future) Struct() (CustomReserved5, error) {
	p, err := f.Future.Ptr()
	return CustomReserved5(p.Struct()), err
}

type CustomReserved6 capnp.Struct

// CustomReserved6_TypeID is the unique identifier for the type CustomReserved6.
const CustomReserved6_TypeID = 0xf98d843bfd7004a3

func NewCustomReserved6(s *capnp.Segment) (CustomReserved6, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved6(st), err
}

func NewRootCustomReserved6(s *capnp.Segment) (CustomReserved6, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved6(st), err
}

func ReadRootCustomReserved6(msg *capnp.Message) (CustomReserved6, error) {
	root, err := msg.Root()
	return CustomReserved6(root.Struct()), err
}

func (s CustomReserved6) String() string {
	str, _ := text.Marshal(0xf98d843bfd7004a3, capnp.Struct(s))
	return str
}

func (s CustomReserved6) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved6) DecodeFromPtr(p capnp.Ptr) CustomReserved6 {
	return CustomReserved6(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved6) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved6) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved6) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved6) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved6_List is a list of CustomReserved6.
type CustomReserved6_List = capnp.StructList[CustomReserved6]

// NewCustomReserved6 creates a new list of CustomReserved6.
func NewCustomReserved6_List(s *capnp.Segment, sz int32) (CustomReserved6_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved6](l), err
}

// CustomReserved6_Future is a wrapper for a CustomReserved6 promised by a client call.
type CustomReserved6_Future struct{ *capnp.Future }

func (f CustomReserved6_Future) Struct() (CustomReserved6, error) {
	p, err := f.Future.Ptr()
	return CustomReserved6(p.Struct()), err
}

type CustomReserved7 capnp.Struct

// CustomReserved7_TypeID is the unique identifier for the type CustomReserved7.
const CustomReserved7_TypeID = 0xb86e6369214c01c8

func NewCustomReserved7(s *capnp.Segment) (CustomReserved7, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved7(st), err
}

func NewRootCustomReserved7(s *capnp.Segment) (CustomReserved7, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved7(st), err
}

func ReadRootCustomReserved7(msg *capnp.Message) (CustomReserved7, error) {
	root, err := msg.Root()
	return CustomReserved7(root.Struct()), err
}

func (s CustomReserved7) String() string {
	str, _ := text.Marshal(0xb86e6369214c01c8, capnp.Struct(s))
	return str
}

func (s CustomReserved7) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved7) DecodeFromPtr(p capnp.Ptr) CustomReserved7 {
	return CustomReserved7(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved7) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved7) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved7) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved7) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved7_List is a list of CustomReserved7.
type CustomReserved7_List = capnp.StructList[CustomReserved7]

// NewCustomReserved7 creates a new list of CustomReserved7.
func NewCustomReserved7_List(s *capnp.Segment, sz int32) (CustomReserved7_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved7](l), err
}

// CustomReserved7_Future is a wrapper for a CustomReserved7 promised by a client call.
type CustomReserved7_Future struct{ *capnp.Future }

func (f CustomReserved7_Future) Struct() (CustomReserved7, error) {
	p, err := f.Future.Ptr()
	return CustomReserved7(p.Struct()), err
}

type CustomReserved8 capnp.Struct

// CustomReserved8_TypeID is the unique identifier for the type CustomReserved8.
const CustomReserved8_TypeID = 0xf416ec09499d9d19

func NewCustomReserved8(s *capnp.Segment) (CustomReserved8, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved8(st), err
}

func NewRootCustomReserved8(s *capnp.Segment) (CustomReserved8, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved8(st), err
}

func ReadRootCustomReserved8(msg *capnp.Message) (CustomReserved8, error) {
	root, err := msg.Root()
	return CustomReserved8(root.Struct()), err
}

func (s CustomReserved8) String() string {
	str, _ := text.Marshal(0xf416ec09499d9d19, capnp.Struct(s))
	return str
}

func (s CustomReserved8) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved8) DecodeFromPtr(p capnp.Ptr) CustomReserved8 {
	return CustomReserved8(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved8) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved8) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved8) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved8) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved8_List is a list of CustomReserved8.
type CustomReserved8_List = capnp.StructList[CustomReserved8]

// NewCustomReserved8 creates a new list of CustomReserved8.
func NewCustomReserved8_List(s *capnp.Segment, sz int32) (CustomReserved8_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved8](l), err
}

// CustomReserved8_Future is a wrapper for a CustomReserved8 promised by a client call.
type CustomReserved8_Future struct{ *capnp.Future }

func (f CustomReserved8_Future) Struct() (CustomReserved8, error) {
	p, err := f.Future.Ptr()
	return CustomReserved8(p.Struct()), err
}

type CustomReserved9 capnp.Struct

// CustomReserved9_TypeID is the unique identifier for the type CustomReserved9.
const CustomReserved9_TypeID = 0xa1680744031fdb2d

func NewCustomReserved9(s *capnp.Segment) (CustomReserved9, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved9(st), err
}

func NewRootCustomReserved9(s *capnp.Segment) (CustomReserved9, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved9(st), err
}

func ReadRootCustomReserved9(msg *capnp.Message) (CustomReserved9, error) {
	root, err := msg.Root()
	return CustomReserved9(root.Struct()), err
}

func (s CustomReserved9) String() string {
	str, _ := text.Marshal(0xa1680744031fdb2d, capnp.Struct(s))
	return str
}

func (s CustomReserved9) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved9) DecodeFromPtr(p capnp.Ptr) CustomReserved9 {
	return CustomReserved9(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved9) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved9) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved9) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved9) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved9_List is a list of CustomReserved9.
type CustomReserved9_List = capnp.StructList[CustomReserved9]

// NewCustomReserved9 creates a new list of CustomReserved9.
func NewCustomReserved9_List(s *capnp.Segment, sz int32) (CustomReserved9_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved9](l), err
}

// CustomReserved9_Future is a wrapper for a CustomReserved9 promised by a client call.
type CustomReserved9_Future struct{ *capnp.Future }

func (f CustomReserved9_Future) Struct() (CustomReserved9, error) {
	p, err := f.Future.Ptr()
	return CustomReserved9(p.Struct()), err
}

type CustomReserved10 capnp.Struct

// CustomReserved10_TypeID is the unique identifier for the type CustomReserved10.
const CustomReserved10_TypeID = 0xcb9fd56c7057593a

func NewCustomReserved10(s *capnp.Segment) (CustomReserved10, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved10(st), err
}

func NewRootCustomReserved10(s *capnp.Segment) (CustomReserved10, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved10(st), err
}

func ReadRootCustomReserved10(msg *capnp.Message) (CustomReserved10, error) {
	root, err := msg.Root()
	return CustomReserved10(root.Struct()), err
}

func (s CustomReserved10) String() string {
	str, _ := text.Marshal(0xcb9fd56c7057593a, capnp.Struct(s))
	return str
}

func (s CustomReserved10) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved10) DecodeFromPtr(p capnp.Ptr) CustomReserved10 {
	return CustomReserved10(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved10) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved10) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved10) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved10) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved10_List is a list of CustomReserved10.
type CustomReserved10_List = capnp.StructList[CustomReserved10]

// NewCustomReserved10 creates a new list of CustomReserved10.
func NewCustomReserved10_List(s *capnp.Segment, sz int32) (CustomReserved10_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved10](l), err
}

// CustomReserved10_Future is a wrapper for a CustomReserved10 promised by a client call.
type CustomReserved10_Future struct{ *capnp.Future }

func (f CustomReserved10_Future) Struct() (CustomReserved10, error) {
	p, err := f.Future.Ptr()
	return CustomReserved10(p.Struct()), err
}

type CustomReserved11 capnp.Struct

// CustomReserved11_TypeID is the unique identifier for the type CustomReserved11.
const CustomReserved11_TypeID = 0xc2243c65e0340384

func NewCustomReserved11(s *capnp.Segment) (CustomReserved11, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved11(st), err
}

func NewRootCustomReserved11(s *capnp.Segment) (CustomReserved11, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved11(st), err
}

func ReadRootCustomReserved11(msg *capnp.Message) (CustomReserved11, error) {
	root, err := msg.Root()
	return CustomReserved11(root.Struct()), err
}

func (s CustomReserved11) String() string {
	str, _ := text.Marshal(0xc2243c65e0340384, capnp.Struct(s))
	return str
}

func (s CustomReserved11) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved11) DecodeFromPtr(p capnp.Ptr) CustomReserved11 {
	return CustomReserved11(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved11) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved11) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved11) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved11) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved11_List is a list of CustomReserved11.
type CustomReserved11_List = capnp.StructList[CustomReserved11]

// NewCustomReserved11 creates a new list of CustomReserved11.
func NewCustomReserved11_List(s *capnp.Segment, sz int32) (CustomReserved11_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved11](l), err
}

// CustomReserved11_Future is a wrapper for a CustomReserved11 promised by a client call.
type CustomReserved11_Future struct{ *capnp.Future }

func (f CustomReserved11_Future) Struct() (CustomReserved11, error) {
	p, err := f.Future.Ptr()
	return CustomReserved11(p.Struct()), err
}

type CustomReserved12 capnp.Struct

// CustomReserved12_TypeID is the unique identifier for the type CustomReserved12.
const CustomReserved12_TypeID = 0x9ccdc8676701b412

func NewCustomReserved12(s *capnp.Segment) (CustomReserved12, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved12(st), err
}

func NewRootCustomReserved12(s *capnp.Segment) (CustomReserved12, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved12(st), err
}

func ReadRootCustomReserved12(msg *capnp.Message) (CustomReserved12, error) {
	root, err := msg.Root()
	return CustomReserved12(root.Struct()), err
}

func (s CustomReserved12) String() string {
	str, _ := text.Marshal(0x9ccdc8676701b412, capnp.Struct(s))
	return str
}

func (s CustomReserved12) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved12) DecodeFromPtr(p capnp.Ptr) CustomReserved12 {
	return CustomReserved12(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved12) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved12) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved12) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved12) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved12_List is a list of CustomReserved12.
type CustomReserved12_List = capnp.StructList[CustomReserved12]

// NewCustomReserved12 creates a new list of CustomReserved12.
func NewCustomReserved12_List(s *capnp.Segment, sz int32) (CustomReserved12_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved12](l), err
}

// CustomReserved12_Future is a wrapper for a CustomReserved12 promised by a client call.
type CustomReserved12_Future struct{ *capnp.Future }

func (f CustomReserved12_Future) Struct() (CustomReserved12, error) {
	p, err := f.Future.Ptr()
	return CustomReserved12(p.Struct()), err
}

type CustomReserved13 capnp.Struct

// CustomReserved13_TypeID is the unique identifier for the type CustomReserved13.
const CustomReserved13_TypeID = 0xcd96dafb67a082d0

func NewCustomReserved13(s *capnp.Segment) (CustomReserved13, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved13(st), err
}

func NewRootCustomReserved13(s *capnp.Segment) (CustomReserved13, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved13(st), err
}

func ReadRootCustomReserved13(msg *capnp.Message) (CustomReserved13, error) {
	root, err := msg.Root()
	return CustomReserved13(root.Struct()), err
}

func (s CustomReserved13) String() string {
	str, _ := text.Marshal(0xcd96dafb67a082d0, capnp.Struct(s))
	return str
}

func (s CustomReserved13) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved13) DecodeFromPtr(p capnp.Ptr) CustomReserved13 {
	return CustomReserved13(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved13) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved13) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved13) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved13) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved13_List is a list of CustomReserved13.
type CustomReserved13_List = capnp.StructList[CustomReserved13]

// NewCustomReserved13 creates a new list of CustomReserved13.
func NewCustomReserved13_List(s *capnp.Segment, sz int32) (CustomReserved13_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved13](l), err
}

// CustomReserved13_Future is a wrapper for a CustomReserved13 promised by a client call.
type CustomReserved13_Future struct{ *capnp.Future }

func (f CustomReserved13_Future) Struct() (CustomReserved13, error) {
	p, err := f.Future.Ptr()
	return CustomReserved13(p.Struct()), err
}

type CustomReserved14 capnp.Struct

// CustomReserved14_TypeID is the unique identifier for the type CustomReserved14.
const CustomReserved14_TypeID = 0xb057204d7deadf3f

func NewCustomReserved14(s *capnp.Segment) (CustomReserved14, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved14(st), err
}

func NewRootCustomReserved14(s *capnp.Segment) (CustomReserved14, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved14(st), err
}

func ReadRootCustomReserved14(msg *capnp.Message) (CustomReserved14, error) {
	root, err := msg.Root()
	return CustomReserved14(root.Struct()), err
}

func (s CustomReserved14) String() string {
	str, _ := text.Marshal(0xb057204d7deadf3f, capnp.Struct(s))
	return str
}

func (s CustomReserved14) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved14) DecodeFromPtr(p capnp.Ptr) CustomReserved14 {
	return CustomReserved14(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved14) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved14) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved14) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved14) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved14_List is a list of CustomReserved14.
type CustomReserved14_List = capnp.StructList[CustomReserved14]

// NewCustomReserved14 creates a new list of CustomReserved14.
func NewCustomReserved14_List(s *capnp.Segment, sz int32) (CustomReserved14_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved14](l), err
}

// CustomReserved14_Future is a wrapper for a CustomReserved14 promised by a client call.
type CustomReserved14_Future struct{ *capnp.Future }

func (f CustomReserved14_Future) Struct() (CustomReserved14, error) {
	p, err := f.Future.Ptr()
	return CustomReserved14(p.Struct()), err
}

type CustomReserved15 capnp.Struct

// CustomReserved15_TypeID is the unique identifier for the type CustomReserved15.
const CustomReserved15_TypeID = 0xbd443b539493bc68

func NewCustomReserved15(s *capnp.Segment) (CustomReserved15, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved15(st), err
}

func NewRootCustomReserved15(s *capnp.Segment) (CustomReserved15, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved15(st), err
}

func ReadRootCustomReserved15(msg *capnp.Message) (CustomReserved15, error) {
	root, err := msg.Root()
	return CustomReserved15(root.Struct()), err
}

func (s CustomReserved15) String() string {
	str, _ := text.Marshal(0xbd443b539493bc68, capnp.Struct(s))
	return str
}

func (s CustomReserved15) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved15) DecodeFromPtr(p capnp.Ptr) CustomReserved15 {
	return CustomReserved15(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved15) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved15) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved15) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved15) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved15_List is a list of CustomReserved15.
type CustomReserved15_List = capnp.StructList[CustomReserved15]

// NewCustomReserved15 creates a new list of CustomReserved15.
func NewCustomReserved15_List(s *capnp.Segment, sz int32) (CustomReserved15_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved15](l), err
}

// CustomReserved15_Future is a wrapper for a CustomReserved15 promised by a client call.
type CustomReserved15_Future struct{ *capnp.Future }

func (f CustomReserved15_Future) Struct() (CustomReserved15, error) {
	p, err := f.Future.Ptr()
	return CustomReserved15(p.Struct()), err
}

type CustomReserved16 capnp.Struct

// CustomReserved16_TypeID is the unique identifier for the type CustomReserved16.
const CustomReserved16_TypeID = 0xfc6241ed8877b611

func NewCustomReserved16(s *capnp.Segment) (CustomReserved16, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved16(st), err
}

func NewRootCustomReserved16(s *capnp.Segment) (CustomReserved16, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved16(st), err
}

func ReadRootCustomReserved16(msg *capnp.Message) (CustomReserved16, error) {
	root, err := msg.Root()
	return CustomReserved16(root.Struct()), err
}

func (s CustomReserved16) String() string {
	str, _ := text.Marshal(0xfc6241ed8877b611, capnp.Struct(s))
	return str
}

func (s CustomReserved16) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved16) DecodeFromPtr(p capnp.Ptr) CustomReserved16 {
	return CustomReserved16(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved16) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved16) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved16) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved16) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved16_List is a list of CustomReserved16.
type CustomReserved16_List = capnp.StructList[CustomReserved16]

// NewCustomReserved16 creates a new list of CustomReserved16.
func NewCustomReserved16_List(s *capnp.Segment, sz int32) (CustomReserved16_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved16](l), err
}

// CustomReserved16_Future is a wrapper for a CustomReserved16 promised by a client call.
type CustomReserved16_Future struct{ *capnp.Future }

func (f CustomReserved16_Future) Struct() (CustomReserved16, error) {
	p, err := f.Future.Ptr()
	return CustomReserved16(p.Struct()), err
}

type MapdDownloadLocationDetails capnp.Struct

// MapdDownloadLocationDetails_TypeID is the unique identifier for the type MapdDownloadLocationDetails.
const MapdDownloadLocationDetails_TypeID = 0xff889853e7b0987f

func NewMapdDownloadLocationDetails(s *capnp.Segment) (MapdDownloadLocationDetails, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdDownloadLocationDetails(st), err
}

func NewRootMapdDownloadLocationDetails(s *capnp.Segment) (MapdDownloadLocationDetails, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdDownloadLocationDetails(st), err
}

func ReadRootMapdDownloadLocationDetails(msg *capnp.Message) (MapdDownloadLocationDetails, error) {
	root, err := msg.Root()
	return MapdDownloadLocationDetails(root.Struct()), err
}

func (s MapdDownloadLocationDetails) String() string {
	str, _ := text.Marshal(0xff889853e7b0987f, capnp.Struct(s))
	return str
}

func (s MapdDownloadLocationDetails) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdDownloadLocationDetails) DecodeFromPtr(p capnp.Ptr) MapdDownloadLocationDetails {
	return MapdDownloadLocationDetails(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdDownloadLocationDetails) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdDownloadLocationDetails) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdDownloadLocationDetails) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdDownloadLocationDetails) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdDownloadLocationDetails) Location() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MapdDownloadLocationDetails) HasLocation() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdDownloadLocationDetails) LocationBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MapdDownloadLocationDetails) SetLocation(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s MapdDownloadLocationDetails) TotalFiles() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s MapdDownloadLocationDetails) SetTotalFiles(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s MapdDownloadLocationDetails) DownloadedFiles() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s MapdDownloadLocationDetails) SetDownloadedFiles(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

// MapdDownloadLocationDetails_List is a list of MapdDownloadLocationDetails.
type MapdDownloadLocationDetails_List = capnp.StructList[MapdDownloadLocationDetails]

// NewMapdDownloadLocationDetails creates a new list of MapdDownloadLocationDetails.
func NewMapdDownloadLocationDetails_List(s *capnp.Segment, sz int32) (MapdDownloadLocationDetails_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[MapdDownloadLocationDetails](l), err
}

// MapdDownloadLocationDetails_Future is a wrapper for a MapdDownloadLocationDetails promised by a client call.
type MapdDownloadLocationDetails_Future struct{ *capnp.Future }

func (f MapdDownloadLocationDetails_Future) Struct() (MapdDownloadLocationDetails, error) {
	p, err := f.Future.Ptr()
	return MapdDownloadLocationDetails(p.Struct()), err
}

type MapdDownloadProgress capnp.Struct

// MapdDownloadProgress_TypeID is the unique identifier for the type MapdDownloadProgress.
const MapdDownloadProgress_TypeID = 0xfaa35dcac85073a2

func NewMapdDownloadProgress(s *capnp.Segment) (MapdDownloadProgress, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return MapdDownloadProgress(st), err
}

func NewRootMapdDownloadProgress(s *capnp.Segment) (MapdDownloadProgress, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return MapdDownloadProgress(st), err
}

func ReadRootMapdDownloadProgress(msg *capnp.Message) (MapdDownloadProgress, error) {
	root, err := msg.Root()
	return MapdDownloadProgress(root.Struct()), err
}

func (s MapdDownloadProgress) String() string {
	str, _ := text.Marshal(0xfaa35dcac85073a2, capnp.Struct(s))
	return str
}

func (s MapdDownloadProgress) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdDownloadProgress) DecodeFromPtr(p capnp.Ptr) MapdDownloadProgress {
	return MapdDownloadProgress(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdDownloadProgress) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdDownloadProgress) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdDownloadProgress) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdDownloadProgress) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdDownloadProgress) Active() bool {
	return capnp.Struct(s).Bit(0)
}

func (s MapdDownloadProgress) SetActive(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s MapdDownloadProgress) Cancelled() bool {
	return capnp.Struct(s).Bit(1)
}

func (s MapdDownloadProgress) SetCancelled(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

func (s MapdDownloadProgress) TotalFiles() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s MapdDownloadProgress) SetTotalFiles(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s MapdDownloadProgress) DownloadedFiles() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s MapdDownloadProgress) SetDownloadedFiles(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s MapdDownloadProgress) Locations() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s MapdDownloadProgress) HasLocations() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdDownloadProgress) SetLocations(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewLocations sets the locations field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s MapdDownloadProgress) NewLocations(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s MapdDownloadProgress) LocationDetails() (MapdDownloadLocationDetails_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return MapdDownloadLocationDetails_List(p.List()), err
}

func (s MapdDownloadProgress) HasLocationDetails() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s MapdDownloadProgress) SetLocationDetails(v MapdDownloadLocationDetails_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewLocationDetails sets the locationDetails field to a newly
// allocated MapdDownloadLocationDetails_List, preferring placement in s's segment.
func (s MapdDownloadProgress) NewLocationDetails(n int32) (MapdDownloadLocationDetails_List, error) {
	l, err := NewMapdDownloadLocationDetails_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return MapdDownloadLocationDetails_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// MapdDownloadProgress_List is a list of MapdDownloadProgress.
type MapdDownloadProgress_List = capnp.StructList[MapdDownloadProgress]

// NewMapdDownloadProgress creates a new list of MapdDownloadProgress.
func NewMapdDownloadProgress_List(s *capnp.Segment, sz int32) (MapdDownloadProgress_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2}, sz)
	return capnp.StructList[MapdDownloadProgress](l), err
}

// MapdDownloadProgress_Future is a wrapper for a MapdDownloadProgress promised by a client call.
type MapdDownloadProgress_Future struct{ *capnp.Future }

func (f MapdDownloadProgress_Future) Struct() (MapdDownloadProgress, error) {
	p, err := f.Future.Ptr()
	return MapdDownloadProgress(p.Struct()), err
}

type MapdPathPoint capnp.Struct

// MapdPathPoint_TypeID is the unique identifier for the type MapdPathPoint.
const MapdPathPoint_TypeID = 0xd6f78acca1bc3939

func NewMapdPathPoint(s *capnp.Segment) (MapdPathPoint, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return MapdPathPoint(st), err
}

func NewRootMapdPathPoint(s *capnp.Segment) (MapdPathPoint, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return MapdPathPoint(st), err
}

func ReadRootMapdPathPoint(msg *capnp.Message) (MapdPathPoint, error) {
	root, err := msg.Root()
	return MapdPathPoint(root.Struct()), err
}

func (s MapdPathPoint) String() string {
	str, _ := text.Marshal(0xd6f78acca1bc3939, capnp.Struct(s))
	return str
}

func (s MapdPathPoint) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdPathPoint) DecodeFromPtr(p capnp.Ptr) MapdPathPoint {
	return MapdPathPoint(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdPathPoint) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdPathPoint) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdPathPoint) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdPathPoint) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdPathPoint) Latitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s MapdPathPoint) SetLatitude(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s MapdPathPoint) Longitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s MapdPathPoint) SetLongitude(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s MapdPathPoint) Curvature() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(16))
}

func (s MapdPathPoint) SetCurvature(v float32) {
	capnp.Struct(s).SetUint32(16, math.Float32bits(v))
}

func (s MapdPathPoint) TargetVelocity() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(20))
}

func (s MapdPathPoint) SetTargetVelocity(v float32) {
	capnp.Struct(s).SetUint32(20, math.Float32bits(v))
}

// MapdPathPoint_List is a list of MapdPathPoint.
type MapdPathPoint_List = capnp.StructList[MapdPathPoint]

// NewMapdPathPoint creates a new list of MapdPathPoint.
func NewMapdPathPoint_List(s *capnp.Segment, sz int32) (MapdPathPoint_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0}, sz)
	return capnp.StructList[MapdPathPoint](l), err
}

// MapdPathPoint_Future is a wrapper for a MapdPathPoint promised by a client call.
type MapdPathPoint_Future struct{ *capnp.Future }

func (f MapdPathPoint_Future) Struct() (MapdPathPoint, error) {
	p, err := f.Future.Ptr()
	return MapdPathPoint(p.Struct()), err
}

type MapdExtendedOut capnp.Struct

// MapdExtendedOut_TypeID is the unique identifier for the type MapdExtendedOut.
const MapdExtendedOut_TypeID = 0xa30662f84033036c

func NewMapdExtendedOut(s *capnp.Segment) (MapdExtendedOut, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return MapdExtendedOut(st), err
}

func NewRootMapdExtendedOut(s *capnp.Segment) (MapdExtendedOut, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return MapdExtendedOut(st), err
}

func ReadRootMapdExtendedOut(msg *capnp.Message) (MapdExtendedOut, error) {
	root, err := msg.Root()
	return MapdExtendedOut(root.Struct()), err
}

func (s MapdExtendedOut) String() string {
	str, _ := text.Marshal(0xa30662f84033036c, capnp.Struct(s))
	return str
}

func (s MapdExtendedOut) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdExtendedOut) DecodeFromPtr(p capnp.Ptr) MapdExtendedOut {
	return MapdExtendedOut(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdExtendedOut) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdExtendedOut) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdExtendedOut) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdExtendedOut) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdExtendedOut) DownloadProgress() (MapdDownloadProgress, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return MapdDownloadProgress(p.Struct()), err
}

func (s MapdExtendedOut) HasDownloadProgress() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdExtendedOut) SetDownloadProgress(v MapdDownloadProgress) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewDownloadProgress sets the downloadProgress field to a newly
// allocated MapdDownloadProgress struct, preferring placement in s's segment.
func (s MapdExtendedOut) NewDownloadProgress() (MapdDownloadProgress, error) {
	ss, err := NewMapdDownloadProgress(capnp.Struct(s).Segment())
	if err != nil {
		return MapdDownloadProgress{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s MapdExtendedOut) Settings() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s MapdExtendedOut) HasSettings() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s MapdExtendedOut) SettingsBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s MapdExtendedOut) SetSettings(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s MapdExtendedOut) Path() (MapdPathPoint_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return MapdPathPoint_List(p.List()), err
}

func (s MapdExtendedOut) HasPath() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s MapdExtendedOut) SetPath(v MapdPathPoint_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewPath sets the path field to a newly
// allocated MapdPathPoint_List, preferring placement in s's segment.
func (s MapdExtendedOut) NewPath(n int32) (MapdPathPoint_List, error) {
	l, err := NewMapdPathPoint_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return MapdPathPoint_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}

// MapdExtendedOut_List is a list of MapdExtendedOut.
type MapdExtendedOut_List = capnp.StructList[MapdExtendedOut]

// NewMapdExtendedOut creates a new list of MapdExtendedOut.
func NewMapdExtendedOut_List(s *capnp.Segment, sz int32) (MapdExtendedOut_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[MapdExtendedOut](l), err
}

// MapdExtendedOut_Future is a wrapper for a MapdExtendedOut promised by a client call.
type MapdExtendedOut_Future struct{ *capnp.Future }

func (f MapdExtendedOut_Future) Struct() (MapdExtendedOut, error) {
	p, err := f.Future.Ptr()
	return MapdExtendedOut(p.Struct()), err
}
func (p MapdExtendedOut_Future) DownloadProgress() MapdDownloadProgress_Future {
	return MapdDownloadProgress_Future{Future: p.Future.Field(0, nil)}
}

type MapdInputType uint16

// MapdInputType_TypeID is the unique identifier for the type MapdInputType.
const MapdInputType_TypeID = 0x859f26628fc24358

// Values of MapdInputType.
const (
	MapdInputType_download                               MapdInputType = 0
	MapdInputType_setTargetLateralAccel                  MapdInputType = 1
	MapdInputType_setSpeedLimitOffset                    MapdInputType = 2
	MapdInputType_setSpeedLimitControl                   MapdInputType = 3
	MapdInputType_setMapCurveSpeedControl                MapdInputType = 4
	MapdInputType_setVisionCurveSpeedControl             MapdInputType = 5
	MapdInputType_setLogLevel                            MapdInputType = 6
	MapdInputType_setVisionCurveTargetLatA               MapdInputType = 7
	MapdInputType_setVisionCurveMinTargetV               MapdInputType = 8
	MapdInputType_reloadSettings                         MapdInputType = 9
	MapdInputType_saveSettings                           MapdInputType = 10
	MapdInputType_setEnableSpeed                         MapdInputType = 11
	MapdInputType_setVisionCurveUseEnableSpeed           MapdInputType = 12
	MapdInputType_setMapCurveUseEnableSpeed              MapdInputType = 13
	MapdInputType_setSpeedLimitUseEnableSpeed            MapdInputType = 14
	MapdInputType_setHoldLastSeenSpeedLimit              MapdInputType = 15
	MapdInputType_setTargetSpeedJerk                     MapdInputType = 16
	MapdInputType_setTargetSpeedAccel                    MapdInputType = 17
	MapdInputType_setTargetSpeedTimeOffset               MapdInputType = 18
	MapdInputType_setDefaultLaneWidth                    MapdInputType = 19
	MapdInputType_setMapCurveTargetLatA                  MapdInputType = 20
	MapdInputType_loadDefaultSettings                    MapdInputType = 21
	MapdInputType_loadRecommendedSettings                MapdInputType = 22
	MapdInputType_setSlowDownForNextSpeedLimit           MapdInputType = 23
	MapdInputType_setSpeedUpForNextSpeedLimit            MapdInputType = 24
	MapdInputType_setHoldSpeedLimitWhileChangingSetSpeed MapdInputType = 25
	MapdInputType_loadPersistentSettings                 MapdInputType = 26
	MapdInputType_cancelDownload                         MapdInputType = 27
	MapdInputType_setLogJson                             MapdInputType = 28
	MapdInputType_setLogSource                           MapdInputType = 29
	MapdInputType_setExternalSpeedLimitControl           MapdInputType = 30
	MapdInputType_setExternalSpeedLimit                  MapdInputType = 31
	MapdInputType_setSpeedLimitPriority                  MapdInputType = 32
	MapdInputType_setSpeedLimitChangeRequiresAccept      MapdInputType = 33
	MapdInputType_acceptSpeedLimit                       MapdInputType = 34
	MapdInputType_setPressGasToAcceptSpeedLimit          MapdInputType = 35
	MapdInputType_setAdjustSetSpeedToAcceptSpeedLimit    MapdInputType = 36
	MapdInputType_setAcceptSpeedLimitTimeout             MapdInputType = 37
	MapdInputType_setPressGasToOverrideSpeedLimit        MapdInputType = 38
)

// String returns the enum's constant name.
func (c MapdInputType) String() string {
	switch c {
	case MapdInputType_download:
		return "download"
	case MapdInputType_setTargetLateralAccel:
		return "setTargetLateralAccel"
	case MapdInputType_setSpeedLimitOffset:
		return "setSpeedLimitOffset"
	case MapdInputType_setSpeedLimitControl:
		return "setSpeedLimitControl"
	case MapdInputType_setMapCurveSpeedControl:
		return "setMapCurveSpeedControl"
	case MapdInputType_setVisionCurveSpeedControl:
		return "setVisionCurveSpeedControl"
	case MapdInputType_setLogLevel:
		return "setLogLevel"
	case MapdInputType_setVisionCurveTargetLatA:
		return "setVisionCurveTargetLatA"
	case MapdInputType_setVisionCurveMinTargetV:
		return "setVisionCurveMinTargetV"
	case MapdInputType_reloadSettings:
		return "reloadSettings"
	case MapdInputType_saveSettings:
		return "saveSettings"
	case MapdInputType_setEnableSpeed:
		return "setEnableSpeed"
	case MapdInputType_setVisionCurveUseEnableSpeed:
		return "setVisionCurveUseEnableSpeed"
	case MapdInputType_setMapCurveUseEnableSpeed:
		return "setMapCurveUseEnableSpeed"
	case MapdInputType_setSpeedLimitUseEnableSpeed:
		return "setSpeedLimitUseEnableSpeed"
	case MapdInputType_setHoldLastSeenSpeedLimit:
		return "setHoldLastSeenSpeedLimit"
	case MapdInputType_setTargetSpeedJerk:
		return "setTargetSpeedJerk"
	case MapdInputType_setTargetSpeedAccel:
		return "setTargetSpeedAccel"
	case MapdInputType_setTargetSpeedTimeOffset:
		return "setTargetSpeedTimeOffset"
	case MapdInputType_setDefaultLaneWidth:
		return "setDefaultLaneWidth"
	case MapdInputType_setMapCurveTargetLatA:
		return "setMapCurveTargetLatA"
	case MapdInputType_loadDefaultSettings:
		return "loadDefaultSettings"
	case MapdInputType_loadRecommendedSettings:
		return "loadRecommendedSettings"
	case MapdInputType_setSlowDownForNextSpeedLimit:
		return "setSlowDownForNextSpeedLimit"
	case MapdInputType_setSpeedUpForNextSpeedLimit:
		return "setSpeedUpForNextSpeedLimit"
	case MapdInputType_setHoldSpeedLimitWhileChangingSetSpeed:
		return "setHoldSpeedLimitWhileChangingSetSpeed"
	case MapdInputType_loadPersistentSettings:
		return "loadPersistentSettings"
	case MapdInputType_cancelDownload:
		return "cancelDownload"
	case MapdInputType_setLogJson:
		return "setLogJson"
	case MapdInputType_setLogSource:
		return "setLogSource"
	case MapdInputType_setExternalSpeedLimitControl:
		return "setExternalSpeedLimitControl"
	case MapdInputType_setExternalSpeedLimit:
		return "setExternalSpeedLimit"
	case MapdInputType_setSpeedLimitPriority:
		return "setSpeedLimitPriority"
	case MapdInputType_setSpeedLimitChangeRequiresAccept:
		return "setSpeedLimitChangeRequiresAccept"
	case MapdInputType_acceptSpeedLimit:
		return "acceptSpeedLimit"
	case MapdInputType_setPressGasToAcceptSpeedLimit:
		return "setPressGasToAcceptSpeedLimit"
	case MapdInputType_setAdjustSetSpeedToAcceptSpeedLimit:
		return "setAdjustSetSpeedToAcceptSpeedLimit"
	case MapdInputType_setAcceptSpeedLimitTimeout:
		return "setAcceptSpeedLimitTimeout"
	case MapdInputType_setPressGasToOverrideSpeedLimit:
		return "setPressGasToOverrideSpeedLimit"

	default:
		return ""
	}
}

// MapdInputTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func MapdInputTypeFromString(c string) MapdInputType {
	switch c {
	case "download":
		return MapdInputType_download
	case "setTargetLateralAccel":
		return MapdInputType_setTargetLateralAccel
	case "setSpeedLimitOffset":
		return MapdInputType_setSpeedLimitOffset
	case "setSpeedLimitControl":
		return MapdInputType_setSpeedLimitControl
	case "setMapCurveSpeedControl":
		return MapdInputType_setMapCurveSpeedControl
	case "setVisionCurveSpeedControl":
		return MapdInputType_setVisionCurveSpeedControl
	case "setLogLevel":
		return MapdInputType_setLogLevel
	case "setVisionCurveTargetLatA":
		return MapdInputType_setVisionCurveTargetLatA
	case "setVisionCurveMinTargetV":
		return MapdInputType_setVisionCurveMinTargetV
	case "reloadSettings":
		return MapdInputType_reloadSettings
	case "saveSettings":
		return MapdInputType_saveSettings
	case "setEnableSpeed":
		return MapdInputType_setEnableSpeed
	case "setVisionCurveUseEnableSpeed":
		return MapdInputType_setVisionCurveUseEnableSpeed
	case "setMapCurveUseEnableSpeed":
		return MapdInputType_setMapCurveUseEnableSpeed
	case "setSpeedLimitUseEnableSpeed":
		return MapdInputType_setSpeedLimitUseEnableSpeed
	case "setHoldLastSeenSpeedLimit":
		return MapdInputType_setHoldLastSeenSpeedLimit
	case "setTargetSpeedJerk":
		return MapdInputType_setTargetSpeedJerk
	case "setTargetSpeedAccel":
		return MapdInputType_setTargetSpeedAccel
	case "setTargetSpeedTimeOffset":
		return MapdInputType_setTargetSpeedTimeOffset
	case "setDefaultLaneWidth":
		return MapdInputType_setDefaultLaneWidth
	case "setMapCurveTargetLatA":
		return MapdInputType_setMapCurveTargetLatA
	case "loadDefaultSettings":
		return MapdInputType_loadDefaultSettings
	case "loadRecommendedSettings":
		return MapdInputType_loadRecommendedSettings
	case "setSlowDownForNextSpeedLimit":
		return MapdInputType_setSlowDownForNextSpeedLimit
	case "setSpeedUpForNextSpeedLimit":
		return MapdInputType_setSpeedUpForNextSpeedLimit
	case "setHoldSpeedLimitWhileChangingSetSpeed":
		return MapdInputType_setHoldSpeedLimitWhileChangingSetSpeed
	case "loadPersistentSettings":
		return MapdInputType_loadPersistentSettings
	case "cancelDownload":
		return MapdInputType_cancelDownload
	case "setLogJson":
		return MapdInputType_setLogJson
	case "setLogSource":
		return MapdInputType_setLogSource
	case "setExternalSpeedLimitControl":
		return MapdInputType_setExternalSpeedLimitControl
	case "setExternalSpeedLimit":
		return MapdInputType_setExternalSpeedLimit
	case "setSpeedLimitPriority":
		return MapdInputType_setSpeedLimitPriority
	case "setSpeedLimitChangeRequiresAccept":
		return MapdInputType_setSpeedLimitChangeRequiresAccept
	case "acceptSpeedLimit":
		return MapdInputType_acceptSpeedLimit
	case "setPressGasToAcceptSpeedLimit":
		return MapdInputType_setPressGasToAcceptSpeedLimit
	case "setAdjustSetSpeedToAcceptSpeedLimit":
		return MapdInputType_setAdjustSetSpeedToAcceptSpeedLimit
	case "setAcceptSpeedLimitTimeout":
		return MapdInputType_setAcceptSpeedLimitTimeout
	case "setPressGasToOverrideSpeedLimit":
		return MapdInputType_setPressGasToOverrideSpeedLimit

	default:
		return 0
	}
}

type MapdInputType_List = capnp.EnumList[MapdInputType]

func NewMapdInputType_List(s *capnp.Segment, sz int32) (MapdInputType_List, error) {
	return capnp.NewEnumList[MapdInputType](s, sz)
}

type WaySelectionType uint16

// WaySelectionType_TypeID is the unique identifier for the type WaySelectionType.
const WaySelectionType_TypeID = 0xfa3e5ce74e25e82a

// Values of WaySelectionType.
const (
	WaySelectionType_current   WaySelectionType = 0
	WaySelectionType_predicted WaySelectionType = 1
	WaySelectionType_possible  WaySelectionType = 2
	WaySelectionType_extended  WaySelectionType = 3
	WaySelectionType_fail      WaySelectionType = 4
)

// String returns the enum's constant name.
func (c WaySelectionType) String() string {
	switch c {
	case WaySelectionType_current:
		return "current"
	case WaySelectionType_predicted:
		return "predicted"
	case WaySelectionType_possible:
		return "possible"
	case WaySelectionType_extended:
		return "extended"
	case WaySelectionType_fail:
		return "fail"

	default:
		return ""
	}
}

// WaySelectionTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func WaySelectionTypeFromString(c string) WaySelectionType {
	switch c {
	case "current":
		return WaySelectionType_current
	case "predicted":
		return WaySelectionType_predicted
	case "possible":
		return WaySelectionType_possible
	case "extended":
		return WaySelectionType_extended
	case "fail":
		return WaySelectionType_fail

	default:
		return 0
	}
}

type WaySelectionType_List = capnp.EnumList[WaySelectionType]

func NewWaySelectionType_List(s *capnp.Segment, sz int32) (WaySelectionType_List, error) {
	return capnp.NewEnumList[WaySelectionType](s, sz)
}

type SpeedLimitOffsetType uint16

// SpeedLimitOffsetType_TypeID is the unique identifier for the type SpeedLimitOffsetType.
const SpeedLimitOffsetType_TypeID = 0xa5a3dfadcac04344

// Values of SpeedLimitOffsetType.
const (
	SpeedLimitOffsetType_static  SpeedLimitOffsetType = 0
	SpeedLimitOffsetType_percent SpeedLimitOffsetType = 1
)

// String returns the enum's constant name.
func (c SpeedLimitOffsetType) String() string {
	switch c {
	case SpeedLimitOffsetType_static:
		return "static"
	case SpeedLimitOffsetType_percent:
		return "percent"

	default:
		return ""
	}
}

// SpeedLimitOffsetTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func SpeedLimitOffsetTypeFromString(c string) SpeedLimitOffsetType {
	switch c {
	case "static":
		return SpeedLimitOffsetType_static
	case "percent":
		return SpeedLimitOffsetType_percent

	default:
		return 0
	}
}

type SpeedLimitOffsetType_List = capnp.EnumList[SpeedLimitOffsetType]

func NewSpeedLimitOffsetType_List(s *capnp.Segment, sz int32) (SpeedLimitOffsetType_List, error) {
	return capnp.NewEnumList[SpeedLimitOffsetType](s, sz)
}

type MapdIn capnp.Struct

// MapdIn_TypeID is the unique identifier for the type MapdIn.
const MapdIn_TypeID = 0xc86a3d38d13eb3ef

func NewMapdIn(s *capnp.Segment) (MapdIn, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdIn(st), err
}

func NewRootMapdIn(s *capnp.Segment) (MapdIn, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdIn(st), err
}

func ReadRootMapdIn(msg *capnp.Message) (MapdIn, error) {
	root, err := msg.Root()
	return MapdIn(root.Struct()), err
}

func (s MapdIn) String() string {
	str, _ := text.Marshal(0xc86a3d38d13eb3ef, capnp.Struct(s))
	return str
}

func (s MapdIn) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdIn) DecodeFromPtr(p capnp.Ptr) MapdIn {
	return MapdIn(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdIn) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdIn) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdIn) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdIn) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdIn) Type() MapdInputType {
	return MapdInputType(capnp.Struct(s).Uint16(0))
}

func (s MapdIn) SetType(v MapdInputType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s MapdIn) Float() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s MapdIn) SetFloat(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s MapdIn) Str() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MapdIn) HasStr() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdIn) StrBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MapdIn) SetStr(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s MapdIn) Bool() bool {
	return capnp.Struct(s).Bit(16)
}

func (s MapdIn) SetBool(v bool) {
	capnp.Struct(s).SetBit(16, v)
}

// MapdIn_List is a list of MapdIn.
type MapdIn_List = capnp.StructList[MapdIn]

// NewMapdIn creates a new list of MapdIn.
func NewMapdIn_List(s *capnp.Segment, sz int32) (MapdIn_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[MapdIn](l), err
}

// MapdIn_Future is a wrapper for a MapdIn promised by a client call.
type MapdIn_Future struct{ *capnp.Future }

func (f MapdIn_Future) Struct() (MapdIn, error) {
	p, err := f.Future.Ptr()
	return MapdIn(p.Struct()), err
}

type RoadContext uint16

// RoadContext_TypeID is the unique identifier for the type RoadContext.
const RoadContext_TypeID = 0xabefa88b9563dbae

// Values of RoadContext.
const (
	RoadContext_freeway RoadContext = 0
	RoadContext_city    RoadContext = 1
	RoadContext_unknown RoadContext = 2
)

// String returns the enum's constant name.
func (c RoadContext) String() string {
	switch c {
	case RoadContext_freeway:
		return "freeway"
	case RoadContext_city:
		return "city"
	case RoadContext_unknown:
		return "unknown"

	default:
		return ""
	}
}

// RoadContextFromString returns the enum value with a name,
// or the zero value if there's no such value.
func RoadContextFromString(c string) RoadContext {
	switch c {
	case "freeway":
		return RoadContext_freeway
	case "city":
		return RoadContext_city
	case "unknown":
		return RoadContext_unknown

	default:
		return 0
	}
}

type RoadContext_List = capnp.EnumList[RoadContext]

func NewRoadContext_List(s *capnp.Segment, sz int32) (RoadContext_List, error) {
	return capnp.NewEnumList[RoadContext](s, sz)
}

type HighwayClass uint16

// HighwayClass_TypeID is the unique identifier for the type HighwayClass.
const HighwayClass_TypeID = 0xd18274dcdc63c41d

// Values of HighwayClass.
const (
	HighwayClass_unknown       HighwayClass = 0
	HighwayClass_motorway      HighwayClass = 1
	HighwayClass_motorwayLink  HighwayClass = 2
	HighwayClass_trunk         HighwayClass = 3
	HighwayClass_trunkLink     HighwayClass = 4
	HighwayClass_primary       HighwayClass = 5
	HighwayClass_primaryLink   HighwayClass = 6
	HighwayClass_secondary     HighwayClass = 7
	HighwayClass_secondaryLink HighwayClass = 8
	HighwayClass_tertiary      HighwayClass = 9
	HighwayClass_tertiaryLink  HighwayClass = 10
	HighwayClass_unclassified  HighwayClass = 11
	HighwayClass_residential   HighwayClass = 12
	HighwayClass_livingStreet  HighwayClass = 13
)

// String returns the enum's constant name.
func (c HighwayClass) String() string {
	switch c {
	case HighwayClass_unknown:
		return "unknown"
	case HighwayClass_motorway:
		return "motorway"
	case HighwayClass_motorwayLink:
		return "motorwayLink"
	case HighwayClass_trunk:
		return "trunk"
	case HighwayClass_trunkLink:
		return "trunkLink"
	case HighwayClass_primary:
		return "primary"
	case HighwayClass_primaryLink:
		return "primaryLink"
	case HighwayClass_secondary:
		return "secondary"
	case HighwayClass_secondaryLink:
		return "secondaryLink"
	case HighwayClass_tertiary:
		return "tertiary"
	case HighwayClass_tertiaryLink:
		return "tertiaryLink"
	case HighwayClass_unclassified:
		return "unclassified"
	case HighwayClass_residential:
		return "residential"
	case HighwayClass_livingStreet:
		return "livingStreet"

	default:
		return ""
	}
}

// HighwayClassFromString returns the enum value with a name,
// or the zero value if there's no such value.
func HighwayClassFromString(c string) HighwayClass {
	switch c {
	case "unknown":
		return HighwayClass_unknown
	case "motorway":
		return HighwayClass_motorway
	case "motorwayLink":
		return HighwayClass_motorwayLink
	case "trunk":
		return HighwayClass_trunk
	case "trunkLink":
		return HighwayClass_trunkLink
	case "primary":
		return HighwayClass_primary
	case "primaryLink":
		return HighwayClass_primaryLink
	case "secondary":
		return HighwayClass_secondary
	case "secondaryLink":
		return HighwayClass_secondaryLink
	case "tertiary":
		return HighwayClass_tertiary
	case "tertiaryLink":
		return HighwayClass_tertiaryLink
	case "unclassified":
		return HighwayClass_unclassified
	case "residential":
		return HighwayClass_residential
	case "livingStreet":
		return HighwayClass_livingStreet

	default:
		return 0
	}
}

type HighwayClass_List = capnp.EnumList[HighwayClass]

func NewHighwayClass_List(s *capnp.Segment, sz int32) (HighwayClass_List, error) {
	return capnp.NewEnumList[HighwayClass](s, sz)
}

type MapdOut capnp.Struct

// MapdOut_TypeID is the unique identifier for the type MapdOut.
const MapdOut_TypeID = 0xa4f1eb3323f5f582

func NewMapdOut(s *capnp.Segment) (MapdOut, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 5})
	return MapdOut(st), err
}

func NewRootMapdOut(s *capnp.Segment) (MapdOut, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 5})
	return MapdOut(st), err
}

func ReadRootMapdOut(msg *capnp.Message) (MapdOut, error) {
	root, err := msg.Root()
	return MapdOut(root.Struct()), err
}

func (s MapdOut) String() string {
	str, _ := text.Marshal(0xa4f1eb3323f5f582, capnp.Struct(s))
	return str
}

func (s MapdOut) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdOut) DecodeFromPtr(p capnp.Ptr) MapdOut {
	return MapdOut(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdOut) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdOut) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdOut) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdOut) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdOut) WayName() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MapdOut) HasWayName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdOut) WayNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MapdOut) SetWayName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s MapdOut) WayRef() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s MapdOut) HasWayRef() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s MapdOut) WayRefBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s MapdOut) SetWayRef(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s MapdOut) RoadName() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s MapdOut) HasRoadName() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s MapdOut) RoadNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s MapdOut) SetRoadName(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s MapdOut) SpeedLimit() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(0))
}

func (s MapdOut) SetSpeedLimit(v float32) {
	capnp.Struct(s).SetUint32(0, math.Float32bits(v))
}

func (s MapdOut) NextSpeedLimit() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s MapdOut) SetNextSpeedLimit(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s MapdOut) NextSpeedLimitDistance() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(8))
}

func (s MapdOut) SetNextSpeedLimitDistance(v float32) {
	capnp.Struct(s).SetUint32(8, math.Float32bits(v))
}

func (s MapdOut) Hazard() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s MapdOut) HasHazard() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s MapdOut) HazardBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s MapdOut) SetHazard(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s MapdOut) NextHazard() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s MapdOut) HasNextHazard() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s MapdOut) NextHazardBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s MapdOut) SetNextHazard(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s MapdOut) NextHazardDistance() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(12))
}

func (s MapdOut) SetNextHazardDistance(v float32) {
	capnp.Struct(s).SetUint32(12, math.Float32bits(v))
}

func (s MapdOut) AdvisorySpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(16))
}

func (s MapdOut) SetAdvisorySpeed(v float32) {
	capnp.Struct(s).SetUint32(16, math.Float32bits(v))
}

func (s MapdOut) NextAdvisorySpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(20))
}

func (s MapdOut) SetNextAdvisorySpeed(v float32) {
	capnp.Struct(s).SetUint32(20, math.Float32bits(v))
}

func (s MapdOut) NextAdvisorySpeedDistance() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(24))
}

func (s MapdOut) SetNextAdvisorySpeedDistance(v float32) {
	capnp.Struct(s).SetUint32(24, math.Float32bits(v))
}

func (s MapdOut) OneWay() bool {
	return capnp.Struct(s).Bit(224)
}

func (s MapdOut) SetOneWay(v bool) {
	capnp.Struct(s).SetBit(224, v)
}

func (s MapdOut) Lanes() uint8 {
	return capnp.Struct(s).Uint8(29)
}

func (s MapdOut) SetLanes(v uint8) {
	capnp.Struct(s).SetUint8(29, v)
}

func (s MapdOut) TileLoaded() bool {
	return capnp.Struct(s).Bit(225)
}

func (s MapdOut) SetTileLoaded(v bool) {
	capnp.Struct(s).SetBit(225, v)
}

func (s MapdOut) SpeedLimitSuggestedSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(32))
}

func (s MapdOut) SetSpeedLimitSuggestedSpeed(v float32) {
	capnp.Struct(s).SetUint32(32, math.Float32bits(v))
}

func (s MapdOut) SuggestedSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(36))
}

func (s MapdOut) SetSuggestedSpeed(v float32) {
	capnp.Struct(s).SetUint32(36, math.Float32bits(v))
}

func (s MapdOut) EstimatedRoadWidth() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(40))
}

func (s MapdOut) SetEstimatedRoadWidth(v float32) {
	capnp.Struct(s).SetUint32(40, math.Float32bits(v))
}

func (s MapdOut) RoadContext() RoadContext {
	return RoadContext(capnp.Struct(s).Uint16(30))
}

func (s MapdOut) SetRoadContext(v RoadContext) {
	capnp.Struct(s).SetUint16(30, uint16(v))
}

func (s MapdOut) DistanceFromWayCenter() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(44))
}

func (s MapdOut) SetDistanceFromWayCenter(v float32) {
	capnp.Struct(s).SetUint32(44, math.Float32bits(v))
}

func (s MapdOut) VisionCurveSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(48))
}

func (s MapdOut) SetVisionCurveSpeed(v float32) {
	capnp.Struct(s).SetUint32(48, math.Float32bits(v))
}

func (s MapdOut) MapCurveSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(52))
}

func (s MapdOut) SetMapCurveSpeed(v float32) {
	capnp.Struct(s).SetUint32(52, math.Float32bits(v))
}

func (s MapdOut) WaySelectionType() WaySelectionType {
	return WaySelectionType(capnp.Struct(s).Uint16(56))
}

func (s MapdOut) SetWaySelectionType(v WaySelectionType) {
	capnp.Struct(s).SetUint16(56, uint16(v))
}

func (s MapdOut) SpeedLimitAccepted() bool {
	return capnp.Struct(s).Bit(226)
}

func (s MapdOut) SetSpeedLimitAccepted(v bool) {
	capnp.Struct(s).SetBit(226, v)
}

func (s MapdOut) HighwayClass() HighwayClass {
	return HighwayClass(capnp.Struct(s).Uint16(58))
}

func (s MapdOut) SetHighwayClass(v HighwayClass) {
	capnp.Struct(s).SetUint16(58, uint16(v))
}

// MapdOut_List is a list of MapdOut.
type MapdOut_List = capnp.StructList[MapdOut]

// NewMapdOut creates a new list of MapdOut.
func NewMapdOut_List(s *capnp.Segment, sz int32) (MapdOut_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 64, PointerCount: 5}, sz)
	return capnp.StructList[MapdOut](l), err
}

// MapdOut_Future is a wrapper for a MapdOut promised by a client call.
type MapdOut_Future struct{ *capnp.Future }

func (f MapdOut_Future) Struct() (MapdOut, error) {
	p, err := f.Future.Ptr()
	return MapdOut(p.Struct()), err
}

const schema_b526ba661d550a59 = "x\xda\x94X}\x8c\x15\xd7u?g\xee\xbe}\xfb\xf6" +
	"\x83\xf7f\xef`C\xec\xed\xdaNl\xd5Vh\x8c\xd7" +
	"4\x86\x94,\xb0\x1b\x0a\xab\x87\xd9\xb7\xb3x\xc3\x0a$" +
	"f\xdf\xdc\xdd\x1d\x98\x9dy\xcc\xdc\xb7\xcbCEK\xa9" +
	"#\xd9\xb4Q\xd4\xd6\x8eLd\x948\x18\xc9n\x83q" +
	"S\xa8\x1cd\xab\x11\xb2%\x96f%\x88J%\x1c," +
	"\x1bK\x11\x906J\xd2\x1a\xb5\xa4\xb6\xa6:w\xde\xd7" +
	"\xc2k\xc8\xfe\xb3\xf3\xe6w~\xf7\xdcs\xce=s\xce" +
	"=\xfb\xb8l^\xd7\xb4\xb2#\xd9\x06Z\xee`\xa29" +
	"\xd2\xf7l\xff\xd8\x93o\x1c\x04\xfd>\x8c\xb6\xb7n\xeb" +
	"\x1a?\xf3\xc8ihJ\x02\xf48\x89Q\xe4\x07\x12I" +
	"`\xd1\xc9O\xb2\xabG\x7f}\xf6\xcf\x1b\xb0\xb6\x13k" +
	"J\xb1\xbe\xdew\xf6[c\x8f|\xf7\x1b\xa0\xdf\xa7\xd5" +
	"X\x80=\x9b\x13\x03\xc8w&b\xfaI\x06\x18u\x9e" +
	"\xc2\x89\x89s\xf3/7P\xb845\x86\xfc\xd1\x14)" +
	"\\\xf1\xb3n\xd6\x9f\x9c|\xa5\x01+\x91\x1aE\xbe\\" +
	"\xb1\\\xd6\xb3\xee\x7f\xc6\x9a\x8f-d%\x18\xd1n\xb6" +
	"\x8c\"O\xa5\x92\x00<\x91:\x09\x18\x1d\xbay\xf3\xf3" +
	"=\xff\xfe\x9bW!w\x1f\xb6\xd4\xb1\x95q?J}" +
	"\x0e\xf9\x1c\xb1{\xdeK\xcd&\x00\xa3\xfe\xbe\x1f\x9f?" +
	"\xf1\xe1\xb1\xe3w\xb8\x94\xc8\x1cB\xbe<C\x8a\x97f" +
	"\xbe\x0c\x18m{5w\xf9\x8b\xd3\xf3\xc7\x1b\xd8\xba<" +
	"3\x8a|E\x86l}\xe3g\xf9\x17\xff\xf2\xb5_\xfd" +
	"\xfd\x1d\xfaR\x9955}[\x01\xa3\x9d\xa7\xaf\xad\xfc" +
	"\xd6g\x1f\xbe\xd1@\xdf\xa3\xa4o\xad\xd2\xd7\xfb\xe1/" +
	"\x0ely`\xe4\xcd\x86\xbb\x8eUv=\x87\xd9\x07\x9d" +
	"\xbc\xf7V\x03V\x8atu)\xd6\xe4\xdb\x7f\xfb\x82\xf9" +
	"\x95\xfew\x1a\xb0n\xa5\xc7\x90w(\xd6\xb3\xec\xc9\x8f" +
	"\xc4\x9f|\xe1l\x03\xd6\x0db}\x96&\xd6\xaf\xfe\xf1" +
	"\xab\x17\x9fZ\xbb\xfb\x1c\x85\xb9\xfeP\x90x\x97\xd3\x9d" +
	"\xc8o\xa4\xc9\xd7\x9f\xa7\xaf\x01Fk\xb6\x8f\x14\xdcK" +
	"\xdf\xfd\x97\x06:\x7fD^\xcc\xab\x9d/\x1c\xfa\xde\xc4" +
	"\xff\xbe\xff\xed\xf9\x06\xac\xd7\x89\xf5\x8ebu\xbd\x9b\xbf" +
	"rE\x1e\xbaxG\x84\x8fd6 \x7f\x9d\"\xdcs" +
	"<3\x82\x80\xd1\xea\xd5o\xbf\xf2\x93\xc3\xff\xfdod" +
	"$\xbbM\xe3\x8b\xfa\x00\xf2\xd7u\xb2\xf1\xb8N6\xae" +
	"\xca\xf6\xff\xc5K#\xdf~\xbf\xc1\xee\xcfw\x8e\"?" +
	"\xdaI\xbb\x9f\xf5\xfe\xb9\xed\x99ww\xfcW\x03V\x89" +
	"X\xdfT\xac\xe5G\x8fnN\xfd\xc7=\x9f4\xfa\xe8" +
	"\x88u@\xb1\x8e5\x15>\xfb\xca\xb3\xdf\xbc\xd5\xe8\xa3" +
	"#\xd6\x94b=v\xfd\xe1\xa7\xaf\xed\xf8\xeao\xef\xfc" +
	"\xe8:\xc7\x90\xef\xec$\x0f\xb6w\xce\x02F\xdf\x0f\x07" +
	"\xcf\x9d\xdfy\xec\xb7\xe4n\x1d5\xa1\x91\xc6#\x9d\x87" +
	"\x90\x9f\xe8T\xc1\xecT\xd1\xd1\xffi\xe6\xb9_\xae\x1f" +
	"\xfb\xb4Q\x02\x1ac\xc8\xd7\x1a\xb4\xfd\xecKo^3" +
	"_z.jx\xd0\xcb\x8d3\xc8W\x1ad\xc2\x0a\xe3" +
	"$\xac\x88\xf2\"\x10\x96\xfb\xa5|S1\x94\xfe\xd4\x97" +
	"\xf2\xea\xf1Gy\xab\xe0\x15\xd6\xf4\xa9\x97!\x11\x8a`" +
	"Z0\xfb\xc9A\xc4\xc5\xf0\x1f\xbf\x1b\x7f\x8bU\xb07" +
	"{\x85\xa2\x1c.\x15\x04\xc0 b\xeee\xd4\x00\xf8<" +
	"\x0e\x00 \xf29\xfc!\x00j|\x0e\xbf\x0f\x80\x8c\xcf" +
	"\xe1\xdf\x01`\x13\x9f\xc3\xb3\x00\x98\xe0s\xf8>\x006" +
	"\xf3y\x1c\x03\xc0$\x9f\xc3\xf3\x00\xd8\xc2\xe7\xd53\xc5" +
	"/\xe2~\x00l\xe5\xf3\xb8\x1b\x00\xdb\xf8\x9czo\xe7" +
	"\xef\xe1/\x00\xb0\x83\xcf\xe1O\x01p\x09\x9f\xc7\x8f\x01" +
	"0\xcd/\xaa\xf7\x0c\xbf\x84\xdf\x01@\x9d_R\xfbv" +
	"\xf2KJ\x1f\xe7\x97\xd5\xbb\xc1/+\xbb\x96\x96\xdf\xef" +
	"\xe1\x97\x95=\xf7\xf2\xcbJ\xef2\xfe\x81\xd2\xb7\xbc\xe7" +
	"*\xaeA\x00\xfc\x1c\xbf\x81g\x00\xf0>~C\x19p" +
	"?\xff9\x8e\x02`\x17\xbf\xaa\x0c\xfb\x03\xfe\x81Z\xd8" +
	"\xcd\xaf*\xc5\x0f\x94\x9f\x0f\xf6\\\xc5NR\xf0\x10\xbf" +
	"\x81\x87\x01\xf0\xf3\xfc\x06\xfe'\x00~\xa1\xe7\x97\xf8\x10" +
	"\x09\x1e\xe67U\x08\x1e\xe9\xb9\x85\x1a\x02D\xb6?\xe3" +
	"\xb9\xbee\x03@\x14\x0a9l\x05\x13\x02e\xd6\x92\"" +
	"\xb0\xdc\xee\xf5\xf9\xbcp\x097\x0bB\xd8\x98u\xa6\x1c" +
	"\xb9u|<\x19\x0ay\x1b\xda\xe7{i\x19\xf8\x8a\xbc" +
	"\xc5*\xf4\x15\x13\xc1\xb4P\xf2>\xdf#\x01\x84B>" +
	"\xe3\x84\x8e\xef\xf5\x15\x17\x88X\xbc(\xebOd\x05$" +
	"\xa7\xe3\xfd\x14S\x8b\xa9\xca&2i}lc\xbdl" +
	"\x8b\xe3\xc5\xe2g\x00\xa2@\x90'\xa6\x80^)\x1do" +
	"\"\x8cBkZ\x98BJH\xc7\xafB~\xcd\xb3\xc6" +
	"\\\xe8\x8d\xb7\xbf]\xd9\xb6P(\xb90\xd3\x15\xb1r" +
	"E[ +\x08\x81v\xd5{My_'M\x96W" +
	"n\xf2];\xabY\xa14\x85\xf0\x14\x95\x98(\xeb\xa2" +
	"\xac\xd0\x01\xc1\x82=\xb7\x83\xeb\xf3\xc9r\xe0\x15\xaa\xc5" +
	"\xe8\xb03%\xb6\x8e\x8f\x87B\xc6\x81\xe8\x17\xe3V\x11" +
	"]\x99\xb5<1\xe2$m9Y5\x19+q\xebV" +
	"\x81\x8b(0D\xc7\xa2+)\"N\x92\x02B\xe8\x90" +
	"\xc8\xfb\x89\xa9)\xe1\xd9\xc2V\x12o\"\xa4\xb32]" +
	"\x7f\xa6\xdf\x9f\xf16\xfa\xc1\xd3b_l@6M\xce" +
	"\xd6|\xdfVX u\x92e)\xf9n\xb2\x8a\xcfr" +
	"d\xd2qE\xdf\xa4\xe5M8\xde\x84)zc\xba\xda" +
	"}P\x04!:\xa1\x14\x9e$A|ly\xcb\xcb\x0b" +
	"\xb7\xdf\x87\xde87\xcb\xe91\x10\x02\xf3\xbd\xf2\x8b\xe9" +
	"C\xba\x18\xe4\x85:\xd4}R\x04\x9ag\xb9\xd50/" +
	"HG%\xc6\x8a\xb8;\xbb\xc0\x878{\x07\x03\xa7\xdb" +
	"\x0f\x1cY\xaa\xe2,VCF\x8b!\xb1\xb7\xe8\x04\"" +
	"\xa4\xaf\xa1\x802\xb2\xe8)\xcd\x02Vv\x8b\x8fc0" +
	"\x10a\xa8\xfd\xa9\x15\x0e\xfb\xeb\xcb\x8c\x05\xfb\xad\xb7w" +
	"\x17CF\xe1\x8fO\xb3\x9eU\x8b\x9d\x025Ys\x85" +
	"N\xddgEY\xdd\xa2Em\xb1uZ\x04\x81c\x8b" +
	"\x1a\x11*\xa5\xf3n\x956i\xaf|b\x91\xa5y\xf5" +
	"\xefS\x9a)\xd0\x94F[YQRmngM\x00" +
	"M\x08\xa0\x7f\xed0@n\x13\xc3\xdc\xb0\x86:\xa2\x81" +
	"\x04\xe6\x06\x00r\x83\x0cs;4\xd45\xcd\xa0J\xae" +
	"o\x7f\x0c 7\xcc0W\xd0\xb0Z\x9cp0\xf0'" +
	"\xc8u*\xb6\xb5&\x08\x88\x19@\x8aK\x9c\xb5T\xaa" +
	"A\xc3v\xc0t\xc1\x92\x93\xb8\x04p\x90!fj\xb7" +
	"\x04@\x02\xab\x8e\xb0\xff\xc7\x91\x8a\x03v\xc5\x01~B" +
	"\xdb\x00`\xbe\xa614Oi5\x1f\xf8?hk\x00" +
	"\xcc\x1f\x10\xfe\x96Vs\x83\x9f\xd6\x06\x00\xccS\x84\xff" +
	"X\xd3\x10\x99\x81\x0c\x80\xbf\xa3\x8d\x02\x98o\x13|\x8e" +
	"\xe8Mh`\x13\x00\x7fO\xdb\x0f`\xbeK\xf8\x05\xc2" +
	"\x13\x9a\x81\x09\xeak\xda\x19\x00\xf3\x02\xe1W\x08of" +
	"\x066\x03\xf0\xcbj\xdb\x7f%\xfc#\xc2\x93M\x06u" +
	"k\xfe\x81\xd2\x7f\x85\xf0\xeb\x84\xb70\x03[\xe8\x8e\xa6" +
	"}\x07\xc0\xbcN\xf8'\x84\xa7\x9a\x0cL\x01\xf0\xdfh" +
	"\x01\x80\xf9k\xc2?%\xbc5a`+\x00\xbf\xa5\xfd" +
	"\x0d\x80\xf9)\xe1-LC\xbd\xad\xd9\xc06\xba\x80\xb3" +
	"\x9f\x02\x98\xed\x8c\xa1\xb9\x8c\xf0\xf6\x8f\x0cl\xa7\xfb." +
	"#{2\x84\xdfOxG\x97\x81\x1d\x00|9{\x02" +
	"\xc04\x08\x7f\x80\xf0%W\x0d\\\x02\xc0\xbb\x18\xd9y" +
	"?\xe1\x7fHx\xba\xc5\xc04\x00\x7f\x98\x9d\x070\xbf" +
	"H\xf8S\x84gR\x06f\x00\xf8*F\xf1y\x92\xf0" +
	"u\x84\xeb\xad\x06\xea\x00|-#\xbf\xd6\x11\x9e%\xbc" +
	"3m`'\x00\xdf\xcc\xc6\x00\xccM\x84\x0f\x13\xce\xdb" +
	"\x0c\xe4\x00<\xc7~\x08`\x0e\x13\xbe\x8bp\xa3\xdd@" +
	"\x03\x80\xefd\x87\x01\xcc]\x84\xbb\x84/\xed0p)" +
	"\x00w\x18\xc5g\x92pI\xf8=\xf7\x1bx\x0f\x00\xdf" +
	"\xab\xf8\x92\xf0\x83\x84\xdf\xfb\xb1\x81\xf7\x02\xf0\x03\xca\x9e" +
	"\x83\x84\xff\x15\xe1\xcb\xba\x0c\\\x06\xc0\x9fg\xbb\x01\xcc" +
	"\xe7\x08\x7f\x81i8;c\x95\x9e\xb6\xa6D%]{" +
	"g\xac\xd2\x90\x18\xaf\xbcF\x81o\xd9$\xaf\xcb\xe8(" +
	",\x7f\xe7\xc0\x1c\x89\xad\xa0a+`\xe4\x95k/\xf4" +
	"\xc6%\xe0\x0e\x01\xc6x\xbf\xd3\x1bJ\xaa\xaa\x15B\xef" +
	"\xa4\xb5\xdf\x0a\xec\xaav\xe2o\xb2\xf6[\xc0\x1a\x80\x18" +
	"\xd8\xfd\x0e\xadg5\x05\x91eO;\xa1\x1f\x94\xa0;" +
	"\xae\xa3\xf5;\xaf\xb7\xa7\x1d$al\xc2\x1d2\xad\"" +
	"+\xeb\xcdc\xcd0\xdf\x13#V\x09\x114D\xc0n" +
	"\xd7\xf2D\x88\xcd\xa0a3`$\x1dWd\xe9\xb6\xc2" +
	"\x84]\xa1T#\xa39\xd2,NL\x88P\x0a[)" +
	"\xa7\xab\\y\xe7\xb0,\x80^{\xa1\xb9\"\x94\xce\x94" +
	"%\x05\xdaC\xbee\x8f86\x93\x93U!\x9d\x03\xdd" +
	"Q )\xf6IL\xd7F?@L\x03F\xb6S\x8e" +
	"\xea\xc6\xc0\x9f\x1a\xb1J}\xdd\xc2\xa3^SY?]" +
	"\xbe\xef`\xe5\xc2Sg\xd1\x14\xb5\xe9`Z\xdc\x1e\xbf" +
	"\x19\xabd\x0aW\xe4Q:\xbe\x17\xdfs1]\x1b\x11" +
	"\xca;W|F'n\x18\xb2> \x93\xce\xc4\xe4\x8c" +
	"U\xea\x83\xb4k\x85!\xa6k\x03Uyu\xa5\xfe%" +
	"\x1a\xd4\xbfZ?\x89\xaf\x1a\xca\x04*\x86-\xaa>\xeb" +
	"kH\x89\x9e\xda\x00@)%\x9d\xfclA\x04y\xe1" +
	"\xc9\xc5\xb4\x93U\xf5\xed\xa4Q\x15\xa6\xc3\xe8\xeb\xf5=" +
	")\xf6\xc5\xadDm\xde\xb5Am\xbe\xf41\xba\xe4\xeb" +
	"\x1d\x1b\x00f\xc7\x03!f\xacR:\xef\xc8\xd2l\xd1" +
	"\xdb\xe3\xf93\xdeb,Y\xb9\xa8F\x98\xb4W.v" +
	"\xa8\xf9\xf2b7X\xb5\xd8\x05+\xef\x16L56\xa1" +
	"Gq\xccT[\xb2E\x8dv\x07\xc3\xdcd]K\x16" +
	"O\x00\xe4v1\xcc\xb9\x1ab\xb9#;\x0f\x01\xe4\xec" +
	"\xb8#\xeb,\xa3\x1a\x99>E\xab'\x19\xe6\xa4\x86i" +
	"Y*\x08L\xd7\xfew\x14gY\xf7\xb8\xeb[\xd5\x8a" +
	"\x94\x0ceP\xed\xcec\xbe\xefV\xb3u1\xae>\xbe" +
	"\xd8\xd8\xf4\xdcm\xc1\xa6\xf2\xb7B_\x8aJ\xf3\xa7\x94" +
	"\xd3\xaf\xc4\x99vd@e\xda\x8b4t1\xfd\xaf\x9f" +
	"\xa0aR\x7f~\x88fI\xfd\x1bDi\xd6\x0f\xa8I" +
	"R/\x11\xd8\xa2\x17\x03\x9a#\xf5\xbd\xb4\xaeU\x9fR" +
	"S\xa4\xee\xd0\xa3]\x17\xc4\xec\xd0\xad\xdd\x00\xd5L\x9d" +
	"\xf2\xa5\x1f\xccX%\x1a\xbf\xaa\xbf\xd3Y\xc7\xdb\xd3-" +
	"\x83\xa2\xb7'R\x7f\xb3\x8e\x07\xb8g\xb6\x108SV" +
	"P\x8a\xca\xcf,$\x1d\x8fF\x87\xbc\xef\xd9V\x00X" +
	"\xaa\xfd\xee.\x91\x8eH\x8a@:V\xa0\xd4W\x7f+" +
	"\xf5Q\xd1\xcb\x93\xcf\x0e\xa4\xc7\x1daG\x81\x08\x1d[" +
	"P\xa9s,7r\x9di\xba\xaaKH\x07B\xc8\xbb" +
	"^\xfc\x06-99\xe8;\x9e\x8cg\xf2\xba$\x1b\xa8" +
	"\xe5S5\xc9\x9c\xa1Z\xee\xe8ZS\x9ce{\x09," +
	"0\xcc\xfd\x19eY\"\xce\xb2\xd2~\x80\xdc>\x86\xb9" +
	"g5\x8c\\K:\xb2h\xab\xa6\xd8\x06\x1a\xb6\x01F" +
	"\xae\xefM\x10\x08(\xaaX\xbe\x18L[\xb2\x18@\xad" +
	"\xa9D2\x9e\x11\x05\xf4\xba>U\x8a\xaa`\x11\x1fr" +
	"\xcf\"?\xfc\xc5^\xb1\x9fZ$\xff\x8f\xef\xc6\x1f)" +
	"w\x12\xd5H\x92\xa5\x82\xa0\xb3\x89\xa3\xbd*N\xef\x15" +
	"C*\xbd\x1f\x1dP\xe9\xfd\xf0\x80J\xef\x07\x1f\x03\x98" +
	"\xcd\x17\x83\x80jz!\x10\xb6\x93\x97\x02\xd0\x8e\x0a~" +
	"\x18:c.\x1d@$\xcaW}\x00H\x8f[\x8e\xfb" +
	";[\x0a\xa5H\x7f\xf9*_\xbd\xc9\x931\xcb\xaa\x89" +
	"rd\x0d@\xee\x05\x86\xb9\xef\xd5%\xcaQ\xca\x89\x97" +
	"\x19\xe6^\xa3D\xc1\xd8\xf4\xe3\xa3\x00\xb9W\x19\xe6\xde" +
	"\xa4D\xd1\xe2D9q\x08 \xf7\x03\x86\xb9\xb74\xc4" +
	"&u\xa7\xd6O\xd3\xeaS\x0cs\x17\xe8B\x8d\xeaB" +
	"\xad\xcf\x13\xf1'\x0cs\xd75\xec\xb5\xf2\xd2\x99\x16\xb5" +
	"B\xa4\xc6N\x97|\xadb\xd2\x97\x96\xbb\xd1q\x81\x89" +
	"\x10[@\xc3\x16\xa8\x1bK\x84\xbd\xd1qE\x08U\x89" +
	"\xeb\xe7-\x0a7`X\x99>\xa8\xe6-\xa9\x13a\xbf" +
	"\x90\x96\xe3\x86P\x1bO\xaa\xff\x80\xbbm<\xf9}\x0a" +
	"\xdc\x82,\xb8[\xf0\xb3e\x1b\xfa{c\x1bn\x1b\xd2" +
	"\xe8c\xedg\x98\x1b\xd4\xb0r\x04[(\xdaY\x86\xb9" +
	"\xaf\xd7\x1d\xc1\xb6C\xe5\x19m\x97V\xe7r\xdd]u" +
	"qQ\xfb\xbf\x00\x00\x00\xff\xffX\xea\x16\xe6"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b526ba661d550a59,
		Nodes: []uint64{
			0x80ae746ee2596b11,
			0x81c2f05a394cf4af,
			0x859f26628fc24358,
			0x9ccdc8676701b412,
			0xa1680744031fdb2d,
			0xa30662f84033036c,
			0xa4f1eb3323f5f582,
			0xa5a3dfadcac04344,
			0xa5cd762cd951a455,
			0xabefa88b9563dbae,
			0xaedffd8f31e7b55d,
			0xb057204d7deadf3f,
			0xb86e6369214c01c8,
			0xbd443b539493bc68,
			0xc2243c65e0340384,
			0xc86a3d38d13eb3ef,
			0xcb9fd56c7057593a,
			0xcd96dafb67a082d0,
			0xd18274dcdc63c41d,
			0xd6f78acca1bc3939,
			0xda96579883444c35,
			0xf35cc4560bbf6ec2,
			0xf416ec09499d9d19,
			0xf98d843bfd7004a3,
			0xfa3e5ce74e25e82a,
			0xfaa35dcac85073a2,
			0xfc6241ed8877b611,
			0xff889853e7b0987f,
		},
		Compressed: true,
	})
}
