// Code generated by capnpc-go. DO NOT EDIT.

package offline

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
)

type HighwayClass uint16

// HighwayClass_TypeID is the unique identifier for the type HighwayClass.
const HighwayClass_TypeID = 0x8f5a4ce47bf80ffa

// Values of HighwayClass.
const (
	HighwayClass_unknown       HighwayClass = 0
	HighwayClass_motorway      HighwayClass = 1
	HighwayClass_motorwayLink  HighwayClass = 2
	HighwayClass_trunk         HighwayClass = 3
	HighwayClass_trunkLink     HighwayClass = 4
	HighwayClass_primary       HighwayClass = 5
	HighwayClass_primaryLink   HighwayClass = 6
	HighwayClass_secondary     HighwayClass = 7
	HighwayClass_secondaryLink HighwayClass = 8
	HighwayClass_tertiary      HighwayClass = 9
	HighwayClass_tertiaryLink  HighwayClass = 10
	HighwayClass_unclassified  HighwayClass = 11
	HighwayClass_residential   HighwayClass = 12
	HighwayClass_livingStreet  HighwayClass = 13
)

// String returns the enum's constant name.
func (c HighwayClass) String() string {
	switch c {
	case HighwayClass_unknown:
		return "unknown"
	case HighwayClass_motorway:
		return "motorway"
	case HighwayClass_motorwayLink:
		return "motorwayLink"
	case HighwayClass_trunk:
		return "trunk"
	case HighwayClass_trunkLink:
		return "trunkLink"
	case HighwayClass_primary:
		return "primary"
	case HighwayClass_primaryLink:
		return "primaryLink"
	case HighwayClass_secondary:
		return "secondary"
	case HighwayClass_secondaryLink:
		return "secondaryLink"
	case HighwayClass_tertiary:
		return "tertiary"
	case HighwayClass_tertiaryLink:
		return "tertiaryLink"
	case HighwayClass_unclassified:
		return "unclassified"
	case HighwayClass_residential:
		return "residential"
	case HighwayClass_livingStreet:
		return "livingStreet"

	default:
		return ""
	}
}

// HighwayClassFromString returns the enum value with a name,
// or the zero value if there's no such value.
func HighwayClassFromString(c string) HighwayClass {
	switch c {
	case "unknown":
		return HighwayClass_unknown
	case "motorway":
		return HighwayClass_motorway
	case "motorwayLink":
		return HighwayClass_motorwayLink
	case "trunk":
		return HighwayClass_trunk
	case "trunkLink":
		return HighwayClass_trunkLink
	case "primary":
		return HighwayClass_primary
	case "primaryLink":
		return HighwayClass_primaryLink
	case "secondary":
		return HighwayClass_secondary
	case "secondaryLink":
		return HighwayClass_secondaryLink
	case "tertiary":
		return HighwayClass_tertiary
	case "tertiaryLink":
		return HighwayClass_tertiaryLink
	case "unclassified":
		return HighwayClass_unclassified
	case "residential":
		return HighwayClass_residential
	case "livingStreet":
		return HighwayClass_livingStreet

	default:
		return 0
	}
}

type HighwayClass_List = capnp.EnumList[HighwayClass]

func NewHighwayClass_List(s *capnp.Segment, sz int32) (HighwayClass_List, error) {
	return capnp.NewEnumList[HighwayClass](s, sz)
}

type Way capnp.Struct

// Way_TypeID is the unique identifier for the type Way.
const Way_TypeID = 0xa4b9c59286b69600

func NewWay(s *capnp.Segment) (Way, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 80, PointerCount: 4})
	return Way(st), err
}

func NewRootWay(s *capnp.Segment) (Way, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 80, PointerCount: 4})
	return Way(st), err
}

func ReadRootWay(msg *capnp.Message) (Way, error) {
	root, err := msg.Root()
	return Way(root.Struct()), err
}

func (s Way) String() string {
	str, _ := text.Marshal(0xa4b9c59286b69600, capnp.Struct(s))
	return str
}

func (s Way) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Way) DecodeFromPtr(p capnp.Ptr) Way {
	return Way(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Way) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Way) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Way) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Way) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Way) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Way) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Way) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Way) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Way) Ref() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Way) HasRef() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Way) RefBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Way) SetRef(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Way) MaxSpeed() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Way) SetMaxSpeed(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Way) MinLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Way) SetMinLat(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s Way) MinLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s Way) SetMinLon(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

func (s Way) MaxLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(24))
}

func (s Way) SetMaxLat(v float64) {
	capnp.Struct(s).SetUint64(24, math.Float64bits(v))
}

func (s Way) MaxLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(32))
}

func (s Way) SetMaxLon(v float64) {
	capnp.Struct(s).SetUint64(32, math.Float64bits(v))
}

func (s Way) Nodes() (Coordinates_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return Coordinates_List(p.List()), err
}

func (s Way) HasNodes() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Way) SetNodes(v Coordinates_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewNodes sets the nodes field to a newly
// allocated Coordinates_List, preferring placement in s's segment.
func (s Way) NewNodes(n int32) (Coordinates_List, error) {
	l, err := NewCoordinates_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Coordinates_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s Way) Lanes() uint8 {
	return capnp.Struct(s).Uint8(40)
}

func (s Way) SetLanes(v uint8) {
	capnp.Struct(s).SetUint8(40, v)
}

func (s Way) AdvisorySpeed() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(48))
}

func (s Way) SetAdvisorySpeed(v float64) {
	capnp.Struct(s).SetUint64(48, math.Float64bits(v))
}

func (s Way) Hazard() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Way) HasHazard() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Way) HazardBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Way) SetHazard(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Way) OneWay() bool {
	return capnp.Struct(s).Bit(328)
}

func (s Way) SetOneWay(v bool) {
	capnp.Struct(s).SetBit(328, v)
}

func (s Way) MaxSpeedForward() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(56))
}

func (s Way) SetMaxSpeedForward(v float64) {
	capnp.Struct(s).SetUint64(56, math.Float64bits(v))
}

func (s Way) MaxSpeedBackward() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(64))
}

func (s Way) SetMaxSpeedBackward(v float64) {
	capnp.Struct(s).SetUint64(64, math.Float64bits(v))
}

func (s Way) Id() int64 {
	return int64(capnp.Struct(s).Uint64(72))
}

func (s Way) SetId(v int64) {
	capnp.Struct(s).SetUint64(72, uint64(v))
}

func (s Way) HighwayClass() HighwayClass {
	return HighwayClass(capnp.Struct(s).Uint16(42))
}

func (s Way) SetHighwayClass(v HighwayClass) {
	capnp.Struct(s).SetUint16(42, uint16(v))
}

// Way_List is a list of Way.
type Way_List = capnp.StructList[Way]

// NewWay creates a new list of Way.
func NewWay_List(s *capnp.Segment, sz int32) (Way_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 80, PointerCount: 4}, sz)
	return capnp.StructList[Way](l), err
}

// Way_Future is a wrapper for a Way promised by a client call.
type Way_Future struct{ *capnp.Future }

func (f Way_Future) Struct() (Way, error) {
	p, err := f.Future.Ptr()
	return Way(p.Struct()), err
}

type Coordinates capnp.Struct

// Coordinates_TypeID is the unique identifier for the type Coordinates.
const Coordinates_TypeID = 0x922b57c60c6a46d1

func NewCoordinates(s *capnp.Segment) (Coordinates, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Coordinates(st), err
}

func NewRootCoordinates(s *capnp.Segment) (Coordinates, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Coordinates(st), err
}

func ReadRootCoordinates(msg *capnp.Message) (Coordinates, error) {
	root, err := msg.Root()
	return Coordinates(root.Struct()), err
}

func (s Coordinates) String() string {
	str, _ := text.Marshal(0x922b57c60c6a46d1, capnp.Struct(s))
	return str
}

func (s Coordinates) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Coordinates) DecodeFromPtr(p capnp.Ptr) Coordinates {
	return Coordinates(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Coordinates) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Coordinates) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Coordinates) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Coordinates) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Coordinates) Latitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Coordinates) SetLatitude(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Coordinates) Longitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Coordinates) SetLongitude(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

// Coordinates_List is a list of Coordinates.
type Coordinates_List = capnp.StructList[Coordinates]

// NewCoordinates creates a new list of Coordinates.
func NewCoordinates_List(s *capnp.Segment, sz int32) (Coordinates_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[Coordinates](l), err
}

// Coordinates_Future is a wrapper for a Coordinates promised by a client call.
type Coordinates_Future struct{ *capnp.Future }

func (f Coordinates_Future) Struct() (Coordinates, error) {
	p, err := f.Future.Ptr()
	return Coordinates(p.Struct()), err
}

type Offline capnp.Struct

// Offline_TypeID is the unique identifier for the type Offline.
const Offline_TypeID = 0xcb5ff253617678e0

func NewOffline(s *capnp.Segment) (Offline, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 1})
	return Offline(st), err
}

func NewRootOffline(s *capnp.Segment) (Offline, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 1})
	return Offline(st), err
}

func ReadRootOffline(msg *capnp.Message) (Offline, error) {
	root, err := msg.Root()
	return Offline(root.Struct()), err
}

func (s Offline) String() string {
	str, _ := text.Marshal(0xcb5ff253617678e0, capnp.Struct(s))
	return str
}

func (s Offline) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Offline) DecodeFromPtr(p capnp.Ptr) Offline {
	return Offline(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Offline) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Offline) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Offline) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Offline) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Offline) MinLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Offline) SetMinLat(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Offline) MinLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Offline) SetMinLon(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s Offline) MaxLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s Offline) SetMaxLat(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

func (s Offline) MaxLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(24))
}

func (s Offline) SetMaxLon(v float64) {
	capnp.Struct(s).SetUint64(24, math.Float64bits(v))
}

func (s Offline) Ways() (Way_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Way_List(p.List()), err
}

func (s Offline) HasWays() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Offline) SetWays(v Way_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewWays sets the ways field to a newly
// allocated Way_List, preferring placement in s's segment.
func (s Offline) NewWays(n int32) (Way_List, error) {
	l, err := NewWay_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Way_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Offline) Overlap() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(32))
}

func (s Offline) SetOverlap(v float64) {
	capnp.Struct(s).SetUint64(32, math.Float64bits(v))
}

// Offline_List is a list of Offline.
type Offline_List = capnp.StructList[Offline]

// NewOffline creates a new list of Offline.
func NewOffline_List(s *capnp.Segment, sz int32) (Offline_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 40, PointerCount: 1}, sz)
	return capnp.StructList[Offline](l), err
}

// Offline_Future is a wrapper for a Offline promised by a client call.
type Offline_Future struct{ *capnp.Future }

func (f Offline_Future) Struct() (Offline, error) {
	p, err := f.Future.Ptr()
	return Offline(p.Struct()), err
}

const schema_da3a0d9284ca402f = "x\xda\xa4\x94M\x88\x1c\xc5\x1b\xc6\x9f\xa7\xba\xe7cw" +
	"g\xd2)\xba\xff\xf0G\x0c+\x9ebD\xf3%(\x8b" +
	"\x90\x90@H\x96\x05\xd3\xe9\xc3\x12!H\xb9\xd3\x93\xf4" +
	"\xceL\xf7\xda3\xfb1\x8a\x04\xc4\x0f\xf4\"\x06#\x06" +
	"\x14\xb2\xb0\x01\x85\x1c\xf4\xa0l \x81\x08\x1bM4\x01" +
	"\x03\x9e<\xe5\xa0\x10!\x07\x15\x85U\xc4\x96\xb77\xf3" +
	"\x11\x10r\xf0\xd2]\xf5{\x9fz\xeb\xa5\xde\xa7j\xc7" +
	"\x93j\xaf\xbd\xb3\xfa\x95\x82\xf2\x1f*\x14\xb3?\x9d\xf5" +
	"\x97~\x98z\xf6m\xe8-*\xdb\xbe\xf7\xebWOU" +
	"'\xbe\x07\xb8\xfb\x10\x8f\xd0=\xc6\x12\xb0\xfb(\xa7\x09" +
	"f7\x0f\xccV\xbe\x9c~\xf4\x14\xfc-\x1c\xd2\xda\"" +
	"9\xa4&\xe9\x1eS%\xc0=\xaa\x16\xc1\xbf\xdf\xfb\xfc" +
	"\xf5SW.\xac\xf8[8:\x90\x16r\xed%5J" +
	"\xf7\x86hw_SoX`vki\xc1\x04\xbf>" +
	"\xf7\x8dd.\x0c\xc9\xf3\xddO\x17\xb7\xd1=W\x94\xe1" +
	"rq\x9ax,\x9b\x09\xd3\xd04\xb7'v\xbd\xde\x8c" +
	"\xe2p{\xb2\xf1\x7f|\xc6\xcc\xc5s\x13\x07\xa3\xe3'" +
	"\x16Mw\x7f\xd3\xb4\xd9>L\xfaOQ\x01zy\x1f" +
	"@\xea3\x93\x00\x95>=\x0b\xd0\xd2\xef\xec\x02h\xeb" +
	"7\x8f\x00,\xe8\xd7DR\xd4/?\x0f\xb0\xa4\xbb\x02" +
	"\xcbz>\x058\xa2_\x90u\xa3\xba%\xeb\xc6t$" +
	"\xbf\x8a\x0eEY\xd5f\x1689\x1f7\xe2d1\xce" +
	"ZI'I\x17M\x17\xc0`\xecLEqc\xbc\x93" +
	"\xce\xc7\x8d,\xffNE1\xd889\x97F-\x93v" +
	"\xb3\xbb\xff)\x94\xa2\xb8\x91\xb5\xc3\x99$\xae\x99\x14\xec" +
	"\x0e\xc6\xe3]\xc9\x91u\xc2\xb4\x13\x994O\xdf\x1f\xe7" +
	"\xe9\xb3\xf9x\xa6i\xda\xed\x08N=\x0akY\x1a\xb6" +
	"\xa3Z\x18wP\x8aL3kF\x0bQ|<\xe8\xc0" +
	"I\xc3\xb0s\x9f#\xdc\x9f$i-\x8aM'l\x03" +
	"r\x84e\xcb\x06l\x02\xfa\x91I\xc0\xdfj\xd1\x7fB" +
	"Q\x93\x1e\x05\xee<\x02\xf8;,\xfaO+fM\xd3" +
	"\x89:\xf3\xb5\x10rRP\x1c\x03\xb3f\x12\x1f\x17\x08" +
	"\x86}\xd6+\xc1\xfa\xd7\x12\xa6\xe5\x04e\xeb\xbd\xbd\xad" +
	"\xddO\xb9\x0d\x08\xce\xd3b\xb0\xca\xc1\xee\xeeg|\x18" +
	"\x08>\x11~\x91\x8aT\x9e4\xdc\xbd\xc0I X\x15" +
	"\xbc&r\x8b\x1e-\xc0\xfd\x82\x13@pQ\xf8U\xe1" +
	"\xb6\xf2h\x03\xee\x95\x9c_\x16~]x\xc1\xf2X\x00" +
	"\xdck9_\x13\xfe\xad\xf0\xa2\xed\xb1\x08\xb87r~" +
	"U\xf8w\xc2K\xca\x13\xbf\xba7\xb9\x0b\x08\xae\x0b\xbf" +
	"-\xbc\xbc\xd5c\x19p\x7f\xcc\xf9-\xe1w\x84\x8f\x14" +
	"=\x8e\x00\xeeOL\x81\xe0\xb6\xf0\xdf\x84\x8fZ\x1eG" +
	"\x01\xf7\x97<\xff\x1d\xe1\xebT\xdc9v\x90\x1e\xc7\x00" +
	"\xf7\xf7<\xf0\xb3\x04\xfe\x92\x05\x95\x92\xc7\x0a\xe0\xfe\xc1" +
	"W\x80`]\xb8\xad\x14u\xb5\xec\xb1\x0a\xb8To\x01" +
	"\x81\xad,\x06\x9b\x85o\x1a\xf1\xb8\x09p\xab\xea\x01 " +
	"(\x0b\xf7\x84;\xff\xf3\xe8\x00\xaeV\xb3@\xb0Y\xf8" +
	"\x83J\xd1\x89M+d\x05\x8a\x15\xb0\x94\x86\xf5\xde8" +
	"k\x99\xa5`.\x0ckC\x9d\xde\xd3\x8a\xe2)\xd3\xb9" +
	"g\x9a\xc4\x83\xa9Y\xba'j\x96\x86\xa2\xe3qR\x0b" +
	"\xdb\xdc\x04\x1e\xb6\xc8\xcd\x83\xf7\x06\x148\xde4q\xd8" +
	"f\x11\x8aE03\xb5\x85\xa8\x9d\xa4]\x8c\xe75\xf4" +
	"s\x9e0/\x9a\xb4\xd6\xabqO\x12\x87\xd3\xa6KB" +
	"\x91C%\xf3\x80\\\xcc\xb46\xb0h?\xb2\xcf\xcc4" +
	"\xf2P?fE5\x16\xa0X\x00\xb3\x13w_\x178" +
	"r\xd7\xe8\x0c\x1eP\x90\xce}m\xfdL\xbd\xee\xc8T" +
	"\x9c\xfd\xff\xfe\xa5:3\x01\xf8\xefZ\xf4\xcf\x0e]\xaa" +
	"\x0f\x05\xbeo\xd1_Q\xd4j\xc3\xd4zY\xe0\x07\x16" +
	"\xfd\x8f\xc4\xd1V\xeeh}N\xe0Y\x8b\xfeyE\xda" +
	"\xb9\x9b\xf5\xc7\xdb\x00\x7f\xc5\xa2\x7fY\xacl\xe7V\xd6" +
	"\x97\xf6\x01\xfe\xaaE\x7fM\xfd\xa7N9\x8b\xa6;h" +
	"T\xef\xad\xdfh\xd3\xc9d!L\x9bf\xae\xa7\xfd'" +
	"\x00\x00\xff\xff\xe2\x9bvs"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_da3a0d9284ca402f,
		Nodes: []uint64{
			0x8f5a4ce47bf80ffa,
			0x922b57c60c6a46d1,
			0xa4b9c59286b69600,
			0xcb5ff253617678e0,
		},
		Compressed: true,
	})
}
